-- BRAE.QA_TTC2_REGISTRO definition

CREATE TABLE "BRAE"."QA_TTC2_REGISTRO" 
   (	"TC2_NIU" NUMBER, 
	"TC2_INFO_PREDIAL" NUMBER, 
	"TC2_CEDULA_CATASTRAL" VARCHAR2(100), 
	"TC2_TIPO_FACTURA" NUMBER, 
	"TC2_ID_FACTURA" NUMBER, 
	"TC2_TIPO_TARIFA" NUMBER, 
	"TC2_TIPO_LECTURA" NUMBER, 
	"TC2_CONSUMO_USR" NUMBER, 
	"TC2_CONSUMO_SUBS" NUMBER, 
	"TC2_VALOR_SUBS_USR" NUMBER, 
	"TC2_VALOR_REFACT_SUBS_USR" NUMBER, 
	"TC2_VALOR_FOES_APLI_CONS" NUMBER, 
	"TC2_VALOR_REFACT_FOES_APLI" NUMBER, 
	"TC2_VALOR_CONTRIBUCION" NUMBER, 
	"TC2_VALOR_REFACT_CONT" NUMBER, 
	"TC2_TVC" NUMBER, 
	"TC2_VC" NUMBER, 
	"TC2_VCD" NUMBER, 
	"TC2_VCF" NUMBER, 
	"TC2_CEC_KWH" NUMBER, 
	"TC2_CONPU" NUMBER, 
	"TC2_THC" NUMBER, 
	"TC2_HC" NUMBER, 
	"TC2_REFACT_COMPENSACION" NUMBER, 
	"TC2_TIPO_MEDIDOR" NUMBER, 
	"TC2_TARIFA_APLICADA" NUMBER, 
	"TC2_FECHA_PUB_TARIFA_APLI" DATE, 
	"TC2_VALOR_SUBSIDIO_REC" NUMBER, 
	"TC2_ID_MERCADO" NUMBER, 
	"TC2_AGNIO_REPORTE" NUMBER, 
	"TC2_MES_REPORTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TSP_DATOS_BRAE" ;