CREATE OR REPLACE PROCEDURE BRAE.QA_PTC1_INSERT_OBS(FECHAOPERACION IN  DATE, USR IN VARCHAR2, ESTADO OUT NUMBER, MESSAGE OUT VARCHAR2)
AS

QUANTITY_1 NUMBER;
QUANTITY_2 NUMBER;
ID_COMER NUMBER;
AJUSTADO NUMBER;
VAR_VALID VARCHAR2(100);

BEGIN

	--Verificar duplicidad de usuario
	SELECT TC1_IDCOMER INTO ID_COMER
	FROM   QA_TTC1_OBS
	WHERE  TC1_PERIODO = TO_CHAR(FECHAOPERACION,'YYYYMM')
	AND    TC1_TC1 = USR
	;

	SELECT COUNT(DISTINCT TC1_TC1) AS QUANTITY
	INTO QUANTITY_1
	FROM QA_TTC1_TEMP 
	WHERE TC1_TC1 = USR
	AND   TC1_IDCOMER = ID_COMER
	AND   TC1_PERIODO = TO_CHAR(FECHAOPERACION,'YYYYMM')
	;

	SELECT COUNT(TC1_TC1) AS QUANTITY
	INTO QUANTITY_2
	FROM QA_TTC1_TEMP 
	WHERE TC1_TC1 = USR
	AND   TC1_PERIODO = TO_CHAR(FECHAOPERACION,'YYYYMM')
	;

	IF (QUANTITY_1 = 0 AND QUANTITY_2 < 2) THEN
		--ADD IT
	  INSERT INTO QA_TTC1_TEMP
	  SELECT TC1_TC1 --Verificar duplicidad de usuario
			,TC1_CODCONEX --Verificar
			,TC1_TIPCONEX --Verificar
			,TC1_NT
			,TC1_NTP
			,TC1_PROPACTIV
			,TC1_CONEXRED 
			,TC1_IDCOMER --Verificar duplicidad de usuario
			,TC1_IDMERC --Asignar
			,TC1_GC --Asignar
			,TC1_CODFRONCOM
			,TC1_CODCIRC --Asignar
			,TC1_CODTRANSF --Asignar
			,TC1_CODDANE --Verificar
			,TC1_UBIC
			,TC1_DIREC
			,TC1_CONESP
			,TC1_CODARESP
			,TC1_TIPARESP
			,TC1_ESTSECT
			,TC1_ALTITUD 
			,TC1_LONGITUD --Formatear
			,TC1_LATITUD --Formatear
			,TC1_AUTOGEN
			,TC1_EXPENER
			,TC1_CAPAUTOGENR
			,TC1_TIPGENR
			,TC1_CODFRONEXP
			,TC1_FENTGEN
			,TC1_CONTRESP
			,TC1_CAPCONTRESP
			,NULL TC1_PERIODO --Asignar
			,NULL TC1_IUA --Asignar 
		FROM  QA_TTC1_OBS 
		WHERE TC1_PERIODO = TO_CHAR(FECHAOPERACION,'YYYYMM')
		AND   TC1_TC1 = USR;
		COMMIT;

	ELSE
		--DO NOT ADD IT
		MESSAGE := 'El usuario que intenta agregar ya existe en la tabla temporal TC1';
		DELETE FROM QA_TTC1_TEMP WHERE TC1_PERIODO IS NULL;
		COMMIT;
		RETURN;
	END IF;


	--Verificar TC1_CODCONEX
	SELECT COUNT(DISTINCT FDD_AJUSTADO) - 1 AS QUANTITY 
	INTO AJUSTADO
	FROM   QA_TFDDREGISTRO
	WHERE  TO_CHAR(FDD_FINICIAL,'YYYYMM') = TO_CHAR(FECHAOPERACION,'YYYYMM'); 
	
	IF (AJUSTADO = 0) THEN
	
		UPDATE QA_TTC1_TEMP T
		SET TC1_CODTRANSF = NVL((SELECT TT2_CODE_IUA FROM QA_TTT2_REGISTRO WHERE TT2_ESTADO = 'OPERACION' AND TT2_CODIGOELEMENTO = T.TC1_CODCONEX),'NA')
		   ,TC1_IUA       = NVL((SELECT TT2_CODE_IUA FROM QA_TTT2_REGISTRO WHERE TT2_ESTADO = 'OPERACION' AND TT2_CODIGOELEMENTO = T.TC1_CODCONEX),'NA')
		   ,TC1_IDMERC    = '161'
		   ,TC1_TIPCONEX  = 'T'
		   ,TC1_LONGITUD  = RPAD(TC1_LONGITUD,INSTR(TC1_LONGITUD,'.') + 6, 0)
           ,TC1_LATITUD   = RPAD(TC1_LATITUD, INSTR(TC1_LATITUD, '.') + 6, 0)
		   WHERE TC1_PERIODO IS NULL;
		COMMIT;
	
	END IF;

	IF (AJUSTADO = 1) THEN
	
		UPDATE QA_TTC1_TEMP T
		SET TC1_CODTRANSF = NVL((SELECT DISTINCT TC1_IUA FROM QA_TTC1_TEMP WHERE TC1_CODCONEX = T.TC1_CODCONEX),'NA')
		   ,TC1_IUA       = NVL((SELECT DISTINCT TC1_IUA FROM QA_TTC1_TEMP WHERE TC1_CODCONEX = T.TC1_CODCONEX),'NA')	
		   ,TC1_IDMERC    = '161'
		   ,TC1_TIPCONEX  = 'T'
		   ,TC1_LONGITUD  = RPAD(TC1_LONGITUD,INSTR(TC1_LONGITUD,'.') + 6, 0)
           ,TC1_LATITUD   = RPAD(TC1_LATITUD, INSTR(TC1_LATITUD, '.') + 6, 0)
		WHERE TC1_PERIODO IS NULL;
		COMMIT;
	
	END IF;
	
	SELECT DISTINCT TC1_CODTRANSF
	INTO VAR_VALID
	FROM QA_TTC1_TEMP 
	WHERE TC1_PERIODO IS NULL;

	IF VAR_VALID = 'NA' THEN
		MESSAGE := 'El codigo del transformador no es valido';
		DELETE FROM QA_TTC1_TEMP WHERE TC1_PERIODO IS NULL;
		COMMIT;
		RETURN;
	END IF;

    --CORREGIR CARACTERES EN EL CAMPO DIRRECION
    UPDATE QA_TTC1_TEMP
    SET TC1_DIREC = SUBSTR(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(TC1_DIREC,'Á','A'),'É','E'),'Í','I'),'Ó','O'),'Ú','U'),'á','a'),'é','e'),'í','i'),'ó','o'),'ú','u'),'Ñ','N'),'(',' '),')',' '),'\',' '),'/',' '),',',' '),'.',' '),'°',' '),'À',' '),'1º',' '),'2°',' '),'3°',' '),'º',' '),'·',' '),'ñ','n'),'´',' '),' ',' '),'#',' '),'ª',' '),'Ò',' '),'¿',''),'Â¿',''),'Â',''),1,50)
    WHERE TC1_PERIODO IS NULL;
    COMMIT;
   
    --COMPLETAR EL CAMPO CODIGO DE FRONTERA PARA LOS USUARIOS INCUMBENTES CON "OR0001"
    UPDATE QA_TTC1_TEMP
    SET   TC1_CODFRONCOM = 'OR0001'
    WHERE TC1_CODFRONCOM IS NULL
    AND   TC1_IDCOMER = '604'
    AND   TC1_PERIODO IS NULL
    ;
    COMMIT;

	--Verficar 	TC1_CODDANE
   	SELECT NVL(TC1_MUNICIPIO,'NA')
   	INTO VAR_VALID
   	FROM QA_TTC1_TEMP
   	LEFT OUTER JOIN QA_TTC1_DIVIPOLA ON TC1_COD_CENTRO_POBLADO = TC1_CODDANE
   	WHERE TC1_PERIODO IS NULL;
   
   	IF VAR_VALID = 'NA' THEN 
   		
		MESSAGE := 'El codigo DANE no es valido';
		DELETE FROM QA_TTC1_TEMP WHERE TC1_PERIODO IS NULL;
		COMMIT;
		RETURN;
	
   	END IF;
	--Asignar 	TC1_PERIODO
   
   	UPDATE QA_TTC1_TEMP 
   	SET TC1_PERIODO = TO_CHAR(FECHAOPERACION,'YYYYMM')
   	WHERE TC1_PERIODO IS NULL;
   	COMMIT;

	--Eliminar el usuario de la tabla observaciones, luego de verificar que todo ha sido exitoso
	DELETE FROM QA_TTC1_OBS 
	WHERE TC1_PERIODO = TO_CHAR(FECHAOPERACION,'YYYYMM')
	AND   TC1_TC1 = USR;
	COMMIT;

	MESSAGE := 'El registro se ha insertado exitosamente';

END QA_PTC1_INSERT_OBS;


