CREATE OR REPLACE PROCEDURE BRAE.QA_PTC1_INSERT_OBS(FECHAOPERACION IN  DATE, USR IN VARCHAR2)
AS


BEGIN
	
	--ELIMINACION DE DUPLICADOS DE LA TABLA OBSERVACIONES
	
    
	
	--SELECT * FROM QA_TTC1_OBS 
	--WHERE TC1_PERIODO = 202307;
    NULL;

END QA_PTC1_INSERT_OBS;


