create table QA_TTT9
(
    TT9_CODIGOMERCADO  NUMBER,
    TT9_CODIGOEVENTO   VARCHAR2(10),
    TT9_FINICIAL       DATE,
    TT9_CODIGOELEMENTO VARCHAR2(16),
    TT9_TIPOELEMENTO   VARCHAR2(2),
    TT9_TIPOAJUSTE     NUMBER,
    TT9_PERIODO_OP     DATE
)
/


