CREATE OR REPLACE PROCEDURE BRAE.QA_PTT3_CERTIFICAR(FECHAOPERACION DATE)
AS

BEGIN

    UPDATE QA_TTT3_REGISTRO 
    SET   TT3_CERTIFICADO = 1
         ,TT3_FCERTIFICACION = SYSDATE
    WHERE TT3_PERIODO_OP =  TRUNC(FECHAOPERACION)
    AND   TT3_CERTIFICADO = 0;
    
    IF SQL%FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Reporte certficado correctamente: '||TRUNC(FECHAOPERACION));
    ELSE
        DBMS_OUTPUT.PUT_LINE('Error, no es posible ejecutar el procedimiento: '||TRUNC(FECHAOPERACION));
    END IF;
    
    COMMIT;
        
END QA_PTT3_CERTIFICAR;
/