create table QA_TCONSOLIDADO_OR
(
    FDD_YEAR           NUMBER,
    FDD_MONTH          NUMBER,
    FDD_COD_ASIC       VARCHAR2(10),
    FDD_CODIGOEVENTO   VARCHAR2(10),
    FDD_CAUSA_CREG     VARCHAR2(10),
    FDD_IUA            VARCHAR2(20),
    FDD_TIPOELEMENTO   VARCHAR2(2),
    FDD_DUR_NOCTURNA   NUMBER,
    FDD_DURACION       NUMBER,
    FDD_USRS_AFECTADOS NUMBER
)
/


