create table RESUMEN
(
    BUSCADOR        VARCHAR2(50),
    SUBESTACION     VARCHAR2(50),
    CLASIFICACION   VARCHAR2(2),
    TRAFO           VARCHAR2(50),
    FINICIO         DATE,
    FFIN            DATE,
    DESCRIPCION     VARCHAR2(500),
    CODIGO_PROYECTO VARCHAR2(100),
    ID_DESCONEXION  NUMBER
)
/


