CREATE OR REPLACE PROCEDURE BRAE.QA_PFDDREPORTAR_AJ(FECHAOPERACION  DATE,
                        V_FDD_RADICADO  BRAE.QA_TFDDREGISTRO.FDD_RADICADO%TYPE)
AS

  TYPE T_QA_TFDDREPORTAR_AJ IS TABLE OF QA_TFDDREPORTE_AJ%ROWTYPE;
  V_QA_TFDDREPORTAR_AJ T_QA_TFDDREPORTAR_AJ;

BEGIN

     --ELIMINAR POSIBLES REGISTROS ESCRITOS DEL MISMO PERIODO
       DELETE
       FROM QA_TFDDREPORTE_AJ
       WHERE FDR_PERIODO_OP=TRUNC(FECHAOPERACION);
       COMMIT;

     --ACTUALIZAR LA TABAL QA_TFDDPRELIMINAR_AJ CON CODIGO DE RADICADO GENERADO POR TT9

       UPDATE QA_TFDDPRELIMINAR_AJ
          SET FDD_RADICADO=V_FDD_RADICADO,
              FDD_AJUSTADO='S';
       COMMIT;

     --INSERTAR REGISTROS EN LA TABLA QA_TFDDREPORTE_AJ
      SELECT  TRUNC(FECHAOPERACION) AS FDD_PERIODO
             ,TO_NUMBER(FDD_CODIGOEVENTO) AS FDD_CODIGOEVENTO
             ,TO_DATE(TO_CHAR(FDD_FINICIAL,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') AS FDD_FINICIAL
             ,TO_DATE(TO_CHAR(FDD_FFINAL  ,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') AS FDD_FFINAL
             ,FDD_CODIGOELEMENTO
             ,(CASE WHEN(FDD_TIPOELEMENTO='Transformer') THEN(1) ELSE (2) END ) AS FDD_TIPOELEMENTO
             ,TO_NUMBER(FDD_CAUSA_CREG) AS FDD_CAUSA
             ,FDD_CONTINUIDAD
             ,0 AS FDD_EXCLUIDOZNI
             ,(CASE WHEN FDD_CODIGOGENERADOR IS NULL THEN 0 ELSE 1 END) AS FDD_AFECTACONGEN
             ,(CASE WHEN FDD_USUARIOAP='S' THEN 1 ELSE 0 END) AS FDD_USUARIOAP
             ,FDD_TIPOAJUSTE
             ,V_FDD_RADICADO
             ,FDD_IUA
      BULK  COLLECT INTO V_QA_TFDDREPORTAR_AJ
      FROM QA_TFDDPRELIMINAR_AJ;

      IF V_QA_TFDDREPORTAR_AJ IS NOT EMPTY THEN
         FORALL i IN V_QA_TFDDREPORTAR_AJ.FIRST .. V_QA_TFDDREPORTAR_AJ.LAST
            INSERT INTO QA_TFDDREPORTE_AJ
            VALUES V_QA_TFDDREPORTAR_AJ(i);
      END IF;

END QA_PFDDREPORTAR_AJ;