CREATE OR REPLACE PROCEDURE BRAE.QA_PCS3_TEST(FECHAOPERACION DATE)
AS
    --INCENTIVOS DE CALIDAD MEDIA
    --IC_SAIDI_(j,t)=If_SAIDI_(j,t)+Iv_SAIDI_(j,t)
    --Para determinar el valor del incentivo fijo, If_SAIDIj,t, se debe utilizar el indicador de calidad SAIDIj,t-1 y tener en cuenta lo siguiente:

         V_IF_SAIDI NUMBER;
         V_IV_SAIDI NUMBER;
         V_IF_SAIFI NUMBER;
         V_IV_SAIFI NUMBER;
         V_IV_SAIDI_MAX NUMBER;
         V_IV_SAIFI_MAX NUMBER;
         V_SAIDI_CI NUMBER;
         V_SAIFI_CI NUMBER;

         
         --a. Si el SAIDIj,t-1 se encuentra dentro de los límites de la banda de indiferencia de su meta para el año t-1, el If_SAIDIj,t será igual a cero.



         --c. Si el SAIDIj,t-1 es mayor que el límite superior de la banda de indiferencia de su meta para el año t-1, el If_SAIDIj,t se obtiene utilizando la siguiente expresión:
                      --If_SAIDI_(j,t)=-0,04*máx(0,04*∑_(n=1)^3 Crr_(j,n)   ,∑_(n=1)^3 BRAEN_(j,n,t-1) )

BEGIN
         --PERIODO DE OPERACION
         INSERT INTO BRAE.QA_TCS3_TEST (CS3_PERIODO_OP) VALUES (TRUNC(FECHAOPERACION));
          
          --ACTUALIZAR VARIABLES
         --SAIDI_CI_(j,t-1)=max�?�(SAIDI_LP ,SAIDI_(j,t-1) )
         SELECT (CASE
                    WHEN ((SELECT CS1_SAIDI FROM QA_TCS1 WHERE CS1_PERIODO_OP=TO_DATE('01/12'||(TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))-1),'DD/MM/YYYY'))>=(SELECT SAIDI_LP FROM QA_TMETAS_CALMEDIA WHERE PERIODO_META=(TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))-1))) 
                    THEN (SELECT CS1_SAIDI FROM QA_TCS1 WHERE CS1_PERIODO_OP=TO_DATE('01/12'||(TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))-1),'DD/MM/YYYY'))
                    ELSE (SELECT SAIDI_LP FROM QA_TMETAS_CALMEDIA WHERE PERIODO_META=(TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))-1))
                    END)
         INTO V_SAIDI_CI            
         FROM DUAL;                

         --Ivi_SAIDImax_(j,t)=0,04*∑_(n=1)^3 BRAEN_(j,n,t-1)
          SELECT  0.04*(CB_BRAENJ1+CB_BRAENJ2+CB_BRAENJ3) 
          INTO V_IV_SAIDI_MAX
          FROM QA_TCBRAEN_TEST 
          WHERE CB_PERIODO=(TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))-1);

         --SAIFI_CI_(j,t-1)=max�?�(SAIFI_LP ,SAIFI_(j,t-1) )
         SELECT (CASE
                    WHEN ((SELECT CS1_SAIFI FROM QA_TCS1 WHERE CS1_PERIODO_OP=TO_DATE('01/12'||(TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))-1),'DD/MM/YYYY'))>=(SELECT SAIFI_LP FROM QA_TMETAS_CALMEDIA WHERE PERIODO_META=(TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))-1))) 
                    THEN (SELECT CS1_SAIFI FROM QA_TCS1 WHERE CS1_PERIODO_OP=TO_DATE('01/12'||(TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))-1),'DD/MM/YYYY'))
                    ELSE (SELECT SAIFI_LP FROM QA_TMETAS_CALMEDIA WHERE PERIODO_META=(TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))-1))
                    END)
         INTO V_SAIFI_CI            
         FROM DUAL;

         --Ivi_SAIFImax_(j,t)=0,04*∑_(n=1)^3 BRAEN_(j,n,t-1) 
          SELECT  0.04*(CB_BRAENJ1+CB_BRAENJ2+CB_BRAENJ3) 
          INTO V_IV_SAIFI_MAX
          FROM QA_TCBRAEN_TEST 
          WHERE CB_PERIODO=(TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))-1); 

         --b. Si el SAIDIj,t-1 es menor que el límite inferior de la banda de indiferencia de su meta para el año t-1, el If_SAIDIj,t se obtiene utilizando la siguiente expresión:
         --If_SAIDI_(j,t)=0,04*∑_(n=1)^3 BRAEN_(j,n,t-1) 
         --CALCULAR INCENTIVO FIJO POR DURACION Y FRECUENCIA
          UPDATE BRAE.QA_TCS3_TEST
          SET CS3_IF_SAIDI = 0.04*(SELECT  (CB_BRAENJ1+CB_BRAENJ2+CB_BRAENJ3) FROM QA_TCBRAEN_TEST WHERE CB_PERIODO=(TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))-1)),
              CS3_IF_SAIFI = 0.04*(SELECT  (CB_BRAENJ1+CB_BRAENJ2+CB_BRAENJ3) FROM QA_TCBRAEN_TEST WHERE CB_PERIODO=(TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))-1))
          WHERE CS3_PERIODO_OP=TRUNC(FECHAOPERACION);

         -- f.	Si el SAIDIj,t-1 es menor que el límite inferior de la banda de indiferencia de su meta para el año t-1, el Iv_SAIDIj,t se obtiene utilizando la siguiente expresión:         
         --Iv_SAIDI_(j,t)=(0,92*SAIDI_R_j-SAIDI_CI_(j,t-1) )*Ivi_SAIDI max_(j,t)/(0,92*SAIDI_R_j-SAIDI_LP)
          UPDATE BRAE.QA_TCS3_TEST
          SET CS3_IV_SAIDI = (((0.92*(SELECT SAIDI_RJ FROM QA_TMETAS_CALMEDIA WHERE PERIODO_META=(TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))-1)))-V_SAIDI_CI)
          *(V_IV_SAIDI_MAX
          /((0.92*(SELECT SAIDI_RJ FROM QA_TMETAS_CALMEDIA WHERE PERIODO_META=(TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))-1)))
          -(SELECT SAIDI_LP FROM QA_TMETAS_CALMEDIA WHERE PERIODO_META=(TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))-1)))))
          WHERE CS3_PERIODO_OP=TRUNC(FECHAOPERACION);
        
         --f. 	Si el SAIFIj,t-1 es menor que el límite inferior de la banda de indiferencia de su meta para el año t-1, el Iv_SAIFIj,t se obtiene utilizando la siguiente expresión:
         --Iv_SAIFI_(t,j)=(0,92*SAIFI_R_j-SAIFI_CI_(j,t-1) )*Ivi_SAIFI max_(j,t)/(0,92*SAIFI_R_j-SAIFI_LP)
         UPDATE BRAE.QA_TCS3_TEST
          SET CS3_IV_SAIFI = (((0.92*(SELECT SAIFI_RJ FROM QA_TMETAS_CALMEDIA WHERE PERIODO_META=(TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))-1)))-V_SAIFI_CI)
          *(V_IV_SAIFI_MAX
          /((0.92*(SELECT SAIFI_RJ FROM QA_TMETAS_CALMEDIA WHERE PERIODO_META=(TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))-1)))
          -(SELECT SAIFI_LP FROM QA_TMETAS_CALMEDIA WHERE PERIODO_META=(TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))-1)))))
          WHERE CS3_PERIODO_OP=TRUNC(FECHAOPERACION);
               
         --- ACTUALIZAR CAMPOS AGRUPADOS Y PRORRATEADOS DEL CS2
          UPDATE BRAE.QA_TCS3_TEST
          SET CS3_IC_SAIDI = (SELECT CS3_IF_SAIDI + CS3_IV_SAIDI FROM QA_TCS3_TEST WHERE CS3_PERIODO_OP=TRUNC(FECHAOPERACION)),
              CS3_IC_SAIFI = (SELECT CS3_IF_SAIFI + CS3_IV_SAIFI FROM QA_TCS3_TEST WHERE CS3_PERIODO_OP=TRUNC(FECHAOPERACION))
          WHERE CS3_PERIODO_OP=TRUNC(FECHAOPERACION);

        UPDATE BRAE.QA_TCS3_TEST
          SET CS3_INCD1= CS3_IC_SAIDI * (SELECT (CB_BRAEJ1/(CB_BRAEJ1+CB_BRAEJ2+CB_BRAEJ3)) FROM QA_TCBRAEN_TEST WHERE CB_PERIODO=(TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))-1)),
              CS3_INCD2= CS3_IC_SAIDI * (SELECT (CB_BRAEJ2/(CB_BRAEJ1+CB_BRAEJ2+CB_BRAEJ3)) FROM QA_TCBRAEN_TEST WHERE CB_PERIODO=(TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))-1)),
              CS3_INCD3= CS3_IC_SAIDI * (SELECT (CB_BRAEJ3/(CB_BRAEJ1+CB_BRAEJ2+CB_BRAEJ3)) FROM QA_TCBRAEN_TEST WHERE CB_PERIODO=(TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))-1)),
              CS3_INCF1= CS3_IC_SAIFI * (SELECT (CB_BRAEJ1/(CB_BRAEJ1+CB_BRAEJ2+CB_BRAEJ3)) FROM QA_TCBRAEN_TEST WHERE CB_PERIODO=(TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))-1)),
              CS3_INCF2= CS3_IC_SAIFI * (SELECT (CB_BRAEJ2/(CB_BRAEJ1+CB_BRAEJ2+CB_BRAEJ3)) FROM QA_TCBRAEN_TEST WHERE CB_PERIODO=(TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))-1)),
              CS3_INCF3= CS3_IC_SAIFI * (SELECT (CB_BRAEJ3/(CB_BRAEJ1+CB_BRAEJ2+CB_BRAEJ3)) FROM QA_TCBRAEN_TEST WHERE CB_PERIODO=(TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))-1))
          WHERE CS3_PERIODO_OP=TRUNC(FECHAOPERACION);
        COMMIT;

END QA_PCS3_TEST;







