CREATE OR REPLACE PROCEDURE BRAE.QA_PTT2_CERTIFICAR(FECHAOPERACION DATE)
AS

BEGIN

    UPDATE QA_TTT2_REGISTRO 
    SET   TT2_ESTADOREPORTE = 1
    WHERE TT2_PERIODO_OP =  TRUNC(FECHAOPERACION)
    AND   TT2_ESTADOREPORTE = 0;
    
    IF SQL%FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Reporte certficado correctamente: '||TRUNC(FECHAOPERACION));
    ELSE
        DBMS_OUTPUT.PUT_LINE('Error, no es posible ejecutar el procedimiento: '||TRUNC(FECHAOPERACION));
    END IF;
    
    COMMIT;
        
END QA_PTT2_CERTIFICAR;
/