CREATE OR REPLACE PROCEDURE QA_PBRA11_REPORTE(FECHAOPERACION DATE) AS

    TYPE VAR_TABLE IS TABLE OF QA_TBRA11_REPORTE%ROWTYPE;
    QA_VBRA11_REPORTE VAR_TABLE;
    
    CANT     NUMBER;
    AJUSTADO NUMBER;
  
BEGIN
    --VALIDACIONES
    SELECT COUNT(*)
    INTO CANT
    FROM  BRAE.QA_TBRA11_REPORTE
    WHERE BRA11_PERIODO_OP =  TRUNC(FECHAOPERACION);

    --VERIFICACION DE ACCION DE AJUSTES REALIZADOS EN LA BASE DE DATOS PARA EL PERIODO 
    SELECT COUNT(DISTINCT FDD_AJUSTADO) AS AJUSTADO
    INTO AJUSTADO
    FROM QA_TFDDREGISTRO
    WHERE TRUNC(FDD_FINICIAL,'MM') = TRUNC(FECHAOPERACION)
    AND   FDD_AJUSTADO = 'S'
    ;

    IF AJUSTADO = 1 AND CANT = 0 THEN 
    
        --INSERCION DE REGISTROS 
        INSERT INTO BRAE.QA_TBRA11_REPORTE
        SELECT   BRA11_PERIODO_OP
                ,BRA11_CODIGOELEMENTO
                ,BRA11_CODIGOPROYECTO
                ,BRA11_IUL
                ,BRA11_CODE_IUA
                ,BRA11_CODE_IUA_PRO
                ,BRA11_UNIDAD_CONSTRUCTIVA
                ,BRA11_RPP
                ,BRA11_SALINIDAD
                ,BRA11_TIPOINVERSION
                ,BRA11_OBSERVACIONES
                ,TO_NUMBER(TO_CHAR(BRA11_FESTADO,'YYYY')) AS BRA11_FESTADO
                ,BRA11_REMUNERACION_PENDIENTE
                ,BRA11_ESTADO
                ,BRA11_RESMETODOLOGIA
                ,BRA11_ALTERNATIVA_VALORACION 
                ,BRA11_ID_PLAN
                ,BRA11_CANTIDAD_REPOSICIONES
                ,BRA11_IDMERCADO
        FROM QA_TBRA11_REGISTRO
        WHERE BRA11_PERIODO_OP=TRUNC(FECHAOPERACION);
        COMMIT;
        
    END IF;
    
END QA_PBRA11_REPORTE;