
CREATE TABLE QA_TTT9
(
 TT9_CODIGOMERCADO  NUMBER
,TT9_CODIGOEVENTO   VARCHAR2(10)
,TT9_FINICIAL       DATE
,TT9_CODIGOELEMENTO VARCHAR2(16)
,TT9_TIPOELEMENTO   VARCHAR2(2)
,TT9_TIPOAJUSTE     NUMBER
,TT9_PERIODO_OP     DATE
,CONCATENAR         VARCHAR2(80)
);


CREATE TABLE BRAE.QA_TCONSUMOSDIA
(
  CONS_ELEMENTO  VARCHAR2(32 BYTE),
  CONS_PERIODO   DATE,
  CONS_DIARIO    NUMBER
);


CREATE TABLE BRAE.QA_TCS2
(
  CS2_PERIODO_OP      DATE,
  CS2_NIU             NUMBER,
  CS2_DIU             NUMBER(15,5),
  CS2_DIUM            NUMBER(15,5),
  CS2_FIU             NUMBER,
  CS2_FIUM            NUMBER,
  CS2_IDMERCADO       NUMBER,
  CS2_FRECUENCIA_C1   NUMBER,
  CS2_DURACION_C1     NUMBER(15,5),
  CS2_FRECUENCIA_C2   NUMBER,
  CS2_DURACION_C2     NUMBER(15,5),
  CS2_FRECUENCIA_C3   NUMBER,
  CS2_DURACION_C3     NUMBER(15,5),
  CS2_FRECUENCIA_C4   NUMBER,
  CS2_DURACION_C4     NUMBER(15,5),
  CS2_FRECUENCIA_C5   NUMBER,
  CS2_DURACION_C5     NUMBER(15,5),
  CS2_FRECUENCIA_C6   NUMBER,
  CS2_DURACION_C6     NUMBER(15,5),
  CS2_FRECUENCIA_C7   NUMBER,
  CS2_DURACION_C7     NUMBER(15,5),
  CS2_FRECUENCIA_C8   NUMBER,
  CS2_DURACION_C8     NUMBER(15,5),
  CS2_FRECUENCIA_C9   NUMBER,
  CS2_DURACION_C9     NUMBER(15,5),
  CS2_FRECUENCIA_C10  NUMBER,
  CS2_DURACION_C10    NUMBER(15,5),
  CS2_FRECUENCIA_C11  NUMBER,
  CS2_DURACION_C11    NUMBER(15,5),
  CS2_FRECUENCIA_C12  NUMBER,
  CS2_DURACION_C12    NUMBER(15,5),
  CS2_FRECUENCIA_C13  NUMBER,
  CS2_DURACION_C13    NUMBER(15,5),
  CS2_FRECUENCIA_C14  NUMBER,
  CS2_DURACION_C14    NUMBER(15,5),
  CS2_FRECUENCIA_C15  NUMBER,
  CS2_DURACION_C15    NUMBER(15,5)
);

CREATE TABLE BRAE.QA_TCS3
(
  CS3_PERIODO_OP  DATE,
  CS3_INCD1       NUMBER,
  CS3_INCD2       NUMBER,
  CS3_INCD3       NUMBER,
  CS3_INCF1       NUMBER,
  CS3_INCF2       NUMBER,
  CS3_INCF3       NUMBER,
  CS3_IC_SAIDI    NUMBER,
  CS3_IC_SAIFI    NUMBER,
  CS3_IF_SAIDI    NUMBER,
  CS3_IF_SAIFI    NUMBER,
  CS3_IV_SAIDI    NUMBER,
  CS3_IV_SAIFI    NUMBER
);


 CREATE TABLE BRAE.QA_TCBRAEN
 (
  CB_PERIODO  NUMBER,
  CB_Crrj4    NUMBER,
  CB_Crrj3    NUMBER,
  CB_Crrj2    NUMBER,
  CB_Crrj1    NUMBER,
  CB_CRRj     NUMBER,
  CB_BRAENj4  NUMBER,
  CB_BRAENj3  NUMBER,
  CB_BRAENj2  NUMBER,
  CB_BRAENj1  NUMBER,
  CB_BRAENjT  NUMBER,
  CB_BRAEJ4   NUMBER,
  CB_BRAEJ3   NUMBER,
  CB_BRAEJ2   NUMBER,
  CB_BRAEJ1   NUMBER,
  CB_BRAEJT   NUMBER

 );


CREATE TABLE BRAE.QA_TCSX
(
  CSX_TRANSFOR           VARCHAR2(15 BYTE),
  CSX_DIU                NUMBER,
  CSX_DIUM               NUMBER,
  CSX_FIU                NUMBER,
  CSX_FIUM               NUMBER,
  CSX_IDMERCADO          NUMBER,
  CSX_FRECUENCIA_C1      NUMBER,
  CSX_DURACION_C1        NUMBER,
  CSX_FRECUENCIA_C2      NUMBER,
  CSX_DURACION_C2        NUMBER,
  CSX_FRECUENCIA_C3      NUMBER,
  CSX_DURACION_C3        NUMBER,
  CSX_FRECUENCIA_C4      NUMBER,
  CSX_DURACION_C4        NUMBER,
  CSX_FRECUENCIA_C5      NUMBER,
  CSX_DURACION_C5        NUMBER,
  CSX_FRECUENCIA_C6      NUMBER,
  CSX_DURACION_C6        NUMBER,
  CSX_FRECUENCIA_C7      NUMBER,
  CSX_DURACION_C7        NUMBER,
  CSX_FRECUENCIA_C8      NUMBER,
  CSX_DURACION_C8        NUMBER,
  CSX_FRECUENCIA_C9      NUMBER,
  CSX_DURACION_C9        NUMBER,
  CSX_FRECUENCIA_C10     NUMBER,
  CSX_DURACION_C10       NUMBER,
  CSX_FRECUENCIA_C11     NUMBER,
  CSX_DURACION_C11       NUMBER,
  CSX_FRECUENCIA_C12     NUMBER,
  CSX_DURACION_C12       NUMBER,
  CSX_FRECUENCIA_C13     NUMBER,
  CSX_DURACION_C13       NUMBER,
  CSX_FRECUENCIA_C14     NUMBER,
  CSX_DURACION_C14       NUMBER,
  CSX_FRECUENCIA_C15     NUMBER,
  CSX_DURACION_C15       NUMBER,
  CSX_DIU_AP             NUMBER,
  CSX_DIUM_AP            NUMBER,
  CSX_FIU_AP             NUMBER,
  CSX_FIUM_AP            NUMBER,
  CSX_FRECUENCIA_C1_AP   NUMBER,
  CSX_DURACION_C1_AP     NUMBER,
  CSX_FRECUENCIA_C2_AP   NUMBER,
  CSX_DURACION_C2_AP     NUMBER,
  CSX_FRECUENCIA_C3_AP   NUMBER,
  CSX_DURACION_C3_AP     NUMBER,
  CSX_FRECUENCIA_C4_AP   NUMBER,
  CSX_DURACION_C4_AP     NUMBER,
  CSX_FRECUENCIA_C5_AP   NUMBER,
  CSX_DURACION_C5_AP     NUMBER,
  CSX_FRECUENCIA_C6_AP   NUMBER,
  CSX_DURACION_C6_AP     NUMBER,
  CSX_FRECUENCIA_C7_AP   NUMBER,
  CSX_DURACION_C7_AP     NUMBER,
  CSX_FRECUENCIA_C8_AP   NUMBER,
  CSX_DURACION_C8_AP     NUMBER,
  CSX_FRECUENCIA_C9_AP   NUMBER,
  CSX_DURACION_C9_AP     NUMBER,
  CSX_FRECUENCIA_C10_AP  NUMBER,
  CSX_DURACION_C10_AP    NUMBER,
  CSX_FRECUENCIA_C11_AP  NUMBER,
  CSX_DURACION_C11_AP    NUMBER,
  CSX_FRECUENCIA_C12_AP  NUMBER,
  CSX_DURACION_C12_AP    NUMBER,
  CSX_FRECUENCIA_C13_AP  NUMBER,
  CSX_DURACION_C13_AP    NUMBER,
  CSX_FRECUENCIA_C14_AP  NUMBER,
  CSX_DURACION_C14_AP    NUMBER,
  CSX_FRECUENCIA_C15_AP  NUMBER,
  CSX_DURACION_C15_AP    NUMBER,
  CSX_PERIODO_OP         DATE
);

CREATE TABLE BRAE.QA_TCSX_X
(
  CSX_TRANSFOR           VARCHAR2(15 BYTE),
  CSX_DIU                NUMBER,
  CSX_DIUM               NUMBER,
  CSX_FIU                NUMBER,
  CSX_FIUM               NUMBER,
  CSX_IDMERCADO          NUMBER,
  CSX_FRECUENCIA_C1      NUMBER,
  CSX_DURACION_C1        NUMBER,
  CSX_FRECUENCIA_C2      NUMBER,
  CSX_DURACION_C2        NUMBER,
  CSX_FRECUENCIA_C3      NUMBER,
  CSX_DURACION_C3        NUMBER,
  CSX_FRECUENCIA_C4      NUMBER,
  CSX_DURACION_C4        NUMBER,
  CSX_FRECUENCIA_C5      NUMBER,
  CSX_DURACION_C5        NUMBER,
  CSX_FRECUENCIA_C6      NUMBER,
  CSX_DURACION_C6        NUMBER,
  CSX_FRECUENCIA_C7      NUMBER,
  CSX_DURACION_C7        NUMBER,
  CSX_FRECUENCIA_C8      NUMBER,
  CSX_DURACION_C8        NUMBER,
  CSX_FRECUENCIA_C9      NUMBER,
  CSX_DURACION_C9        NUMBER,
  CSX_FRECUENCIA_C10     NUMBER,
  CSX_DURACION_C10       NUMBER,
  CSX_FRECUENCIA_C11     NUMBER,
  CSX_DURACION_C11       NUMBER,
  CSX_FRECUENCIA_C12     NUMBER,
  CSX_DURACION_C12       NUMBER,
  CSX_FRECUENCIA_C13     NUMBER,
  CSX_DURACION_C13       NUMBER,
  CSX_FRECUENCIA_C14     NUMBER,
  CSX_DURACION_C14       NUMBER,
  CSX_FRECUENCIA_C15     NUMBER,
  CSX_DURACION_C15       NUMBER,
  CSX_DIU_AP             NUMBER,
  CSX_DIUM_AP            NUMBER,
  CSX_FIU_AP             NUMBER,
  CSX_FIUM_AP            NUMBER,
  CSX_FRECUENCIA_C1_AP   NUMBER,
  CSX_DURACION_C1_AP     NUMBER,
  CSX_FRECUENCIA_C2_AP   NUMBER,
  CSX_DURACION_C2_AP     NUMBER,
  CSX_FRECUENCIA_C3_AP   NUMBER,
  CSX_DURACION_C3_AP     NUMBER,
  CSX_FRECUENCIA_C4_AP   NUMBER,
  CSX_DURACION_C4_AP     NUMBER,
  CSX_FRECUENCIA_C5_AP   NUMBER,
  CSX_DURACION_C5_AP     NUMBER,
  CSX_FRECUENCIA_C6_AP   NUMBER,
  CSX_DURACION_C6_AP     NUMBER,
  CSX_FRECUENCIA_C7_AP   NUMBER,
  CSX_DURACION_C7_AP     NUMBER,
  CSX_FRECUENCIA_C8_AP   NUMBER,
  CSX_DURACION_C8_AP     NUMBER,
  CSX_FRECUENCIA_C9_AP   NUMBER,
  CSX_DURACION_C9_AP     NUMBER,
  CSX_FRECUENCIA_C10_AP  NUMBER,
  CSX_DURACION_C10_AP    NUMBER,
  CSX_FRECUENCIA_C11_AP  NUMBER,
  CSX_DURACION_C11_AP    NUMBER,
  CSX_FRECUENCIA_C12_AP  NUMBER,
  CSX_DURACION_C12_AP    NUMBER,
  CSX_FRECUENCIA_C13_AP  NUMBER,
  CSX_DURACION_C13_AP    NUMBER,
  CSX_FRECUENCIA_C14_AP  NUMBER,
  CSX_DURACION_C14_AP    NUMBER,
  CSX_FRECUENCIA_C15_AP  NUMBER,
  CSX_DURACION_C15_AP    NUMBER,
  CSX_PERIODO_OP         DATE
);


CREATE TABLE BRAE.QA_TCSU
(
  CSU_NIU                VARCHAR2(15 BYTE),
  CSU_DIU                NUMBER,
  CSU_DIUM               NUMBER,
  CSU_FIU                NUMBER,
  CSU_FIUM               NUMBER,
  CSU_IDMERCADO          NUMBER,
  CSU_FRECUENCIA_C1      NUMBER,
  CSU_DURACION_C1        NUMBER,
  CSU_FRECUENCIA_C2      NUMBER,
  CSU_DURACION_C2        NUMBER,
  CSU_FRECUENCIA_C3      NUMBER,
  CSU_DURACION_C3        NUMBER,
  CSU_FRECUENCIA_C4      NUMBER,
  CSU_DURACION_C4        NUMBER,
  CSU_FRECUENCIA_C5      NUMBER,
  CSU_DURACION_C5        NUMBER,
  CSU_FRECUENCIA_C6      NUMBER,
  CSU_DURACION_C6        NUMBER,
  CSU_FRECUENCIA_C7      NUMBER,
  CSU_DURACION_C7        NUMBER,
  CSU_FRECUENCIA_C8      NUMBER,
  CSU_DURACION_C8        NUMBER,
  CSU_FRECUENCIA_C9      NUMBER,
  CSU_DURACION_C9        NUMBER,
  CSU_FRECUENCIA_C10     NUMBER,
  CSU_DURACION_C10       NUMBER,
  CSU_FRECUENCIA_C11     NUMBER,
  CSU_DURACION_C11       NUMBER,
  CSU_FRECUENCIA_C12     NUMBER,
  CSU_DURACION_C12       NUMBER,
  CSU_FRECUENCIA_C13     NUMBER,
  CSU_DURACION_C13       NUMBER,
  CSU_FRECUENCIA_C14     NUMBER,
  CSU_DURACION_C14       NUMBER,
  CSU_FRECUENCIA_C15     NUMBER,
  CSU_DURACION_C15       NUMBER,
  CSU_PERIODO_OP         DATE
);



CREATE TABLE BRAE.QA_TDATACSX
(
  FDD_CODIGOEVENTO    VARCHAR2(10 BYTE)         NOT NULL,
  FDD_FINICIAL        DATE,
  FDD_FFINAL          DATE,
  FDD_DURACION        NUMBER,
  FDD_DURACION_AP     NUMBER,
  FDD_CODIGOELEMENTO  VARCHAR2(16 BYTE),
  FDD_CONTINUIDAD     VARCHAR2(2 BYTE),
  FDD_USUARIOAP       VARCHAR2(2 BYTE),
  FDD_EXCLUSION       VARCHAR2(20 BYTE),
  FDD_CAUSA           VARCHAR2(50 BYTE),
  FDD_CAUSA_CREG      VARCHAR2(50 BYTE),
  FDD_CAUSA_SSPD      NUMBER
  );


CREATE TABLE BRAE.QA_TFDDAJUSTES
(
  FDR_PERIODO_OP      DATE,
  FDR_CODIGOEVENTO    VARCHAR2(10 BYTE)         NOT NULL,
  FDR_FINICIAL        DATE,
  FDR_FFINAL          DATE,
  FDR_CODIGOELEMENTO  VARCHAR2(16 BYTE),
  FDR_TIPOELEMENTO    NUMBER,
  FDR_CAUSA           VARCHAR2(16 BYTE),
  FDR_CONTINUIDAD     VARCHAR2(2 BYTE),
  FDR_EXCLUIDOZNI     NUMBER,
  FDR_AFECTACONGEN    NUMBER,
  FDR_USUARIOAP       NUMBER,
  FDR_TIPOAJUSTE      NUMBER,
  FDR_RADICADO        VARCHAR2(30 BYTE)
);

CREATE TABLE BRAE.QA_TFDDCAUSAS
(
  FDC_CAUSA_OMS      VARCHAR2(10 BYTE),
  FDC_CAUSA_015      NUMBER,
  FDC_CAUSA_SSPD     NUMBER,
  FDC_DESCRIPCION    VARCHAR2(150 BYTE),
  FDC_CLASIFICACION  VARCHAR2(20 BYTE),
  FDC_EXCLUSION      VARCHAR2(20 BYTE),
  FDC_DETALLE        VARCHAR2(150 BYTE)
);

CREATE TABLE BRAE.QA_TFDDMODIFICADOS
(
  FDD_CODIGOEVENTO    VARCHAR2(10 BYTE)         NOT NULL,
  FDD_FINICIAL        TIMESTAMP(3),
  FDD_FFINAL          TIMESTAMP(3),
  FDD_CODIGOELEMENTO  VARCHAR2(16 BYTE),
  FDD_TIPOELEMENTO    VARCHAR2(16 BYTE),
  FDD_CAUSA_CREG      VARCHAR2(50 BYTE),
  FDD_ORIGEN          VARCHAR2(3 BYTE)
);


CREATE TABLE BRAE.QA_TFDDPRELIMINAR
(
  FDD_CODIGOEVENTO     VARCHAR2(10 BYTE)        NOT NULL,
  FDD_FINICIAL         TIMESTAMP(3),
  FDD_FFINAL           TIMESTAMP(3),
  FDD_CODIGOELEMENTO   VARCHAR2(16 BYTE),
  FDD_TIPOELEMENTO     VARCHAR2(16 BYTE),
  FDD_CONSUMODIA       NUMBER(15,5),
  FDD_ENS_ELEMENTO     NUMBER(15,5),
  FDD_ENS_EVENTO       NUMBER(15,5),
  FDD_ENEG_EVENTO      NUMBER(15,5),
  FDD_ENEG_ELEMENTO    NUMBER(15,5),
  FDD_CODIGOGENERADOR  VARCHAR2(16 BYTE),
  FDD_CAUSA            VARCHAR2(50 BYTE),
  FDD_CAUSA_CREG       VARCHAR2(50 BYTE),
  FDD_USUARIOAP        VARCHAR2(2 BYTE),
  FDD_CONTINUIDAD      VARCHAR2(2 BYTE),
  FDD_ESTADOREPORTE    VARCHAR2(2 BYTE),
  FDD_PUBLICADO        VARCHAR2(2 BYTE),
  FDD_RECONFIG         VARCHAR2(2 BYTE),
  FDD_PERIODO_OP       DATE,
  FDD_FREG_APERTURA    DATE,
  FDD_FREG_CIERRE      DATE,
  FDD_FPUB_APERTURA    DATE,
  FDD_FPUB_CIERRE      DATE,
  FDD_PERIODO_TC1      NUMBER,
  FDD_EXCLUSION        VARCHAR2(20 BYTE),
  FDD_CAUSA_SSPD       NUMBER                   DEFAULT 0
);

CREATE TABLE BRAE.QA_TFDDPRELIMINAR_NR
(
  FDD_CODIGOEVENTO     VARCHAR2(10 BYTE)        NOT NULL,
  FDD_FINICIAL         TIMESTAMP(3),
  FDD_FFINAL           TIMESTAMP(3),
  FDD_CODIGOELEMENTO   VARCHAR2(16 BYTE),
  FDD_TIPOELEMENTO     VARCHAR2(16 BYTE),
  FDD_CONSUMODIA       NUMBER(15,5),
  FDD_ENS_ELEMENTO     NUMBER(15,5),
  FDD_ENS_EVENTO       NUMBER(15,5),
  FDD_ENEG_EVENTO      NUMBER(15,5),
  FDD_ENEG_ELEMENTO    NUMBER(15,5),
  FDD_CODIGOGENERADOR  VARCHAR2(16 BYTE),
  FDD_CAUSA            VARCHAR2(50 BYTE),
  FDD_CAUSA_CREG       VARCHAR2(50 BYTE),
  FDD_USUARIOAP        VARCHAR2(2 BYTE),
  FDD_CONTINUIDAD      VARCHAR2(2 BYTE),
  FDD_ESTADOREPORTE    VARCHAR2(2 BYTE),
  FDD_PUBLICADO        VARCHAR2(2 BYTE),
  FDD_RECONFIG         VARCHAR2(2 BYTE),
  FDD_PERIODO_OP       DATE,
  FDD_FREG_APERTURA    DATE,
  FDD_FREG_CIERRE      DATE,
  FDD_FPUB_APERTURA    DATE,
  FDD_FPUB_CIERRE      DATE,
  FDD_PERIODO_TC1      NUMBER,
  FDD_TIPOCARGA        VARCHAR2(20 BYTE)        DEFAULT 'NR',
  FDD_EXCLUSION        VARCHAR2(20 BYTE),
  FDD_CAUSA_SSPD       NUMBER,
  FDD_AJUSTADO         VARCHAR2(2 BYTE)         DEFAULT 'N',
  FDD_TIPOAJUSTE       NUMBER                   DEFAULT 0,
  FDD_RADICADO         VARCHAR2(30 BYTE)        DEFAULT 'NA',
  FDD_APROBADO         VARCHAR2(2 BYTE)         DEFAULT 'NA'
);

CREATE TABLE BRAE.QA_TFDDRECICLER
(
  FDD_CODIGOEVENTO     VARCHAR2(10 BYTE)        NOT NULL,
  FDD_FINICIAL         TIMESTAMP(3),
  FDD_FFINAL           TIMESTAMP(3),
  FDD_CODIGOELEMENTO   VARCHAR2(16 BYTE),
  FDD_TIPOELEMENTO     VARCHAR2(16 BYTE),
  FDD_CONSUMODIA       NUMBER(15,5),
  FDD_ENS_ELEMENTO     NUMBER(15,5),
  FDD_ENS_EVENTO       NUMBER(15,5),
  FDD_ENEG_EVENTO      NUMBER(15,5),
  FDD_ENEG_ELEMENTO    NUMBER(15,5),
  FDD_CODIGOGENERADOR  VARCHAR2(16 BYTE),
  FDD_CAUSA            VARCHAR2(50 BYTE),
  FDD_CAUSA_CREG       VARCHAR2(50 BYTE),
  FDD_USUARIOAP        VARCHAR2(2 BYTE),
  FDD_CONTINUIDAD      VARCHAR2(2 BYTE),
  FDD_ESTADOREPORTE    VARCHAR2(2 BYTE),
  FDD_PUBLICADO        VARCHAR2(2 BYTE),
  FDD_RECONFIG         VARCHAR2(2 BYTE),
  FDD_PERIODO_OP       DATE,
  FDD_FREG_APERTURA    DATE,
  FDD_FREG_CIERRE      DATE,
  FDD_FPUB_APERTURA    DATE,
  FDD_FPUB_CIERRE      DATE,
  FDD_PERIODO_TC1      NUMBER,
  FDD_TIPOCARGA        VARCHAR2(20 BYTE),
  FDD_EXCLUSION        VARCHAR2(20 BYTE),
  FDD_CAUSA_SSPD       NUMBER,
  FDD_AJUSTADO         VARCHAR2(2 BYTE),
  FDD_TIPOAJUSTE       NUMBER,
  FDD_RADICADO         VARCHAR2(30 BYTE),
  FDD_APROBADO         VARCHAR2(2 BYTE)
);


CREATE TABLE BRAE.QA_TFDDREGISTRO
(
  FDD_CODIGOEVENTO     VARCHAR2(10 BYTE)        NOT NULL,
  FDD_FINICIAL         TIMESTAMP(3),
  FDD_FFINAL           TIMESTAMP(3),
  FDD_CODIGOELEMENTO   VARCHAR2(16 BYTE),
  FDD_TIPOELEMENTO     VARCHAR2(16 BYTE),
  FDD_CONSUMODIA       NUMBER(15,5),
  FDD_ENS_ELEMENTO     NUMBER(15,5),
  FDD_ENS_EVENTO       NUMBER(15,5),
  FDD_ENEG_EVENTO      NUMBER(15,5),
  FDD_ENEG_ELEMENTO    NUMBER(15,5),
  FDD_CODIGOGENERADOR  VARCHAR2(16 BYTE),
  FDD_CAUSA            VARCHAR2(50 BYTE),
  FDD_CAUSA_CREG       VARCHAR2(50 BYTE),
  FDD_USUARIOAP        VARCHAR2(2 BYTE),
  FDD_CONTINUIDAD      VARCHAR2(2 BYTE),
  FDD_ESTADOREPORTE    VARCHAR2(2 BYTE),
  FDD_PUBLICADO        VARCHAR2(2 BYTE),
  FDD_RECONFIG         VARCHAR2(2 BYTE),
  FDD_PERIODO_OP       DATE,
  FDD_FREG_APERTURA    DATE,
  FDD_FREG_CIERRE      DATE,
  FDD_FPUB_APERTURA    DATE,
  FDD_FPUB_CIERRE      DATE,
  FDD_PERIODO_TC1      NUMBER,
  FDD_TIPOCARGA        VARCHAR2(20 BYTE)        DEFAULT 'CARGA DIARIA',
  FDD_EXCLUSION        VARCHAR2(20 BYTE),
  FDD_CAUSA_SSPD       NUMBER,
  FDD_AJUSTADO         VARCHAR2(2 BYTE)         DEFAULT 'N',
  FDD_TIPOAJUSTE       NUMBER                   DEFAULT 0,
  FDD_RADICADO         VARCHAR2(30 BYTE)        DEFAULT 'NA',
  FDD_APROBADO         VARCHAR2(2 BYTE)         DEFAULT 'NA'
);


CREATE TABLE BRAE.QA_TFDDREGISTRO_NR
(
  FDD_CODIGOEVENTO     VARCHAR2(10 BYTE)        NOT NULL,
  FDD_FINICIAL         TIMESTAMP(3),
  FDD_FFINAL           TIMESTAMP(3),
  FDD_CODIGOELEMENTO   VARCHAR2(16 BYTE),
  FDD_TIPOELEMENTO     VARCHAR2(16 BYTE),
  FDD_CONSUMODIA       NUMBER(15,5),
  FDD_ENS_ELEMENTO     NUMBER(15,5),
  FDD_ENS_EVENTO       NUMBER(15,5),
  FDD_ENEG_EVENTO      NUMBER(15,5),
  FDD_ENEG_ELEMENTO    NUMBER(15,5),
  FDD_CODIGOGENERADOR  VARCHAR2(16 BYTE),
  FDD_CAUSA            VARCHAR2(50 BYTE),
  FDD_CAUSA_CREG       VARCHAR2(50 BYTE),
  FDD_USUARIOAP        VARCHAR2(2 BYTE),
  FDD_CONTINUIDAD      VARCHAR2(2 BYTE),
  FDD_ESTADOREPORTE    VARCHAR2(2 BYTE),
  FDD_PUBLICADO        VARCHAR2(2 BYTE),
  FDD_RECONFIG         VARCHAR2(2 BYTE),
  FDD_PERIODO_OP       DATE,
  FDD_FREG_APERTURA    DATE,
  FDD_FREG_CIERRE      DATE,
  FDD_FPUB_APERTURA    DATE,
  FDD_FPUB_CIERRE      DATE,
  FDD_PERIODO_TC1      NUMBER
);


CREATE TABLE BRAE.QA_TFDDREGISTRO_X
(
  FDD_CODIGOEVENTO     VARCHAR2(10 BYTE)        NOT NULL,
  FDD_FINICIAL         TIMESTAMP(3),
  FDD_FFINAL           TIMESTAMP(3),
  FDD_CODIGOELEMENTO   VARCHAR2(16 BYTE),
  FDD_TIPOELEMENTO     VARCHAR2(16 BYTE),
  FDD_CONSUMODIA       NUMBER(15,5),
  FDD_ENS_ELEMENTO     NUMBER(15,5),
  FDD_ENS_EVENTO       NUMBER(15,5),
  FDD_ENEG_EVENTO      NUMBER(15,5),
  FDD_ENEG_ELEMENTO    NUMBER(15,5),
  FDD_CODIGOGENERADOR  VARCHAR2(16 BYTE),
  FDD_CAUSA            VARCHAR2(50 BYTE),
  FDD_CAUSA_CREG       VARCHAR2(50 BYTE),
  FDD_USUARIOAP        VARCHAR2(2 BYTE),
  FDD_CONTINUIDAD      VARCHAR2(2 BYTE),
  FDD_ESTADOREPORTE    VARCHAR2(2 BYTE),
  FDD_PUBLICADO        VARCHAR2(2 BYTE),
  FDD_RECONFIG         VARCHAR2(2 BYTE),
  FDD_PERIODO_OP       DATE,
  FDD_FREG_APERTURA    DATE,
  FDD_FREG_CIERRE      DATE,
  FDD_FPUB_APERTURA    DATE,
  FDD_FPUB_CIERRE      DATE,
  FDD_PERIODO_TC1      NUMBER,
  FDD_TIPOCARGA        VARCHAR2(20 BYTE),
  FDD_EXCLUSION        VARCHAR2(20 BYTE),
  FDD_CAUSA_SSPD       NUMBER,
  FDD_AJUSTADO         VARCHAR2(2 BYTE),
  FDD_TIPOAJUSTE       NUMBER,
  FDD_RADICADO         VARCHAR2(30 BYTE),
  FDD_APROBADO         VARCHAR2(2 BYTE)
);


CREATE TABLE BRAE.QA_TFDDREPORTE
(
  FDR_PERIODO_OP      DATE,
  FDR_CODIGOEVENTO    VARCHAR2(10 BYTE)         NOT NULL,
  FDR_FINICIAL        DATE,
  FDR_FFINAL          DATE,
  FDR_CODIGOELEMENTO  VARCHAR2(16 BYTE),
  FDR_TIPOELEMENTO    NUMBER,
  FDR_CAUSA           VARCHAR2(16 BYTE),
  FDR_CONTINUIDAD     VARCHAR2(2 BYTE),
  FDR_EXCLUIDOZNI     NUMBER,
  FDR_AFECTACONGEN    NUMBER,
  FDR_USUARIOAP       NUMBER
);

CREATE TABLE BRAE.QA_TFDDREPORTE_NR
(
  FDR_PERIODO_OP      DATE,
  FDR_CODIGOEVENTO    VARCHAR2(10 BYTE)         NOT NULL,
  FDR_FINICIAL        DATE,
  FDR_FFINAL          DATE,
  FDR_CODIGOELEMENTO  VARCHAR2(16 BYTE),
  FDR_TIPOELEMENTO    NUMBER,
  FDR_CAUSA           VARCHAR2(16 BYTE),
  FDR_CONTINUIDAD     VARCHAR2(2 BYTE),
  FDR_EXCLUIDOZNI     NUMBER,
  FDR_AFECTACONGEN    NUMBER,
  FDR_USUARIOAP       NUMBER
);

CREATE TABLE BRAE.QA_TFDDSUPRIMIDOS
(
  FDD_CODIGOEVENTO     VARCHAR2(10 BYTE)        NOT NULL,
  FDD_FINICIAL         TIMESTAMP(3),
  FDD_FFINAL           TIMESTAMP(3),
  FDD_CODIGOELEMENTO   VARCHAR2(16 BYTE),
  FDD_TIPOELEMENTO     VARCHAR2(16 BYTE),
  FDD_CONSUMODIA       NUMBER(15,5),
  FDD_ENS_ELEMENTO     NUMBER(15,5),
  FDD_ENS_EVENTO       NUMBER(15,5),
  FDD_ENEG_EVENTO      NUMBER(15,5),
  FDD_ENEG_ELEMENTO    NUMBER(15,5),
  FDD_CODIGOGENERADOR  VARCHAR2(16 BYTE),
  FDD_CAUSA            VARCHAR2(50 BYTE),
  FDD_CAUSA_CREG       VARCHAR2(50 BYTE),
  FDD_USUARIOAP        VARCHAR2(2 BYTE),
  FDD_CONTINUIDAD      VARCHAR2(2 BYTE),
  FDD_ESTADOREPORTE    VARCHAR2(2 BYTE),
  FDD_PUBLICADO        VARCHAR2(2 BYTE),
  FDD_RECONFIG         VARCHAR2(2 BYTE),
  FDD_PERIODO_OP       DATE,
  FDD_FREG_APERTURA    DATE,
  FDD_FREG_CIERRE      DATE,
  FDD_FPUB_APERTURA    DATE,
  FDD_FPUB_CIERRE      DATE,
  FDD_PERIODO_TC1      NUMBER
);

CREATE TABLE BRAE.QA_TTC1
(
  TC1_TC1          VARCHAR2(20 BYTE),
  TC1_CODCONEX     VARCHAR2(9 BYTE),
  TC1_TIPCONEX     VARCHAR2(2 BYTE),
  TC1_NT           NUMBER(2),
  TC1_NTP          NUMBER(2),
  TC1_PROPACTIV    VARCHAR2(5 BYTE),
  TC1_CONEXRED     VARCHAR2(2 BYTE),
  TC1_IDCOMER      VARCHAR2(7 BYTE),
  TC1_IDMERC       VARCHAR2(5 BYTE),
  TC1_GC           VARCHAR2(3 BYTE),
  TC1_CODFRONCOM   VARCHAR2(8 BYTE),
  TC1_CODCIRC      VARCHAR2(7 BYTE),
  TC1_CODTRANSF    VARCHAR2(7 BYTE),
  TC1_CODDANE      VARCHAR2(10 BYTE),
  TC1_CEDCATAS     VARCHAR2(22 BYTE),
  TC1_UBIC         VARCHAR2(2 BYTE),
  TC1_DIREC        VARCHAR2(40 BYTE),
  TC1_CONESP       VARCHAR2(3 BYTE),
  TC1_CODARESP     VARCHAR2(5 BYTE),
  TC1_TIPARESP     VARCHAR2(2 BYTE),
  TC1_ESTSECT      VARCHAR2(2 BYTE),
  TC1_ALTITUD      NUMBER(15,5),
  TC1_LONGITUD     NUMBER(15,5),
  TC1_LATITUD      INTEGER,
  TC1_AUTOGEN      VARCHAR2(2 BYTE),
  TC1_EXPENER      VARCHAR2(2 BYTE),
  TC1_CAPAUTOGENR  VARCHAR2(6 BYTE),
  TC1_TIPGENR      VARCHAR2(2 BYTE),
  TC1_CODFRONEXP   VARCHAR2(6 BYTE),
  TC1_FENTGEN      DATE,
  TC1_CONTRESP     VARCHAR2(6 BYTE),
  TC1_CAPCONTRESP  VARCHAR2(6 BYTE),
  TC1_PERIODO      NUMBER(6)
);

CREATE TABLE BRAE.QA_TTC2
(
  TC2_TC2         VARCHAR2(10 BYTE),
  TC2_CODCONEX    VARCHAR2(10 BYTE),
  TC2_CONSUMOMES  NUMBER(20,10),
  TC2_PERIODO     NUMBER(7)
);



CREATE TABLE BRAE.QA_TTC1CERT
(
  TC1_NIU          VARCHAR2(50 BYTE),
  TC1_CODCONEX     VARCHAR2(50 BYTE),
  TC1_TIPCONEX     VARCHAR2(30 BYTE),
  TC1_NT           NUMBER,
  TC1_NTP          NUMBER,
  TC1_CARGOINV     VARCHAR2(30 BYTE),
  TC1_CONEXRED     VARCHAR2(30 BYTE),
  TC1_IDCOMER      NUMBER,
  TC1_IDMERC       NUMBER,
  TC1_GC097        NUMBER,
  TC1_CODFRONT     VARCHAR2(50 BYTE),
  TC1_PERIDO       NUMBER,
  TC1_GC015        NUMBER
);


CREATE TABLE BRAE.QA_TMETAS_CALMEDIA
(
  PERIODO_META   NUMBER,
  SAIDI_Rj       NUMBER,
  SAIFI_Rj       NUMBER,
  SAIDI_Mjt      NUMBER,
  SAIFI_Mjt      NUMBER,
  SAIDI_Mjt_LS   NUMBER,
  SAIFI_Mjt_LS   NUMBER,
  SAIDI_Mjt_LI   NUMBER,
  SAIFI_Mjt_LI   NUMBER,
  SAIDI_LP	     NUMBER,
  SAIFI_LP       NUMBER
);

CREATE TABLE BRAE.QA_TMETAS_CALINDIVIDUAL
(
  PERIODO        NUMBER,
  GRUPO015       NUMBER,
  NT             NUMBER,
  DIUGj          NUMBER,
  FIUGj          NUMBER,
  Por_t          NUMBER
);

DROP TABLE QA_TCS1;
CREATE TABLE BRAE.QA_TCS1
(
  CS1_PERIODO_OP     DATE,
  CS1_IDMERCADO      NUMBER,
  CS1_UIXTI_M        NUMBER,
  CS1_UI_M           NUMBER,
  CS1_UT_M           NUMBER,
  CS1_SAIDI_M        NUMBER,
  CS1_SAIFI_M        NUMBER,
  CS1_SAIDI          NUMBER,
  CS1_SAIFI          NUMBER,
  CS1_SAIDI_MAT      NUMBER,
  CS1_SAIFI_MAT      NUMBER,
  CS1_MAIFI_M        NUMBER,
  CS1_MAIFI          NUMBER,
  CS1_MAIFI_MAT      NUMBER,
  CS1_CAIDI_M        NUMBER,
  CS1_CAIDI          NUMBER
);


CREATE TABLE QA_TFDDPRELIMINAR_AJ
(FDD_CODIGOEVENTO       NOT NULL VARCHAR2(10)
 FDD_FINICIAL                    TIMESTAMP(3)
 FDD_FFINAL                      TIMESTAMP(3)
 FDD_CODIGOELEMENTO              VARCHAR2(16)
 FDD_TIPOELEMENTO                VARCHAR2(16)
 FDD_CONSUMODIA                  NUMBER(15,5)
 FDD_ENS_ELEMENTO                NUMBER(15,5)
 FDD_ENS_EVENTO                  NUMBER(15,5)
 FDD_ENEG_EVENTO                 NUMBER(15,5)
 FDD_ENEG_ELEMENTO               NUMBER(15,5)
 FDD_CODIGOGENERADOR             VARCHAR2(16)
 FDD_CAUSA                       VARCHAR2(50)
 FDD_CAUSA_CREG                  VARCHAR2(50)
 FDD_USUARIOAP                   VARCHAR2(2)
 FDD_CONTINUIDAD                 VARCHAR2(2)
 FDD_ESTADOREPORTE               VARCHAR2(2)
 FDD_PUBLICADO                   VARCHAR2(2)
 FDD_RECONFIG                    VARCHAR2(2)
 FDD_PERIODO_OP                  DATE
 FDD_FREG_APERTURA               DATE
 FDD_FREG_CIERRE                 DATE
 FDD_FPUB_APERTURA               DATE
 FDD_FPUB_CIERRE                 DATE
 FDD_PERIODO_TC1                 NUMBER
 FDD_TIPOCARGA                   VARCHAR2(20)
 FDD_EXCLUSION                   VARCHAR2(20)
 FDD_CAUSA_SSPD                  NUMBER
 FDD_AJUSTADO                    VARCHAR2(2)
 FDD_TIPOAJUSTE                  NUMBER
 FDD_RADICADO                    VARCHAR2(30)
 FDD_APROBADO                    VARCHAR2(2)
 FDD_IUA                         VARCHAR2(20)  );