create table QA_TTT3_REGISTRO
(
    TT3_PERIODO_OP     DATE,
    TT3_ID             NUMBER,
    TT3_DESCRIPCION    VARCHAR2(40),
    TT3_FINICIAL       DATE,
    TT3_FFINAL         DATE,
    TT3_SUBESTACION    VARCHAR2(30),
    TT3_IUS            VARCHAR2(4),
    TT3_ALCANCE        VARCHAR2(400),
    TT3_CODIGOPROYECTO VARCHAR2(50),
    TT3_CERTIFICADO    NUMBER default 0,
    TT3_EJECUTADO      NUMBER,
    TT3_FCERTIFICACION DATE,
    TT3_FCREACION      DATE   default SYSDATE,
    TT3_TIPOPROYECTO   VARCHAR2(20)
)
/


