-- AJUSTE DE 3524 REGISTROS MODIFICADOS
UPDATE QA_TFDDREGISTRO R
SET  --R.FDD_FINICIAL = (SELECT FDD_FINICIAL FROM QA_TFDDMODIFICADOS WHERE FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO=R.FDD_CODIGOEVENTO||R.FDD_CODIGOELEMENTO AND FDD_ORIGEN='OMS'),
     --R.FDD_FFINAL = (SELECT FDD_FFINAL FROM QA_TFDDMODIFICADOS WHERE FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO=R.FDD_CODIGOEVENTO||R.FDD_CODIGOELEMENTO AND FDD_ORIGEN='OMS'),
     R.FDD_CAUSA = (SELECT DISTINCT(M.CAUSA) 
                    FROM OMS.INTERUPC I 
                    LEFT OUTER JOIN OMS.MANIOBRAS M ON M.CODE=I.MINICIAL 
                    WHERE I.MINICIAL=R.FDD_CODIGOEVENTO),
     R.FDD_AJUSTADO='S',
     R.FDD_TIPOAJUSTE=(CASE WHEN ((SELECT DISTINCT(TO_NUMBER(FDD_CAUSA_CREG)) 
                                   FROM QA_TFDDMODIFICADOS 
                                   WHERE FDD_CODIGOEVENTO=R.FDD_CODIGOEVENTO 
                                   AND FDD_ORIGEN='OMS')=0) 
                            THEN 3 
                            ELSE 2 
                      END),
     R.FDD_RADICADO='2020052810713814',
     R.FDD_APROBADO='N',
     R.FDD_CAUSA_CREG=(SELECT  DISTINCT(FDD_CAUSA_CREG) 
                       FROM QA_TFDDMODIFICADOS 
                       WHERE FDD_CODIGOEVENTO=R.FDD_CODIGOEVENTO 
                       AND FDD_ORIGEN='OMS'), 
     R.FDD_EXCLUSION=(SELECT DISTINCT(C.FDC_EXCLUSION) 
                     FROM OMS.INTERUPC I
                     LEFT OUTER JOIN OMS.MANIOBRAS M ON M.CODE=I.MINICIAL
                     LEFT OUTER JOIN QA_TFDDCAUSAS C ON C.FDC_CAUSA_OMS=M.CAUSA
                     WHERE I.MINICIAL=R.FDD_CODIGOEVENTO)                
  WHERE R.FDD_CODIGOEVENTO||R.FDD_CODIGOELEMENTO IN (SELECT DISTINCT FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO FROM QA_TFDDMODIFICADOS)
  AND R.FDD_CODIGOEVENTO||R.FDD_CODIGOELEMENTO NOT IN (SELECT FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO FROM QA_TFDDREGISTRO WHERE FDD_TIPOAJUSTE=3 AND FDD_AJUSTADO='N')--PARA NO TRAER EN ESTA CARGA LOS ELIMINADOS POR TC1
  AND R.FDD_CODIGOEVENTO||R.FDD_CODIGOELEMENTO NOT IN (SELECT FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO FROM QA_TFDDREGISTRO WHERE FDD_TIPOCARGA='AJUSTE TC1' AND FDD_AJUSTADO='N')--PARA NO TRAER EN ESTA CARGA LOS AGREAGADOS POR TC1;
;
  


 --COMPLETAR EL CAMPO FDD_CAUSA_SSPD PARA TODOS LOS REGISTROS AFECTADOS SEGUN LA CONDICION WHERE (3524 REGISTROS)
 
  UPDATE BRAE.QA_TFDDREGISTRO T
   SET T.FDD_CAUSA_SSPD =
          (CASE
              WHEN (  (  TO_DATE (
                            TO_CHAR (T.FDD_FFINAL, 'DD/MM/YYYY hh24:mi:ss'),
                            'DD/MM/YYYY hh24:mi:ss')
                       - TO_DATE (
                            TO_CHAR (T.FDD_FINICIAL, 'DD/MM/YYYY hh24:mi:ss'),
                            'DD/MM/YYYY hh24:mi:ss'))
                    * 24) <= 0.05
              THEN
                 1
              ELSE
                 NVL ((SELECT FDC_CAUSA_SSPD  FROM QA_TFDDCAUSAS WHERE FDC_CAUSA_OMS=T.FDD_CAUSA), 0)
           END)
  WHERE T.FDD_CODIGOEVENTO||T.FDD_CODIGOELEMENTO IN (SELECT DISTINCT FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO FROM QA_TFDDMODIFICADOS)
  AND T.FDD_CODIGOEVENTO||T.FDD_CODIGOELEMENTO NOT IN (SELECT FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO FROM QA_TFDDREGISTRO WHERE FDD_TIPOAJUSTE=3 AND FDD_AJUSTADO='N')--PARA NO TRAER EN ESTA CARGA LOS ELIMINADOS POR TC1
  AND T.FDD_CODIGOEVENTO||T.FDD_CODIGOELEMENTO NOT IN (SELECT FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO FROM QA_TFDDREGISTRO WHERE FDD_TIPOCARGA='AJUSTE TC1' AND FDD_AJUSTADO='N')--PARA NO TRAER EN ESTA CARGA LOS AGREAGADOS POR TC1;
;



-- AJUSTE DE 7 REGISTROS PARA ELIMINAR POR ACTUALIZACION DE TC1 COINCIDENTES CON MODIFICADOS
UPDATE QA_TFDDREGISTRO R
SET  R.FDD_AJUSTADO='S',
     R.FDD_RADICADO='2020052810713814',
     R.FDD_APROBADO='N'
  WHERE R.FDD_CODIGOEVENTO||R.FDD_CODIGOELEMENTO IN (SELECT DISTINCT FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO FROM QA_TFDDMODIFICADOS)
  AND R.FDD_CODIGOEVENTO||R.FDD_CODIGOELEMENTO IN (SELECT FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO FROM QA_TFDDREGISTRO WHERE FDD_TIPOAJUSTE=3 AND FDD_AJUSTADO='N')--PARA NO TRAER EN ESTA CARGA LOS ELIMINADOS POR TC1
;
  

--ACTUALIZACION DEL REGISTRO(1) DE MODIFICACION A CAUSA PRUEBA, A SU CAUSA ORIGINAL ANTERIOR
   UPDATE QA_TFDDREGISTRO 
   SET FDD_CAUSA='7FT01.',
       FDD_CAUSA_CREG='40'
    WHERE FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO IN (SELECT DISTINCT FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO FROM QA_TFDDMODIFICADOS)
   AND  FDD_TIPOAJUSTE=3 AND FDD_AJUSTADO='S'
   AND  FDD_CAUSA='PRUEBA'
   AND  FDD_RADICADO='2020052810713814';      
  

--AJUSTE PARA LOS ADD TC1 (233)
    UPDATE BRAE.QA_TFDDREGISTRO 
    SET FDD_AJUSTADO='S',
        FDD_RADICADO='2020052810713814',  
        FDD_APROBADO='N'
    WHERE FDD_TIPOCARGA = 'AJUSTE TC1' AND FDD_AJUSTADO = 'N'; 
    
    

--AJUSTE PARA LOS DEL TC1(66)
    UPDATE BRAE.QA_TFDDREGISTRO 
    SET FDD_AJUSTADO='S',
        FDD_RADICADO='2020052810713814',  
        FDD_APROBADO='N'
    WHERE FDD_TIPOCARGA = 'CARGA DIARIA' AND FDD_AJUSTADO = 'N' AND FDD_TIPOAJUSTE=3;
--COMMIT;


---AJUSTES DE 91 REGISTROS NR
    UPDATE BRAE.QA_TFDDREGISTRO 
    SET FDD_AJUSTADO='S',
        FDD_TIPOAJUSTE='2',
        FDD_RADICADO='2020052810713814',  
        FDD_APROBADO='N'
    WHERE FDD_TIPOCARGA = 'NR' AND FDD_AJUSTADO = 'N'; 


-- PASAR LOS (74) REGISTROS TIPOAJUSTE=3 A LA TABLA QA_TFDDELIMINADOS

    INSERT INTO QA_TFDDELIMINADOS
    SELECT * FROM QA_TFDDREGISTRO
    WHERE FDD_TIPOAJUSTE=3
    AND FDD_TIPOCARGA='CARGA DIARIA'
    AND FDD_RADICADO='2020052810713814';
    
    
--ELIMINACION DE LOS EVENTOS CON TIPO DE AJUSTE = 3 

DELETE FROM QA_TFDDREGISTRO 
WHERE FDD_TIPOAJUSTE=3
AND FDD_TIPOCARGA='CARGA DIARIA'
AND FDD_RADICADO='2020052810713814';


--FIN 


UPDATE QA_TFDDREGISTRO
SET FDD_FPUB_APERTURA=TO_DATE('03/06/2020 23:59:00','DD/MM/YYYY HH24:MI:SS'),
    FDD_FPUB_CIERRE=TO_DATE('03/06/2020 23:59:00','DD/MM/YYYY HH24:MI:SS')
WHERE FDD_RADICADO='2020052810713814'
AND FDD_TIPOCARGA='AJUSTE TC1';

SELECT * FROM QA_TFDDREGISTRO
WHERE FDD_RADICADO='2020052810713814'
AND FDD_TIPOCARGA='AJUSTE TC1';