
--IDENTIFICAR LAS TABLAS DEL ESQUEMA
SELECT OWNER, TABLE_NAME
FROM ALL_TABLES
WHERE UPPER(OWNER) LIKE UPPER('%BRAE%')
AND TABLE_NAME LIKE 'QA%'
ORDER BY OWNER, TABLE_NAME ASC;

--IDENTIFICAR LOS PROCEDIMIENTOS DEL ESQUEMA
SELECT * FROM ALL_PROCEDURES
WHERE OWNER = 'BRAE'
AND OBJECT_NAME LIKE 'QA%'; 
