---TRASLAPE -----------------------------------------------------------------------

SELECT TT2_CODIGOELEMENTO,TT2_ACTIVOCONEXION
FROM BRAE.QA_TTT2_REGISTRO
WHERE TT2_CODIGOELEMENTO='1T12525'
;



SELECT I.MINICIAL,I.MFINAL,I.TRAFO, I.FINICIAL, I.FFINAL
FROM OMS.INTERUPC I
LEFT OUTER JOIN OMS.MANIOBRAS M ON M.CODE=I.MINICIAL
WHERE I.FINICIAL >=  ADD_MONTHS(TO_DATE(:FECHAOPERACION,'DD/MM/YYYY'),-4)
AND   M.CAUSA<>'PRUEBA';



SELECT * FROM QA_TFDDBACKUP_TRASLAPE;

DELETE FROM QA_TFDDBACKUP_TRASLAPE;
COMMIT;

INSERT INTO QA_TFDDBACKUP_TRASLAPE
SELECT I.MINICIAL,I.MFINAL,I.TRAFO, I.FINICIAL, I.FFINAL, M.CAUSA
FROM OMS.INTERUPC I
LEFT OUTER JOIN OMS.MANIOBRAS M ON M.CODE=I.MINICIAL
WHERE I.FINICIAL >=  ADD_MONTHS(TO_DATE(:FECHAOPERACION,'DD/MM/YYYY'),-3)
AND   M.CAUSA<>'PRUEBA'
AND   I.TYPEEQUIP =  'Transformer';

ROLLBACK;
COMMIT;



        SELECT * 
        --BULK COLLECT INTO VAR_B
         FROM(
             SELECT I.MINICIAL,I.MFINAL,I.TRAFO, I.FINICIAL, I.FFINAL
             FROM OMS.INTERUPC I
             LEFT OUTER JOIN OMS.MANIOBRAS M ON M.CODE=I.MINICIAL
             WHERE I.FINICIAL >=  ADD_MONTHS(TO_dATE(:FECHAOPERACION,'DD/MM/YYYY'),-1)
             AND   M.CAUSA<>'PRUEBA'
             MINUS
             SELECT * FROM QA_TFDDBUCKUP_TRASLAPE       
             ORDER BY 1,3);
             
             SELECT * FROM QA_TFDDBUCKUP_TRASLAPE
             WHERE TO_CHAR(TRA_FINICIAL,'DD/MM/YYYY') = '14/12/2021';
             
             DELETE FROM QA_TFDDBUCKUP_TRASLAPE
             WHERE TO_CHAR(TRA_FINICIAL,'DD/MM/YYYY') = '14/12/2021';
             COMMIT;
             
EXEC QA_PFDDTRASLAPE(TO_DATE('14/12/2021','DD/MM/YYYY'));

SELECT * FROM QA_TFDDTRASLAPE;

SELECT DISTINCT TRA_CODIGOEVENTO_A
     , MA.BREAKER
     , TRA_FINICIAL_A
     --, TRA_FFINAL_A
     , TRA_CODIGOEVENTO_B
     , MB.BREAKER
     , TRA_FINICIAL_B
     --, TRA_FFINAL_B
     , (CASE WHEN RA.FDD_CODIGOEVENTO IS NULL 
             THEN 'EVENTO '||TRA_CODIGOEVENTO_A||' NO REPORTADO AL LAC' 
             ELSE 'EVENTO '||TRA_CODIGOEVENTO_A||' REPORTADO AL LAC'  
        END)||' - '||
       (CASE WHEN RB.FDD_CODIGOEVENTO IS NULL 
             THEN 'EVENTO '||TRA_CODIGOEVENTO_B||' NO REPORTADO AL LAC' 
             ELSE 'EVENTO '||TRA_CODIGOEVENTO_B||' REPORTADO AL LAC'  
        END) AS COMENTARIO
FROM QA_TFDDTRASLAPE T
LEFT JOIN OMS.MANIOBRAS        MA ON T.TRA_CODIGOEVENTO_A = MA.CODE
LEFT JOIN OMS.MANIOBRAS        MB ON T.TRA_CODIGOEVENTO_B = MB.CODE
LEFT JOIN BRAE.QA_TFDDREGISTRO RA ON T.TRA_CODIGOEVENTO_A = RA.FDD_CODIGOEVENTO
LEFT JOIN BRAE.QA_TFDDREGISTRO RB ON T.TRA_CODIGOEVENTO_B = RB.FDD_CODIGOEVENTO
;

SELECT * FROM OMS.INTERUPC;

SELECT TT2_PERIODO_OP
     , COUNT(TT2_PERIODO_OP) 
FROM QA_TTT2_REPORTE
GROUP BY TT2_PERIODO_OP
ORDER BY 1;



----20-12-2021

EXEC QA_PFDDTRASLAPE(TO_DATE('20/12/2021','DD/MM/YYYY'));

SELECT * FROM QA_TFDDTRASLAPE;

SELECT * FROM OMS.INTERUPC I
LEFT JOIN OMS.MANIOBRAS M ON M.CODE=I.MINICIAL
WHERE MINICIAL = '879809';


SELECT * FROM QA_TFDDBACKUP_TRASLAPE
WHERE TRA_CODIGOEVENTO_I='879724';
--879724



        SELECT DISTINCT MINICIAL 
        --BULK COLLECT INTO VAR_C
        FROM(
             SELECT  I.MINICIAL
                   , I.MFINAL
                   , I.TRAFO
                   , I.FINICIAL
                   , I.FFINAL
                   , M.CAUSA
             FROM OMS.INTERUPC I
             LEFT OUTER JOIN OMS.MANIOBRAS M ON M.CODE=I.MINICIAL
             WHERE I.FINICIAL >=  ADD_MONTHS(TO_dATE(:FECHAOPERACION,'DD/MM/YYYY'),-1)
             --AND   M.CAUSA<>'PRUEBA'
             MINUS
             SELECT * FROM QA_TFDDBACKUP_TRASLAPE
            );
            
            
            ALTER TABLE QA_TFDDBUCKUP_TRASLAPE
            RENAME TO QA_TFDDBACKUP_TRASLAPE;
            
            ALTER TABLE QA_TFDDBACKUP_TRASLAPE
            MODIFY TRA_CAUSA_OR VARCHAR2(50);
            
            SELECT * FROM QA_TFDDBACKUP_TRASLAPE;
    
----20-12-2021

EXEC QA_PFDDTRASLAPE(TO_DATE('20/12/2021','DD/MM/YYYY'));

SELECT * FROM QA_TFDDTRASLAPE;

SELECT * FROM QA_TFDDBACKUP_TRASLAPE
WHERE TRA_CODIGOEVENTO_I='880698';


DESC QA_TFDDREGISTRO;

SELECT  I.MINICIAL
   , I.MFINAL
   , I.TRAFO
   , I.FINICIAL
   , I.FFINAL
   , M.CAUSA
FROM OMS.INTERUPC I
LEFT OUTER JOIN OMS.MANIOBRAS M ON M.CODE=I.MINICIAL
WHERE I.FINICIAL >=  ADD_MONTHS(TO_dATE(:FECHAOPERACION,'DD/MM/YYYY'),-1)
AND I.TRAFO IS NULL;


SELECT * FROM OMS.INTERUPC;

             SELECT I.MINICIAL,I.MFINAL,I.TRAFO, I.FINICIAL, I.FFINAL , M.CAUSA
             FROM OMS.INTERUPC I
             LEFT OUTER JOIN OMS.MANIOBRAS M ON M.CODE=I.MINICIAL
             WHERE I.FINICIAL >=  ADD_MONTHS(TO_dATE(:FECHAOPERACION,'DD/MM/YYYY'),-1)
             AND   M.CAUSA<>'PRUEBA'
             AND   I.TYPEEQUIP = 'Transformer';



SELECT I.MINICIAL,I.MFINAL,I.TRAFO, I.FINICIAL, I.FFINAL, M.CAUSA
FROM OMS.INTERUPC I
LEFT OUTER JOIN OMS.MANIOBRAS M ON M.CODE=I.MINICIAL
WHERE I.FINICIAL >=  ADD_MONTHS(TO_DATE(:FECHAOPERACION,'DD/MM/YYYY'),-3)
AND   M.CAUSA<>'PRUEBA'
AND   I.TYPEEQUIP =  'Transformer';




----20-12-2021

EXEC QA_PFDDTRASLAPE(TO_DATE('20/12/2021','DD/MM/YYYY'));

SELECT * FROM QA_TFDDTRASLAPE;
SELECT * FROM QA_TFDDBACKUP_TRASLAPE
WHERE TRA_CODIGOEVENTO_I='880698';

desc QA_TFDDREGISTRO;






