SELECT * FROM QA_TTC1 WHERE TC1_PERIODO=202205;
--EJECUTAR LOS PROCEDIMIENTOS 

--EXEC QA_PCSX(TO_DATE('01/07/2022','DD/MM/YYYY'));
--EXEC QA_PCS1(TO_DATE('01/07/2022','DD/MM/YYYY'));

 --GENERAR CS1
 SELECT ROUND(CS1_SAIDI,2) AS SAIDI_ACUMULADO
     , ROUND(CS1_SAIFI,2) AS SAIFI_ACUMULADO
     , ROUND(CS1_MAIFI,2) AS MAIFI
     , ROUND(CS1_CAIDI,2) AS CAIDI     
     , CS1_IDMERCADO      AS MERCADO
 FROM QA_TCS1 WHERE CS1_PERIODO_OP=:PERIODO; 
 
 ---CS2 A PARTIR DE CSX Y TC1 HORIZONTAL  PARA EL REPORTE AL SAC seugun formato  JOSE DIEGO (NIU,DIUM,FIUM,EXCM)
  SELECT DISTINCT(CSU_NIU) AS NIU,
      ROUND(CSU_DIUM,3) AS DIUM,
      ROUND(CSU_FIUM,3) AS FIUM,
       ROUND((CSU_DURACION_C1  +
              CSU_DURACION_C2  +
              CSU_DURACION_C3  +
              CSU_DURACION_C4  +
              CSU_DURACION_C5  +
              CSU_DURACION_C6  +
              CSU_DURACION_C7  +
              CSU_DURACION_C8  +
              CSU_DURACION_C9  +
              CSU_DURACION_C10 +
              CSU_DURACION_C11 +
              CSU_DURACION_C12 +
              CSU_DURACION_C13 +
              CSU_DURACION_C14 +
              CSU_DURACION_C15)*60,3) AS EXCM_Min
  FROM QA_TCSU
  WHERE CSU_PERIODO_OP = TO_DATE(:PERIODO,'DD/MM/YYYY')
  ORDER BY CSU_NIU ASC;


 ---CS2 A PARTIR DE CSX Y TC1  IMPRESO DE FORMA VERTICAL SEGUNG (SSPD) VERTICAL Y CON LAS EXCLUSIONES EN HORAS
        --CAUSAL (1)
         SELECT  /*TO_CHAR(CSU_PERIODO_OP,'DD/MM/YYYY') AS CS2_PERIODO_OP,*/CSU_NIU  AS NIU,ROUND(CSU_DIU,3)  AS DIU,ROUND(CSU_DIUM,3) AS DIUM,CSU_FIU  AS FIU,CSU_FIUM AS FIUM,'161' AS ID_Mercado
                ,'1' AS Codigo_Causal
                ,CSU_FRECUENCIA_C1 AS Numero_Inter_Causal
                ,ROUND(CSU_DURACION_C1,3) AS Duracion_Inter_Causal FROM QA_TCSU
         WHERE CSU_DURACION_C1 > 0 AND CSU_PERIODO_OP = TO_DATE(:PERIODO,'DD/MM/YYYY')
       UNION ALL
        --CAUSAL (2)
         SELECT  /*TO_CHAR(CSU_PERIODO_OP,'DD/MM/YYYY') AS CS2_PERIODO_OP,*/CSU_NIU  AS NIU,ROUND(CSU_DIU,3)  AS DIU,ROUND(CSU_DIUM,3) AS DIUM,CSU_FIU  AS FIU,CSU_FIUM AS FIUM,'161' AS ID_Mercado
                ,'2' AS Codigo_Causal
                ,CSU_FRECUENCIA_C2 AS Numero_Inter_Causal
                ,ROUND(CSU_DURACION_C2,3) AS Duracion_Inter_Causal FROM QA_TCSU
         WHERE CSU_DURACION_C2 > 0 AND CSU_PERIODO_OP = TO_DATE(:PERIODO,'DD/MM/YYYY')
       UNION ALL
        --CAUSAL (3)
         SELECT  /*TO_CHAR(CSU_PERIODO_OP,'DD/MM/YYYY') AS CS2_PERIODO_OP,*/CSU_NIU  AS NIU,ROUND(CSU_DIU,3)  AS DIU,ROUND(CSU_DIUM,3) AS DIUM,CSU_FIU  AS FIU,CSU_FIUM AS FIUM,'161' AS ID_Mercado
                ,'3' AS Codigo_Causal
                ,CSU_FRECUENCIA_C3 AS Numero_Inter_Causal
                ,ROUND(CSU_DURACION_C3,3) AS Duracion_Inter_Causal FROM QA_TCSU
         WHERE CSU_DURACION_C3 > 0 AND CSU_PERIODO_OP = TO_DATE(:PERIODO,'DD/MM/YYYY')
       UNION ALL
        --CAUSAL (4)
         SELECT  /*TO_CHAR(CSU_PERIODO_OP,'DD/MM/YYYY') AS CS2_PERIODO_OP,*/CSU_NIU  AS NIU,ROUND(CSU_DIU,3)  AS DIU,ROUND(CSU_DIUM,3) AS DIUM,CSU_FIU  AS FIU,CSU_FIUM AS FIUM,'161' AS ID_Mercado
                ,'4' AS Codigo_Causal
                ,CSU_FRECUENCIA_C4 AS Numero_Inter_Causal
                ,ROUND(CSU_DURACION_C4,3) AS Duracion_Inter_Causal FROM QA_TCSU
         WHERE CSU_DURACION_C4 > 0 AND CSU_PERIODO_OP = TO_DATE(:PERIODO,'DD/MM/YYYY')
       UNION ALL
        --CAUSAL (5)
         SELECT  /*TO_CHAR(CSU_PERIODO_OP,'DD/MM/YYYY') AS CS2_PERIODO_OP,*/CSU_NIU  AS NIU,ROUND(CSU_DIU,3)  AS DIU,ROUND(CSU_DIUM,3) AS DIUM,CSU_FIU  AS FIU,CSU_FIUM AS FIUM,'161' AS ID_Mercado
                ,'5' AS Codigo_Causal
                ,CSU_FRECUENCIA_C5 AS Numero_Inter_Causal
                ,ROUND(CSU_DURACION_C5,3) AS Duracion_Inter_Causal FROM QA_TCSU
         WHERE CSU_DURACION_C5 > 0 AND CSU_PERIODO_OP = TO_DATE(:PERIODO,'DD/MM/YYYY')
       UNION ALL
        --CAUSAL (6)
         SELECT  /*TO_CHAR(CSU_PERIODO_OP,'DD/MM/YYYY') AS CS2_PERIODO_OP,*/CSU_NIU  AS NIU,ROUND(CSU_DIU,3)  AS DIU,ROUND(CSU_DIUM,3) AS DIUM,CSU_FIU  AS FIU,CSU_FIUM AS FIUM,'161' AS ID_Mercado
                ,'6' AS Codigo_Causal
                ,CSU_FRECUENCIA_C6 AS Numero_Inter_Causal
                ,ROUND(CSU_DURACION_C6,3) AS Duracion_Inter_Causal FROM QA_TCSU
         WHERE CSU_DURACION_C6 > 0 AND CSU_PERIODO_OP = TO_DATE(:PERIODO,'DD/MM/YYYY')
       UNION ALL
        --CAUSAL (7)
         SELECT  /*TO_CHAR(CSU_PERIODO_OP,'DD/MM/YYYY') AS CS2_PERIODO_OP,*/CSU_NIU  AS NIU,ROUND(CSU_DIU,3)  AS DIU,ROUND(CSU_DIUM,3) AS DIUM,CSU_FIU  AS FIU,CSU_FIUM AS FIUM,'161' AS ID_Mercado
                ,'7' AS Codigo_Causal
                ,CSU_FRECUENCIA_C7 AS Numero_Inter_Causal
                ,ROUND(CSU_DURACION_C7,3) AS Duracion_Inter_Causal FROM QA_TCSU
         WHERE CSU_DURACION_C7 > 0 AND CSU_PERIODO_OP = TO_DATE(:PERIODO,'DD/MM/YYYY')
       UNION ALL
        --CAUSAL (8)
         SELECT  /*TO_CHAR(CSU_PERIODO_OP,'DD/MM/YYYY') AS CS2_PERIODO_OP,*/CSU_NIU  AS NIU,ROUND(CSU_DIU,3)  AS DIU,ROUND(CSU_DIUM,3) AS DIUM,CSU_FIU  AS FIU,CSU_FIUM AS FIUM,'161' AS ID_Mercado
                ,'8' AS Codigo_Causal
                ,CSU_FRECUENCIA_C8 AS Numero_Inter_Causal
                ,ROUND(CSU_DURACION_C8,3) AS Duracion_Inter_Causal FROM QA_TCSU
         WHERE CSU_DURACION_C8 > 0 AND CSU_PERIODO_OP = TO_DATE(:PERIODO,'DD/MM/YYYY')
       UNION ALL
        --CAUSAL (9)
         SELECT  /*TO_CHAR(CSU_PERIODO_OP,'DD/MM/YYYY') AS CS2_PERIODO_OP,*/CSU_NIU  AS NIU,ROUND(CSU_DIU,3)  AS DIU,ROUND(CSU_DIUM,3) AS DIUM,CSU_FIU  AS FIU,CSU_FIUM AS FIUM,'161' AS ID_Mercado
                ,'9' AS Codigo_Causal
                ,CSU_FRECUENCIA_C9 AS Numero_Inter_Causal
                ,ROUND(CSU_DURACION_C9,3) AS Duracion_Inter_Causal FROM QA_TCSU
         WHERE CSU_DURACION_C9 > 0 AND CSU_PERIODO_OP = TO_DATE(:PERIODO,'DD/MM/YYYY')
       UNION ALL
        --CAUSAL (10)
         SELECT  /*TO_CHAR(CSU_PERIODO_OP,'DD/MM/YYYY') AS CS2_PERIODO_OP,*/CSU_NIU  AS NIU,ROUND(CSU_DIU,3)  AS DIU,ROUND(CSU_DIUM,3) AS DIUM,CSU_FIU  AS FIU,CSU_FIUM AS FIUM,'161' AS ID_Mercado
                ,'10' AS Codigo_Causal
                ,CSU_FRECUENCIA_C10 AS Numero_Inter_Causal
                ,ROUND(CSU_DURACION_C10,3) AS Duracion_Inter_Causal FROM QA_TCSU
         WHERE CSU_DURACION_C10 > 0 AND CSU_PERIODO_OP = TO_DATE(:PERIODO,'DD/MM/YYYY')
       UNION ALL
        --CAUSAL (11)
         SELECT  /*TO_CHAR(CSU_PERIODO_OP,'DD/MM/YYYY') AS CS2_PERIODO_OP,*/CSU_NIU  AS NIU,ROUND(CSU_DIU,3)  AS DIU,ROUND(CSU_DIUM,3) AS DIUM,CSU_FIU  AS FIU,CSU_FIUM AS FIUM,'161' AS ID_Mercado
                ,'11' AS Codigo_Causal
                ,CSU_FRECUENCIA_C11 AS Numero_Inter_Causal
                ,ROUND(CSU_DURACION_C11,3) AS Duracion_Inter_Causal FROM QA_TCSU
         WHERE CSU_DURACION_C11 > 0 AND CSU_PERIODO_OP = TO_DATE(:PERIODO,'DD/MM/YYYY')
       UNION ALL
        --CAUSAL (12)
         SELECT  /*TO_CHAR(CSU_PERIODO_OP,'DD/MM/YYYY') AS CS2_PERIODO_OP,*/CSU_NIU  AS NIU,ROUND(CSU_DIU,3)  AS DIU,ROUND(CSU_DIUM,3) AS DIUM,CSU_FIU  AS FIU,CSU_FIUM AS FIUM,'161' AS ID_Mercado
                ,'12' AS Codigo_Causal
                ,CSU_FRECUENCIA_C12 AS Numero_Inter_Causal
                ,ROUND(CSU_DURACION_C12,3) AS Duracion_Inter_Causal FROM QA_TCSU
         WHERE CSU_DURACION_C12 > 0 AND CSU_PERIODO_OP = TO_DATE(:PERIODO,'DD/MM/YYYY')
       UNION ALL
        --CAUSAL (13)
         SELECT  /*TO_CHAR(CSU_PERIODO_OP,'DD/MM/YYYY') AS CS2_PERIODO_OP,*/CSU_NIU  AS NIU,ROUND(CSU_DIU,3)  AS DIU,ROUND(CSU_DIUM,3) AS DIUM,CSU_FIU  AS FIU,CSU_FIUM AS FIUM,'161' AS ID_Mercado
                ,'13' AS Codigo_Causal
                ,CSU_FRECUENCIA_C13 AS Numero_Inter_Causal
                ,ROUND(CSU_DURACION_C13,3) AS Duracion_Inter_Causal FROM QA_TCSU
         WHERE CSU_DURACION_C13 > 0 AND CSU_PERIODO_OP = TO_DATE(:PERIODO,'DD/MM/YYYY')
       UNION ALL
        --CAUSAL (14)
         SELECT  /*TO_CHAR(CSU_PERIODO_OP,'DD/MM/YYYY') AS CS2_PERIODO_OP,*/CSU_NIU  AS NIU,ROUND(CSU_DIU,3)  AS DIU,ROUND(CSU_DIUM,3) AS DIUM,CSU_FIU  AS FIU,CSU_FIUM AS FIUM,'161' AS ID_Mercado
                ,'14' AS Codigo_Causal
                ,CSU_FRECUENCIA_C14 AS Numero_Inter_Causal
                ,ROUND(CSU_DURACION_C14,3) AS Duracion_Inter_Causal FROM QA_TCSU
         WHERE CSU_DURACION_C14 > 0 AND CSU_PERIODO_OP = TO_DATE(:PERIODO,'DD/MM/YYYY')
       UNION ALL
        --CAUSAL (15)
         SELECT  /*TO_CHAR(CSU_PERIODO_OP,'DD/MM/YYYY') AS CS2_PERIODO_OP,*/CSU_NIU  AS NIU,ROUND(CSU_DIU,3)  AS DIU,ROUND(CSU_DIUM,3) AS DIUM,CSU_FIU  AS FIU,CSU_FIUM AS FIUM,'161' AS ID_Mercado
                ,'15' AS Codigo_Causal
                ,CSU_FRECUENCIA_C15 AS Numero_Inter_Causal
                ,ROUND(CSU_DURACION_C15,3) AS Duracion_Inter_Causal FROM QA_TCSU
         WHERE CSU_DURACION_C15 > 0 AND CSU_PERIODO_OP = TO_DATE(:PERIODO,'DD/MM/YYYY')
       UNION ALL
       --CAUSAL (16)
         SELECT  /*TO_CHAR(CSU_PERIODO_OP,'DD/MM/YYYY') AS CS2_PERIODO_OP,*/CSU_NIU  AS NIU,ROUND(CSU_DIU,3)  AS DIU,ROUND(CSU_DIUM,3) AS DIUM,CSU_FIU  AS FIU,CSU_FIUM AS FIUM,'161' AS ID_Mercado
                ,'16' AS Codigo_Causal
                ,0 AS Numero_Inter_Causal
                ,0 AS Duracion_Inter_Causal FROM QA_TCSU
              WHERE CSU_DURACION_C1  = 0 AND CSU_DURACION_C2  = 0 
                AND CSU_DURACION_C3  = 0 AND CSU_DURACION_C4  = 0 
                AND CSU_DURACION_C5  = 0 AND CSU_DURACION_C6  = 0 
                AND CSU_DURACION_C7  = 0 AND CSU_DURACION_C8  = 0 
                AND CSU_DURACION_C9  = 0 AND CSU_DURACION_C10 = 0
                AND CSU_DURACION_C11 = 0 AND CSU_DURACION_C12 = 0
                AND CSU_DURACION_C13 = 0 AND CSU_DURACION_C14 = 0
                AND CSU_DURACION_C15 = 0 AND CSU_PERIODO_OP = TO_DATE(:PERIODO,'DD/MM/YYYY')
              ; 



 
              
                