
-- TIPO DE CARGA DE TRANSFORMADORES DE DISTRIBUCION
SELECT T1.TC1_CODCONEX,
       (CASE WHEN(MAX(T2.TC1_ESTSECT)<=6) THEN('Residencial')
             WHEN(MAX(T2.TC1_ESTSECT)= 7) THEN('Industrial')
             WHEN(MAX(T2.TC1_ESTSECT)= 8) THEN('Comercial')
             WHEN(MAX(T2.TC1_ESTSECT)= 9) THEN('Oficial')
             WHEN(MAX(T2.TC1_ESTSECT)=10) THEN('Provisional')
             WHEN(MAX(T2.TC1_ESTSECT)=11) THEN('Alumbrado')
             END) TC1_ESTSECT
FROM(
		SELECT TC1_CODCONEX, MAX(CANT) AS CANT
		FROM (
					SELECT TC1_CODCONEX,TC1_ESTSECT, COUNT(TC1_ESTSECT) AS CANT
					FROM BRAE.QA_TTC1
					WHERE TC1_PERIODO=202106
					AND TC1_ESTSECT <= 11
					GROUP BY TC1_CODCONEX,TC1_ESTSECT
					ORDER BY 1
		     )
		GROUP BY TC1_CODCONEX
		ORDER BY 1
		) T1
LEFT OUTER JOIN (SELECT TC1_CODCONEX,TC1_ESTSECT, COUNT(TC1_ESTSECT) AS CANT
									FROM BRAE.QA_TTC1
									WHERE TC1_PERIODO=202106
									AND TC1_ESTSECT <= 11
									GROUP BY TC1_CODCONEX,TC1_ESTSECT
                ) T2 ON (T2.CANT||T2.TC1_CODCONEX = T1.CANT||T1.TC1_CODCONEX)
GROUP BY T1.TC1_CODCONEX,T1.CANT;








