create table QA_TFDDBACKUP_TRASLAPE
(
    TRA_CODIGOEVENTO_I VARCHAR2(10),
    TRA_CODIGOEVENTO_F VARCHAR2(10),
    TRA_CODIGOELEMENTO VARCHAR2(16),
    TRA_FINICIAL       DATE,
    TRA_FFINAL         DATE,
    TRA_CAUSA_OR       VARCHAR2(50)
)
/


