create table QA_TMETAS_CALMEDIA
(
    PERIODO_META NUMBER,
    SAIDI_RJ     NUMBER,
    SAIFI_RJ     NUMBER,
    SAIDI_MJT    NUMBER,
    SAIFI_MJT    NUMBER,
    SAIDI_MJT_LS NUMBER,
    SAIFI_MJT_LS NUMBER,
    SAIDI_MJT_LI NUMBER,
    SAIFI_MJT_LI NUMBER,
    SAIDI_LP     NUMBER,
    SAIFI_LP     NUMBER
)
/


