create table QA_TCS3
(
    CS3_PERIODO_OP DATE,
    CS3_INCD1      NUMBER,
    CS3_INCD2      NUMBER,
    CS3_INCD3      NUMBER,
    CS3_INCF1      NUMBER,
    CS3_INCF2      NUMBER,
    CS3_INCF3      NUMBER,
    CS3_IC_SAIDI   NUMBER,
    CS3_IC_SAIFI   NUMBER,
    CS3_IF_SAIDI   NUMBER,
    CS3_IF_SAIFI   NUMBER,
    CS3_IV_SAIDI   NUMBER,
    CS3_IV_SAIFI   NUMBER
)
/


