create table QA_TFDDAJUSTES
(
    FDR_PERIODO_OP     DATE,
    FDR_CODIGOEVENTO   VARCHAR2(10) not null,
    FDR_FINICIAL       DATE,
    FDR_FFINAL         DATE,
    FDR_CODIGOELEMENTO VARCHAR2(16),
    FDR_TIPOELEMENTO   NUMBER,
    FDR_CAUSA          VARCHAR2(16),
    FDR_CONTINUIDAD    VARCHAR2(2),
    FDR_EXCLUIDOZNI    NUMBER,
    FDR_AFECTACONGEN   NUMBER,
    FDR_USUARIOAP      NUMBER,
    FDR_TIPOAJUSTE     NUMBER,
    FDR_RADICADO       VARCHAR2(30)
)
/


