CREATE OR REPLACE PROCEDURE BRAE.QA_PCSX_AD(FECHAOPERACION IN DATE)
AS
BEGIN

	
	/* 2. llenar tabla QA_TCSX_AD ********************************************
	   PERIODO POR PERIODOS MENSUALES*/
	
	--INSERCCION DE VALORES A LA TABLA QA_TCSX_AD
	DELETE FROM QA_TCSX_AD
	WHERE CSU_PERIODO_OP = FECHAOPERACION;
	COMMIT;
	
	INSERT INTO QA_TCSX_AD
	SELECT FDD_CODIGOELEMENTO AS CSU_NIU
	      ,SUM(
	           (CASE WHEN (FDD_FFINAL >= ADD_MONTHS(FECHAOPERACION, + 1) OR FDD_FFINAL IS NULL)
	                 THEN
	                  (ADD_MONTHS(FECHAOPERACION, + 1) - FDD_FINICIAL) * 24
	                 ELSE
	                    CASE WHEN (FDD_FINICIAL < FECHAOPERACION)
	                    THEN
	                       (FDD_FFINAL - FECHAOPERACION) * 24
	                    ELSE
	                     (FDD_FFINAL - FDD_FINICIAL) * 24
	                     END
	            END)       
	      ) AS CSU_DIUM
	     ,COUNT(FDD_CODIGOELEMENTO) AS FIUM
	     ,FECHAOPERACION AS CSU_PERIODO_OP
	FROM QA_TFDDREGISTRO_AD
	WHERE TRUNC(FDD_PERIODO_OP,'MM')= FECHAOPERACION
	AND FDD_EXCLUSION =  'NO EXCLUIDA'
	GROUP BY FDD_CODIGOELEMENTO;
	
	COMMIT;

	-- 3. LLENAR TABLA QA_TCSU_AD CON LAS ALTERACIONES EN ALGUNOS REGISTROS SEGUN EVENTOS BT
	DELETE FROM QA_TCSU_AD
	WHERE CSU_PERIODO_OP = FECHAOPERACION;
	COMMIT;

	INSERT INTO QA_TCSU_AD
	SELECT T1. CSU_NIU
	,(CASE WHEN(T1.CSU_DIUM + NVL(T2.CSU_DIUM,0)<TO_NUMBER(TO_CHAR(LAST_DAY(FECHAOPERACION),'DD'))*24) 
	       THEN (T1.CSU_DIUM + NVL(T2.CSU_DIUM,0))
	       ELSE (TO_NUMBER(TO_CHAR(LAST_DAY(FECHAOPERACION),'DD'))*24)
	       END ) + NVL(T3.CSU_DIU_AD,0) AS CSU_DIU
	,(CASE WHEN(T1.CSU_DIUM + NVL(T2.CSU_DIUM,0)<TO_NUMBER(TO_CHAR(LAST_DAY(FECHAOPERACION),'DD'))*24) 
	       THEN (T1.CSU_DIUM + NVL(T2.CSU_DIUM,0))
	       ELSE (TO_NUMBER(TO_CHAR(LAST_DAY(FECHAOPERACION),'DD'))*24)
	       END )AS CSU_DIUM 
	,T1.   CSU_FIUM + NVL(T2.CSU_FIUM,0) + NVL(T4.CSU_FIU_AD,0) AS CSU_FIU
	,T1.   CSU_FIUM + NVL(T2.CSU_FIUM,0) AS CSU_FIUM
	,T1.   CSU_IDMERCADO
	,T1.   CSU_FRECUENCIA_C1
	,T1.   CSU_DURACION_C1
	,T1.   CSU_FRECUENCIA_C2
	,T1.   CSU_DURACION_C2
	,T1.   CSU_FRECUENCIA_C3
	,T1.   CSU_DURACION_C3
	,T1.   CSU_FRECUENCIA_C4
	,T1.   CSU_DURACION_C4
	,T1.   CSU_FRECUENCIA_C5
	,T1.   CSU_DURACION_C5
	,T1.   CSU_FRECUENCIA_C6
	,T1.   CSU_DURACION_C6
	,T1.   CSU_FRECUENCIA_C7
	,T1.   CSU_DURACION_C7
	,T1.   CSU_FRECUENCIA_C8
	,T1.   CSU_DURACION_C8
	,T1.   CSU_FRECUENCIA_C9
	,T1.   CSU_DURACION_C9
	,T1.   CSU_FRECUENCIA_C10
	,T1.   CSU_DURACION_C10
	,T1.   CSU_FRECUENCIA_C11
	,T1.   CSU_DURACION_C11
	,T1.   CSU_FRECUENCIA_C12
	,T1.   CSU_DURACION_C12
	,T1.   CSU_FRECUENCIA_C13
	,T1.   CSU_DURACION_C13
	,T1.   CSU_FRECUENCIA_C14
	,T1.   CSU_DURACION_C14
	,T1.   CSU_FRECUENCIA_C15
	,T1.   CSU_DURACION_C15
	,T1.   CSU_PERIODO_OP
	FROM QA_TCSU T1
	LEFT OUTER JOIN (SELECT * FROM QA_TCSX_AD WHERE CSU_PERIODO_OP=FECHAOPERACION) T2 
	                ON T2.CSU_NIU = T1.CSU_NIU
	LEFT OUTER JOIN (SELECT CSU_NIU, SUM(NVL(CSU_DIUM,0)) AS CSU_DIU_AD 
	                 FROM QA_TCSU_AD
	                 WHERE CSU_PERIODO_OP IN (
	                         ADD_MONTHS(FECHAOPERACION, -1),
	                         ADD_MONTHS(FECHAOPERACION, -2),
	                         ADD_MONTHS(FECHAOPERACION, -3),
	                         ADD_MONTHS(FECHAOPERACION, -4),
	                         ADD_MONTHS(FECHAOPERACION, -5),
	                         ADD_MONTHS(FECHAOPERACION, -6),
	                         ADD_MONTHS(FECHAOPERACION, -7),
	                         ADD_MONTHS(FECHAOPERACION, -8),
	                         ADD_MONTHS(FECHAOPERACION, -9),
	                         ADD_MONTHS(FECHAOPERACION,-10),
	                         ADD_MONTHS(FECHAOPERACION,-11))
	          GROUP BY CSU_NIU) T3 ON T3.CSU_NIU = T1.CSU_NIU
	LEFT OUTER JOIN (SELECT CSU_NIU, SUM(NVL(CSU_FIUM,0)) AS CSU_FIU_AD 
	                 FROM QA_TCSU_AD
	                 WHERE CSU_PERIODO_OP IN (
	                         ADD_MONTHS(FECHAOPERACION, -1),
	                         ADD_MONTHS(FECHAOPERACION, -2),
	                         ADD_MONTHS(FECHAOPERACION, -3),
	                         ADD_MONTHS(FECHAOPERACION, -4),
	                         ADD_MONTHS(FECHAOPERACION, -5),
	                         ADD_MONTHS(FECHAOPERACION, -6),
	                         ADD_MONTHS(FECHAOPERACION, -7),
	                         ADD_MONTHS(FECHAOPERACION, -8),
	                         ADD_MONTHS(FECHAOPERACION, -9),
	                         ADD_MONTHS(FECHAOPERACION,-10),
	                         ADD_MONTHS(FECHAOPERACION,-11))
	          GROUP BY CSU_NIU) T4 ON T4.CSU_NIU = T1.CSU_NIU          
	WHERE T1.CSU_PERIODO_OP = FECHAOPERACION
	;
	
	COMMIT;

	INSERT INTO QA_TLOG_EJECUCION
    SELECT SYSDATE,'QA_PCSX_AD','PROCEDIMIENTO',UPPER(sys_context('USERENV','OS_USER')),'EXITOSO','Se ha ejecutado el procedimiento '||FECHAOPERACION FROM DUAL;
   	COMMIT;

END QA_PCSX_AD;