create table QA_TTT11_REGISTRO
(
    TT11_PERIODO_OP     DATE,
    TT11_ID             NUMBER,
    TT11_DESCRIPCION    VARCHAR2(40),
    TT11_FINICIAL       DATE,
    TT11_FFINAL         DATE,
    TT11_SUBESTACION    VARCHAR2(30),
    TT11_IUS            VARCHAR2(4),
    TT11_ALCANCE        VARCHAR2(400),
    TT11_CODIGOPROYECTO VARCHAR2(50),
    TT11_CERTIFICADO    NUMBER,
    TT11_EJECUTADO      NUMBER,
    TT11_FCERTIFICACION DATE,
    TT11_FCREACION      DATE,
    TT11_TIPOPROYECTO   VARCHAR2(20)
)
/


