create or replace PROCEDURE      QA_PFDDREPORTE_CDL(FECHAOPERACION DATE)
AS

TYPE T_QA_TFDDREPORTE_CDL IS TABLE OF QA_TFDDREPORTE_CDL%ROWTYPE;
  V_QA_TFDDREPORTE_CDL T_QA_TFDDREPORTE_CDL;

 
BEGIN
 
 --BORRAR TABLA
 DELETE FROM BRAE.QA_TFDDREPORTE_CDL;
 COMMIT;
 
 --LLENAR CURSOR
 
 SELECT FDR_CODIGOEVENTO,
    (CASE WHEN(FDR_TIPOCARGA='XR') THEN(TO_CHAR(I.FINICIAL,'DD/MM/YYYY hh24:mi:ss')) ELSE(TO_CHAR(FDR_FINICIAL,'DD/MM/YYYY hh24:mi:ss')) END) FDR_FINICIAL,
    (CASE WHEN(FDR_TIPOCARGA='XR') THEN(TO_CHAR(I.FFINAL,'DD/MM/YYYY hh24:mi:ss'))  ELSE(TO_CHAR(FDR_FFINAL,'DD/MM/YYYY hh24:mi:ss'))  END) FDR_FFINAL,
    FDR_CODIGOELEMENTO,
    FDR_TIPOELEMENTO,
    FDR_CAUSA,
    FDR_CONTINUIDAD,
    FDR_EXCLUIDOZNI,
    FDR_AFECTACONGEN,
    FDR_USUARIOAP,
    FDR_TIPOCARGA
    BULK COLLECT INTO V_QA_TFDDREPORTE_CDL
    FROM BRAE.QA_TFDDREPORTE QA
    LEFT OUTER JOIN (SELECT MINICIAL
                           , FINICIAL FINICIAL
                           ,(CASE WHEN(TRUNC(FFINAL  ) > TRUNC(FECHAOPERACION)) THEN(NULL) ELSE(FFINAL) END) FFINAL
                           , TRAFO AS ELEMENTO
                     FROM OMS.INTERUPC                                   
                     WHERE TYPEEQUIP = 'Transformer'
                     AND FINICIAL>= ADD_MONTHS(TO_DATE('01/'||TO_CHAR(FECHAOPERACION, 'MM/yyyy'),'DD/MM/YYYY'),-1)
                    ) I ON I.MINICIAL||I.ELEMENTO = QA.FDR_CODIGOEVENTO||QA.FDR_CODIGOELEMENTO
    WHERE TRUNC(FDR_PERIODO_OP) = TRUNC(FECHAOPERACION)
    AND FDR_CODIGOEVENTO <> 'NA'
    ORDER BY FDR_CODIGOEVENTO ASC;
 
      FOR i IN V_QA_TFDDREPORTE_CDL.FIRST .. V_QA_TFDDREPORTE_CDL.LAST LOOP
                  INSERT INTO BRAE.QA_TFDDREPORTE_CDL
                  VALUES V_QA_TFDDREPORTE_CDL(i);
      END LOOP; 
      

END QA_PFDDREPORTE_CDL;


