CREATE OR REPLACE PROCEDURE BRAE.QA_PFDDREVERSAR(FECHAOPERACION DATE)
AS

MAX_PERIODO DATE;
PUBLICADO VARCHAR2(2);

BEGIN

    SELECT MAX(FDD_PERIODO_OP) 
    INTO MAX_PERIODO
    FROM QA_TFDDREGISTRO
    ;

    SELECT DISTINCT FDD_PUBLICADO
    INTO PUBLICADO
    FROM QA_TFDDREGISTRO;

    IF MAX_PERIODO = FECHAOPERACION AND PUBLICADO = 'N' THEN
  --ELIMINA LOS REGISTROS DE RECONFIG N
				DELETE FROM QA_TFDDREGISTRO
				WHERE FDD_PERIODO_OP = FECHAOPERACION
				AND FDD_RECONFIG ='N';
				COMMIT;
  --ACTUALIZA A LA FORMA ANTERIOR LOS REGISTROS RECONFIG S
				UPDATE QA_TFDDREGISTRO
				SET
				FDD_FFINAL =  NULL,
				FDD_CONTINUIDAD = 'S',
				FDD_FREG_CIERRE = NULL,
				FDD_PERIODO_OP = TRUNC(FDD_FINICIAL),
				FDD_RECONFIG = 'N'
				WHERE FDD_PERIODO_OP = FECHAOPERACION
				AND FDD_RECONFIG = 'S';
				COMMIT;

  --ELIMINA EL REPORTE CREADO
				DELETE FROM QA_TFDDREPORTE
				WHERE FDR_PERIODO_OP=FECHAOPERACION;
				COMMIT;
                
    --ESCRITURA EN TABLA LOG
                INSERT INTO QA_TLOG_EJECUCION
                SELECT SYSDATE,'QA_PFDDREVERSAR','PROCEDIMIENTO',sys_context('USERENV','OS_USER'),'EXITOSO','NA' FROM DUAL;
    ELSE
    --ESCRITURA EN TABLA LOG
                IF MAX_PERIODO <> FECHAOPERACION THEN
                    INSERT INTO QA_TLOG_EJECUCION
                    SELECT SYSDATE,'QA_PFDDREVERSAR','PROCEDIMIENTO',sys_context('USERENV','OS_USER'),'FALLIDO','Intento de reversión a un periodo no permitido' FROM DUAL;
                ELSE
                    IF PUBLICADO = 'S' THEN
                        INSERT INTO QA_TLOG_EJECUCION
                        SELECT SYSDATE,'QA_PFDDREVERSAR','PROCEDIMIENTO',sys_context('USERENV','OS_USER'),'FALLIDO','Intento de reversión a un periodo publicado' FROM DUAL;
                    END IF;
                END IF;
    END IF;
    

END QA_PFDDREVERSAR;
/