CREATE OR REPLACE PROCEDURE BRAE.QA_PFDDPRELIMINAR(FECHAOPERACION DATE) 
AS
  BANDERA BOOLEAN;
  CONTADOR NUMBER;
  CANTIDAD NUMBER;
  FECHACONSUMO DATE;
  FECHAFRM1 NUMBER;
  FECHAREGISTRO DATE;
  V_FDD_CODIGOEVENTO BRAE.QA_TFDDPRELIMINAR.FDD_CODIGOEVENTO%TYPE;
  V_FDD_CODIGOEVENTO_ABIERTO BRAE.QA_TFDDPRELIMINAR.FDD_CODIGOEVENTO%TYPE;
  V_FDD_ENS_EVENTO BRAE.QA_TFDDPRELIMINAR.FDD_ENS_EVENTO%TYPE;
  V_FDD_FINICIAL BRAE.QA_TFDDPRELIMINAR.FDD_FINICIAL%TYPE;
  V_FDD_FFINAL BRAE.QA_TFDDPRELIMINAR.FDD_FFINAL%TYPE;
  V_FDD_CODIGOELEMENTO BRAE.QA_TFDDPRELIMINAR.FDD_CODIGOELEMENTO%TYPE;
  V_FDD_CODIGOELEMENTO_ABIERTO BRAE.QA_TFDDPRELIMINAR.FDD_CODIGOELEMENTO%TYPE;
  V_FDD_TIPOELEMENTO BRAE.QA_TFDDPRELIMINAR.FDD_TIPOELEMENTO%TYPE;
  V_FDD_CONSUMODIA BRAE.QA_TFDDPRELIMINAR.FDD_CONSUMODIA%TYPE;
  V_FDD_ENS_ELEMENTO BRAE.QA_TFDDPRELIMINAR.FDD_ENS_ELEMENTO%TYPE;
  V_FDD_CAUSA BRAE.QA_TFDDPRELIMINAR.FDD_CAUSA%TYPE;
  V_FDD_PERIODO_OP BRAE.QA_TFDDPRELIMINAR.FDD_PERIODO_OP%TYPE;
  V_FDD_CONTINUIDAD BRAE.QA_TFDDPRELIMINAR.FDD_CONTINUIDAD%TYPE;
  V_FDD_CONTINUIDAD_ABIERTO BRAE.QA_TFDDPRELIMINAR.FDD_CONTINUIDAD%TYPE;
  V_FDD_FREG_APERTURA BRAE.QA_TFDDPRELIMINAR.FDD_FREG_APERTURA%TYPE;
  V_FDD_FREG_CIERRE BRAE.QA_TFDDPRELIMINAR.FDD_FREG_CIERRE%TYPE;
  V_FDD_RECONFIG BRAE.QA_TFDDPRELIMINAR.FDD_RECONFIG%TYPE;
  V_FDD_USUARIOAP BRAE.QA_TFDDPRELIMINAR.FDD_USUARIOAP%TYPE;
  V_FDD_ESTADOREPORTE BRAE.QA_TFDDPRELIMINAR.FDD_ESTADOREPORTE%TYPE;
  V_FDD_PUBLICADO BRAE.QA_TFDDPRELIMINAR.FDD_PUBLICADO%TYPE;
  V_FDD_PERIODO_TC1 BRAE.QA_TFDDPRELIMINAR.FDD_PERIODO_TC1%TYPE;
  V_FDD_EXCLUSION BRAE.QA_TFDDPRELIMINAR.FDD_EXCLUSION%TYPE;
  V_TC1_CODCONEX BRAE.QA_TTC1.TC1_CODCONEX%TYPE;
  V_FDD_CAUSA_CREG BRAE.QA_TFDDPRELIMINAR.FDD_CAUSA_CREG%TYPE;
  V_FDD_ENEG_EVENTO BRAE.QA_TFDDPRELIMINAR.FDD_ENEG_EVENTO%TYPE;
  V_FDD_ENEG_ELEMENTO BRAE.QA_TFDDPRELIMINAR.FDD_ENEG_ELEMENTO%TYPE;
  V_FDD_CODIGOGENERADOR BRAE.QA_TFDDPRELIMINAR.FDD_CODIGOGENERADOR%TYPE;
  V_FDD_FPUB_APERTURA BRAE.QA_TFDDPRELIMINAR.FDD_FPUB_APERTURA%TYPE;
  V_FDD_FPUB_CIERRE BRAE.QA_TFDDPRELIMINAR.FDD_FPUB_CIERRE%TYPE;
  V_FDC_CAUSA_OMS BRAE.QA_TFDDCAUSAS.FDC_CAUSA_OMS%TYPE;
  V_FDC_EXCLUSION BRAE.QA_TFDDCAUSAS.FDC_EXCLUSION%TYPE;
  V_FDC_CAUSA_SSPD BRAE.QA_TFDDCAUSAS.FDC_CAUSA_SSPD%TYPE;  
  V_FDD_CODIGOEVENTO_SMALL BRAE.QA_TFDDPRELIMINAR.FDD_CODIGOEVENTO%TYPE;
  V_FDD_FINICIAL_SMALL BRAE.QA_TFDDPRELIMINAR.FDD_FINICIAL%TYPE;
  V_FDD_FFINAL_SMALL BRAE.QA_TFDDPRELIMINAR.FDD_FFINAL%TYPE;
  V_FDD_CODIGOELEMENTO_SMALL BRAE.QA_TFDDPRELIMINAR.FDD_CODIGOELEMENTO%TYPE;
  
  V_FDD_CODIGOEVENTO_SSPD BRAE.QA_TFDDPRELIMINAR.FDD_CODIGOEVENTO%TYPE;
  V_FDD_FINICIAL_SSPD BRAE.QA_TFDDPRELIMINAR.FDD_FINICIAL%TYPE;
  V_FDD_FFINAL_SSPD BRAE.QA_TFDDPRELIMINAR.FDD_FFINAL%TYPE;
  V_FDD_CODIGOELEMENTO_SSPD BRAE.QA_TFDDPRELIMINAR.FDD_CODIGOELEMENTO%TYPE;
  
 CURSOR C_EVENSMALL IS
    SELECT I.MINICIAL,
           I.FINICIAL,
           I.FFINAL,
           I.TRAFO
   FROM OMS.INTERUPC I
   WHERE I.FINICIAL >= TO_DATE(TO_CHAR(TRUNC(FECHAOPERACION)+(23.95/24),'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')
   AND I.FINICIAL < TRUNC (FECHAOPERACION+1)
   AND I.FFINAL IS NOT NULL
   AND ((I.FFINAL-I.FINICIAL)*24)<=0.05;
   
 CURSOR C_EVENSSPD IS
   SELECT FDD_CODIGOEVENTO,
          FDD_FINICIAL,
          FDD_FFINAL,
          FDD_CODIGOELEMENTO
     FROM BRAE.QA_TFDDPRELIMINAR
     ;--WHERE FDD_PERIODO_OP=TRUNC(FECHAOPERACION);
                  
  CURSOR C_ENS_EVENTO IS
  SELECT FDD_CODIGOEVENTO,SUM(FDD_ENS_ELEMENTO)
  FROM BRAE.QA_TFDDPRELIMINAR
  WHERE FDD_PERIODO_OP=TRUNC(FECHAOPERACION)
  GROUP BY FDD_CODIGOEVENTO;
  
  CURSOR C_EVENTOSABIERTOS IS
  SELECT FDD_CODIGOEVENTO,FDD_CODIGOELEMENTO,FDD_CONTINUIDAD
  FROM BRAE.QA_TFDDREGISTRO
  WHERE FDD_CONTINUIDAD = 'S';
  
  CURSOR C_EVENTOS_ABIERTOS_COPIA IS
     SELECT FDD_CODIGOEVENTO,
            FDD_FINICIAL,
            FDD_FFINAL,
            FDD_CODIGOELEMENTO,
            FDD_TIPOELEMENTO,
            FDD_CONSUMODIA,
            FDD_ENS_ELEMENTO,
            FDD_ENS_EVENTO,
            FDD_ENEG_EVENTO,
            FDD_ENEG_ELEMENTO,
            FDD_CODIGOGENERADOR,
            FDD_CAUSA,
            FDD_CAUSA_CREG,
            FDD_USUARIOAP,
            FDD_CONTINUIDAD,
            FDD_ESTADOREPORTE,
            FDD_PUBLICADO,
            FDD_RECONFIG,
            FDD_PERIODO_OP,
            FDD_FREG_APERTURA,
            FDD_FREG_CIERRE,
            FDD_FPUB_APERTURA,
            FDD_FPUB_CIERRE,
            FDD_PERIODO_TC1,
            FDD_EXCLUSION
  FROM BRAE.QA_TFDDREGISTRO
  WHERE FDD_CONTINUIDAD = 'S';

  CURSOR C_CARGAFDD IS
  SELECT  I.MINICIAL AS FDD_CODIGOEVENTO,
                (CASE WHEN I.FINICIAL<TRUNC(FECHAOPERACION) THEN NULL ELSE TO_TIMESTAMP(TO_CHAR(TO_CHAR(I.FINICIAL,'DD/MM/YYYY hh24:mi:ss')||'.'||LPAD(TO_CHAR(MI.FECHAMS),3,'0')),'DD/MM/YYYY hh24:mi:ss.FF3') END) AS FDD_FINICIAL,
                (CASE WHEN I.FFINAL>=TRUNC(FECHAOPERACION)+1 THEN NULL ELSE TO_TIMESTAMP(CASE WHEN I.FFINAL IS NULL THEN NULL ELSE TO_CHAR(TO_CHAR(I.FFINAL,'DD/MM/YYYY hh24:mi:ss')||'.'||LPAD(TO_CHAR(MF.FECHAMS),3,'0')) END,'DD/MM/YYYY hh24:mi:ss.FF3') END) AS FDD_FFINAL,
                I.TRAFO AS FDD_CODIGOELEMENTO,
                I.TYPEEQUIP AS FDD_TIPOELEMENTO,
                NVL(C.CONS_DIARIO,0) AS FDD_CONSUMODIA,
                (NVL(C.CONS_DIARIO,0))*((CASE WHEN (I.FFINAL>=TRUNC(FECHAOPERACION)+1 OR I.FFINAL IS NULL) THEN NULL ELSE I.FFINAL END) - (CASE WHEN I.FINICIAL IS NULL THEN NULL ELSE I.FINICIAL END)) FDD_ENS_ELEMENTO,
                MI.CAUSA AS FDD_CAUSA,
                TRUNC(FECHAOPERACION) AS FDD_PERIODO_OP,
                (CASE WHEN (I.FFINAL>=TRUNC(FECHAOPERACION)+1 OR I.FFINAL IS NULL) THEN 'S' ELSE 'N' END) AS FDD_CONTINUIDAD,
                FECHAREGISTRO AS FDD_FREG_APERTURA,
                (CASE WHEN (I.FFINAL>=TRUNC(FECHAOPERACION)+1 OR I.FFINAL IS NULL) THEN TO_DATE(NULL) ELSE FECHAREGISTRO END) AS FDD_FREG_CIERRE,
                TO_NUMBER(0) AS FDD_PERIODO_TC1,
                'N' AS FDD_RECONFIG,
                'N' AS FDD_USUARIOAP,
                'N' AS FDD_ESTADOREPORTE,
                'N' AS FDD_PUBLICADO,
                CS.CAUSA015 AS FDD_CAUSA_CREG
                FROM OMS.INTERUPC I
        LEFT OUTER JOIN OMS.MANIOBRAS MI ON MI.CODE = I.MINICIAL
        LEFT OUTER JOIN OMS.MANIOBRAS MF ON MF.CODE = I.MFINAL
        LEFT OUTER JOIN OMS.CAUSAS CS ON CS.CODE = MI.CAUSA       
        LEFT OUTER JOIN BRAE.QA_TCONSUMOSDIA C ON (C.CONS_ELEMENTO = I.TRAFO AND C.CONS_PERIODO = FECHACONSUMO)
        WHERE MI.CAUSA <> 'PRUEBA' 
        AND MI.TIPO <> 'PRUEBA' ---REVISA ENERGY
        AND MI.EJECUTADO = 1
        AND I.TYPEEQUIP IN ('Transformer')
        AND ((I.FINICIAL >= TRUNC(FECHAOPERACION) AND I.FINICIAL < TRUNC(FECHAOPERACION) + 1) OR (I.FFINAL >= TRUNC(FECHAOPERACION) AND I.FFINAL < TRUNC(FECHAOPERACION) + 1));
        

  CURSOR C_TRANSFORMADORES_AP IS
    SELECT TC1_CODCONEX, COUNT(TC1_TC1) AS CONTADOR 
    FROM QA_TTC1
    WHERE TC1_TC1 LIKE 'CALP%'
    AND TC1_PERIODO = FECHAFRM1
  GROUP BY TC1_CODCONEX;
  
  CURSOR C_TRANSFORMDAORES_TC1 IS
    SELECT DISTINCT(TC1_CODCONEX) 
    FROM BRAE.QA_TTC1
    WHERE TC1_PERIODO = FECHAFRM1;
    
  CURSOR C_EXISTENCIA_REGISTROS IS
    SELECT COUNT(*)
    FROM BRAE.QA_TFDDREGISTRO
    WHERE FDD_PERIODO_OP =  TRUNC(FECHAOPERACION);
    
  CURSOR C_EXISTENCIA_REPORTE_ANTERIOR IS
   SELECT COUNT(*)
   FROM BRAE.QA_TFDDREPORTE
   WHERE FDR_PERIODO_OP = (TRUNC(FECHAOPERACION) - 1);
 
  CURSOR C_EXCLUSION IS
   SELECT FDC_CAUSA_OMS,FDC_EXCLUSION 
   FROM BRAE.QA_TFDDCAUSAS;
   
  CURSOR C_CAUSA_SSPD IS
   SELECT FDC_CAUSA_OMS,FDC_CAUSA_SSPD 
   FROM BRAE.QA_TFDDCAUSAS;
  
BEGIN

 -- BORRAR REGISTROS DE LA TABLA QA_TFDDPRELIMINAR
 BEGIN
   DELETE FROM BRAE.QA_TFDDPRELIMINAR;
   COMMIT;
 END;
 
  -- COPIAR EN LA TABLA PRELIMINAR LOS REGISTROS ABIERTOS
  BEGIN
    OPEN C_EVENTOS_ABIERTOS_COPIA;
      LOOP
        FETCH C_EVENTOS_ABIERTOS_COPIA INTO 
                         V_FDD_CODIGOEVENTO,
                         V_FDD_FINICIAL,
                         V_FDD_FFINAL,
                         V_FDD_CODIGOELEMENTO,
                         V_FDD_TIPOELEMENTO,
                         V_FDD_CONSUMODIA,
                         V_FDD_ENS_ELEMENTO,
                         V_FDD_ENS_EVENTO,
                         V_FDD_ENEG_EVENTO,
                         V_FDD_ENEG_ELEMENTO,
                         V_FDD_CODIGOGENERADOR,
                         V_FDD_CAUSA,
                         V_FDD_CAUSA_CREG,
                         V_FDD_USUARIOAP,
                         V_FDD_CONTINUIDAD,
                         V_FDD_ESTADOREPORTE,
                         V_FDD_PUBLICADO,
                         V_FDD_RECONFIG,
                         V_FDD_PERIODO_OP,
                         V_FDD_FREG_APERTURA,
                         V_FDD_FREG_CIERRE,
                         V_FDD_FPUB_APERTURA,
                         V_FDD_FPUB_CIERRE,
                         V_FDD_PERIODO_TC1,
                         V_FDD_EXCLUSION;
        EXIT WHEN C_EVENTOS_ABIERTOS_COPIA%NOTFOUND;
        
        INSERT INTO BRAE.QA_TFDDPRELIMINAR
                       (FDD_CODIGOEVENTO,
                        FDD_FINICIAL,
                        FDD_FFINAL,
                        FDD_CODIGOELEMENTO,
                        FDD_TIPOELEMENTO,
                        FDD_CONSUMODIA,
                        FDD_ENS_ELEMENTO,
                        FDD_ENS_EVENTO,
                        FDD_ENEG_EVENTO,
                        FDD_ENEG_ELEMENTO,
                        FDD_CODIGOGENERADOR,
                        FDD_CAUSA,
                        FDD_CAUSA_CREG,
                        FDD_USUARIOAP,
                        FDD_CONTINUIDAD,
                        FDD_ESTADOREPORTE,
                        FDD_PUBLICADO,
                        FDD_RECONFIG,
                        FDD_PERIODO_OP,
                        FDD_FREG_APERTURA,
                        FDD_FREG_CIERRE,
                        FDD_FPUB_APERTURA,
                        FDD_FPUB_CIERRE,
                        FDD_PERIODO_TC1,
                        FDD_EXCLUSION) 
              VALUES (V_FDD_CODIGOEVENTO,
                      V_FDD_FINICIAL,
                      V_FDD_FFINAL,
                      V_FDD_CODIGOELEMENTO,
                      V_FDD_TIPOELEMENTO,
                      V_FDD_CONSUMODIA,
                      V_FDD_ENS_ELEMENTO,
                      V_FDD_ENS_EVENTO,
                      V_FDD_ENEG_EVENTO,
                      V_FDD_ENEG_ELEMENTO,
                      V_FDD_CODIGOGENERADOR,
                      V_FDD_CAUSA,
                      V_FDD_CAUSA_CREG,
                      V_FDD_USUARIOAP,
                      V_FDD_CONTINUIDAD,
                      V_FDD_ESTADOREPORTE,
                      V_FDD_PUBLICADO,
                      V_FDD_RECONFIG,
                      V_FDD_PERIODO_OP,
                      V_FDD_FREG_APERTURA,
                      V_FDD_FREG_CIERRE,
                      V_FDD_FPUB_APERTURA,
                      V_FDD_FPUB_CIERRE,
                      V_FDD_PERIODO_TC1,
                      V_FDD_EXCLUSION);
        
      END LOOP;
    CLOSE C_EVENTOS_ABIERTOS_COPIA;
    COMMIT;
  END;

  
  --EXTRAER LAS FECHAS PRINCIPALES PARA EL CALCULO DE LOS CONSUMOS Y PARA LA CANTDAD DE USUARIOS POR MES
  BEGIN
    SELECT MAX(CONS_PERIODO) INTO FECHACONSUMO FROM BRAE.QA_TCONSUMOSDIA;
    SELECT MAX(TC1_PERIODO) INTO FECHAFRM1 FROM BRAE.QA_TTC1;
    SELECT SYSDATE INTO FECHAREGISTRO FROM DUAL;
  END; 
  

  --COLOCAR CADA REGISTRO EN LA TABLA QA_TFDDPRELIMINAR
  BEGIN
   
    BANDERA:=FALSE;
    OPEN C_CARGAFDD;
    LOOP
      FETCH C_CARGAFDD INTO V_FDD_CODIGOEVENTO,
                            V_FDD_FINICIAL,
                            V_FDD_FFINAL,
                            V_FDD_CODIGOELEMENTO,
                            V_FDD_TIPOELEMENTO,
                            V_FDD_CONSUMODIA,
                            V_FDD_ENS_ELEMENTO,
                            V_FDD_CAUSA,
                            V_FDD_PERIODO_OP,
                            V_FDD_CONTINUIDAD,
                            V_FDD_FREG_APERTURA,
                            V_FDD_FREG_CIERRE,
                            V_FDD_PERIODO_TC1,
                            V_FDD_RECONFIG,
                            V_FDD_USUARIOAP,
                            V_FDD_ESTADOREPORTE,
                            V_FDD_PUBLICADO,
                            V_FDD_CAUSA_CREG;
                      
      EXIT WHEN C_CARGAFDD%NOTFOUND;
      
        BEGIN
        OPEN C_EVENTOSABIERTOS;
        LOOP
         FETCH C_EVENTOSABIERTOS INTO V_FDD_CODIGOEVENTO_ABIERTO,
                                      V_FDD_CODIGOELEMENTO_ABIERTO,
                                      V_FDD_CONTINUIDAD_ABIERTO;
                                      
         EXIT WHEN C_EVENTOSABIERTOS%NOTFOUND;
         
         
         IF (V_FDD_CODIGOEVENTO=V_FDD_CODIGOEVENTO_ABIERTO 
             AND V_FDD_CODIGOELEMENTO=V_FDD_CODIGOELEMENTO_ABIERTO
             AND V_FDD_CONTINUIDAD_ABIERTO='S') THEN 
            
            BEGIN
             --ACTUALIZAR REGISTROS EN LA TABLA QA_TFDDPRELIMINAR
             UPDATE BRAE.QA_TFDDPRELIMINAR 
             SET
                FDD_FFINAL=V_FDD_FFINAL,
                FDD_CONSUMODIA=V_FDD_CONSUMODIA,                      
                FDD_ENS_ELEMENTO=V_FDD_ENS_ELEMENTO,                     
                FDD_PERIODO_OP=V_FDD_PERIODO_OP,                      
                FDD_CONTINUIDAD='N',
                FDD_RECONFIG='S',
                FDD_ESTADOREPORTE='N',
                FDD_PUBLICADO='N',
                FDD_FREG_CIERRE=FECHAREGISTRO
              WHERE FDD_CODIGOEVENTO=V_FDD_CODIGOEVENTO 
              AND   FDD_CODIGOELEMENTO=V_FDD_CODIGOELEMENTO;
            END;
           BANDERA:=TRUE;
           EXIT;
           
         ELSE
           BANDERA:=FALSE;         
         END IF;         
        END LOOP;
        
        IF BANDERA=FALSE THEN
           BEGIN
             --ADICIONAR REGISTROS A LA TABLA QA_TFDDPRELIMINAR
             IF V_FDD_FINICIAL IS NOT NULL THEN
                INSERT INTO BRAE.QA_TFDDPRELIMINAR
                                      (FDD_CODIGOEVENTO,
                                       FDD_FINICIAL,
                                       FDD_FFINAL,
                                       FDD_CODIGOELEMENTO,
                                       FDD_TIPOELEMENTO,
                                       FDD_CONSUMODIA,
                                       FDD_ENS_ELEMENTO,
                                       FDD_CAUSA,
                                       FDD_PERIODO_OP,
                                       FDD_CONTINUIDAD,
                                       FDD_FREG_APERTURA,
                                       FDD_FREG_CIERRE,
                                       FDD_PERIODO_TC1,
                                       FDD_RECONFIG,
                                       FDD_USUARIOAP,
                                       FDD_ESTADOREPORTE,
                                       FDD_PUBLICADO,
                                       FDD_CAUSA_CREG) 
                               VALUES (V_FDD_CODIGOEVENTO,
                                       V_FDD_FINICIAL,
                                       V_FDD_FFINAL,
                                       V_FDD_CODIGOELEMENTO,
                                       V_FDD_TIPOELEMENTO,
                                       V_FDD_CONSUMODIA,
                                       V_FDD_ENS_ELEMENTO,
                                       V_FDD_CAUSA,
                                       V_FDD_PERIODO_OP,
                                       V_FDD_CONTINUIDAD,
                                       V_FDD_FREG_APERTURA,
                                       V_FDD_FREG_CIERRE,
                                       V_FDD_PERIODO_TC1,
                                       V_FDD_RECONFIG,
                                       V_FDD_USUARIOAP,
                                       V_FDD_ESTADOREPORTE,
                                       V_FDD_PUBLICADO,
                                       V_FDD_CAUSA_CREG);
             END IF;   
           END;                    
        END IF;
        CLOSE C_EVENTOSABIERTOS;
      END;
      
    END LOOP;
    CLOSE C_CARGAFDD;
    COMMIT;
    
 
   /*MARCAR EL CAMPO FDD_USUARIOAP CON 'S' PARA TODOS LOS REGISTROS 
  ALMACENADOS EN EL PERIODO_OP CON TRANSFORMADORES CON ALUMABRADO PUBLICO*/

    BEGIN
      OPEN C_TRANSFORMADORES_AP;
      LOOP
        FETCH C_TRANSFORMADORES_AP INTO V_FDD_CODIGOELEMENTO,CONTADOR;
        EXIT WHEN C_TRANSFORMADORES_AP%NOTFOUND;
        BEGIN
          UPDATE BRAE.QA_TFDDPRELIMINAR SET FDD_USUARIOAP='S'
          WHERE FDD_CODIGOELEMENTO=V_FDD_CODIGOELEMENTO
          AND FDD_PERIODO_OP=FECHAOPERACION
          AND CONTADOR>0; 
        END;
      END LOOP;
      CLOSE C_TRANSFORMADORES_AP;
      COMMIT;
    END;


   --MARCAR EL CAMPO FDD_PERIODO_TC1 CON 'TC1_PERIODO' PARA TODOS LOS REGISTROS 

    BEGIN
      OPEN C_TRANSFORMDAORES_TC1;
      LOOP
        FETCH C_TRANSFORMDAORES_TC1 INTO V_TC1_CODCONEX;
        EXIT WHEN C_TRANSFORMDAORES_TC1%NOTFOUND;
        BEGIN
          UPDATE BRAE.QA_TFDDPRELIMINAR SET FDD_PERIODO_TC1=FECHAFRM1
          WHERE FDD_CODIGOELEMENTO=V_TC1_CODCONEX
          AND FDD_PERIODO_OP=FECHAOPERACION; 
        END;
      END LOOP;
      CLOSE C_TRANSFORMDAORES_TC1;
      COMMIT;
    END;

   -- ELIMINA DE LA TABLA DE REGISTROS LOS EVENTOS CON TRANSFORMADORES QUE NO ESTAN EN EL FORMATO 1  
  
    BEGIN
      DELETE FROM BRAE.QA_TFDDPRELIMINAR
      WHERE FDD_PERIODO_TC1=0; 
      COMMIT;
    END;  
    
    --COMPLETAR EL CAMPO ENS_EVENTO PARA TODOS LOS REGISTROS ALMACENADOS AL PERIODO_OP
 
    BEGIN
      OPEN C_ENS_EVENTO;
      LOOP
        FETCH C_ENS_EVENTO INTO V_FDD_CODIGOEVENTO,V_FDD_ENS_EVENTO;
        EXIT WHEN C_ENS_EVENTO%NOTFOUND;
        BEGIN
          UPDATE BRAE.QA_TFDDPRELIMINAR SET FDD_ENS_EVENTO=V_FDD_ENS_EVENTO
          WHERE FDD_CODIGOEVENTO=V_FDD_CODIGOEVENTO
          AND FDD_PERIODO_OP=FECHAOPERACION; 
        END;
      END LOOP;
      CLOSE C_ENS_EVENTO;
      COMMIT;
    END;
        
   END;  
   
   --COMPLETAR EL CAMPO FDD_EXCLUSION PARA TODOS LOS REGISTROS ALMACENADOS AL PERIODO_OP
 
    BEGIN
      OPEN C_EXCLUSION;
      LOOP
        FETCH C_EXCLUSION INTO V_FDC_CAUSA_OMS,V_FDC_EXCLUSION;
        EXIT WHEN C_EXCLUSION%NOTFOUND;
        BEGIN
          UPDATE BRAE.QA_TFDDPRELIMINAR SET FDD_EXCLUSION=V_FDC_EXCLUSION
          WHERE FDD_CAUSA=V_FDC_CAUSA_OMS
          AND FDD_PERIODO_OP=FECHAOPERACION; 
        END;
      END LOOP;
      CLOSE C_EXCLUSION;
      COMMIT;
    END;
    
    --COMPLETAR EL CAMPO FDD_CAUSA_SSPD PARA TODOS LOS REGISTROS ALMACENADOS AL PERIODO_OP
 
    BEGIN
      OPEN C_CAUSA_SSPD;
      LOOP
        FETCH C_CAUSA_SSPD INTO V_FDC_CAUSA_OMS,V_FDC_CAUSA_SSPD;
        EXIT WHEN C_CAUSA_SSPD%NOTFOUND;        
        
        BEGIN
            UPDATE BRAE.QA_TFDDREGISTRO
               SET FDD_CAUSA_SSPD =
                      (CASE
                          WHEN (  (  TO_DATE (
                                        TO_CHAR (FDD_FFINAL, 'DD/MM/YYYY hh24:mi:ss'),
                                        'DD/MM/YYYY hh24:mi:ss')
                                   - TO_DATE (
                                        TO_CHAR (FDD_FINICIAL, 'DD/MM/YYYY hh24:mi:ss'),
                                        'DD/MM/YYYY hh24:mi:ss'))
                                * 24) <= 0.05
                          THEN
                             1
                          ELSE
                             NVL (V_FDC_CAUSA_SSPD, 0)
                       END)
             WHERE FDD_CAUSA = V_FDC_CAUSA_OMS;
        END;
      END LOOP;
      CLOSE C_CAUSA_SSPD;
      COMMIT;
     END; 
    
    -- VERIFICAR CAUSAS_SSPD ASIGNADAS CON EL VALOR DIFERENTE DE '1'
    
     BEGIN
      OPEN C_EVENSMALL;
        LOOP
          FETCH C_EVENSMALL INTO  V_FDD_CODIGOEVENTO_SMALL,
                                  V_FDD_FINICIAL_SMALL,
                                  V_FDD_FFINAL_SMALL,
                                  V_FDD_CODIGOELEMENTO_SMALL;
          EXIT WHEN C_EVENSMALL%NOTFOUND;
          
          BEGIN
            OPEN C_EVENSSPD;
            LOOP
              FETCH C_EVENSSPD INTO V_FDD_CODIGOEVENTO_SSPD,
                                    V_FDD_FINICIAL_SSPD,
                                    V_FDD_FFINAL_SSPD,
                                    V_FDD_CODIGOELEMENTO_SSPD;
              EXIT WHEN C_EVENSSPD%NOTFOUND;
              IF (V_FDD_CODIGOEVENTO_SMALL=V_FDD_CODIGOEVENTO_SSPD AND
                 V_FDD_CODIGOELEMENTO_SMALL=V_FDD_CODIGOELEMENTO_SSPD) THEN
                 -- CAMBIAR CAUSA_SSPD A 1 DE LA TABAL QA_TFDDPRELIMINAR
                 UPDATE BRAE.QA_TFDDPRELIMINAR 
                 SET
                   FDD_CAUSA_SSPD=1
                 WHERE FDD_CODIGOEVENTO=V_FDD_CODIGOEVENTO_SMALL
                 AND FDD_CODIGOELEMENTO=V_FDD_CODIGOELEMENTO_SMALL
                 ;--AMD FDD_PERIODO_OP=TRUNC(FECHAOPERACION) --CONDICION PARA QA_PFDDREGISTRO
              END IF;
            END LOOP;
            CLOSE C_EVENSSPD;
            COMMIT;
          END;
          
        END LOOP;
      CLOSE C_EVENSMALL;
    END;

END QA_PFDDPRELIMINAR;
/