CREATE OR REPLACE PROCEDURE BRAE.QA_PFDDPUBLICAR(FECHAOPERACION DATE)
AS

 BEGIN
     
    BEGIN
       UPDATE BRAE.QA_TFDDREGISTRO 
             SET
                FDD_PUBLICADO='S',
                FDD_FPUB_APERTURA=(CASE WHEN FDD_FPUB_APERTURA IS NOT NULL THEN FDD_FPUB_APERTURA ELSE SYSDATE END),
                FDD_FPUB_CIERRE=(CASE WHEN (FDD_FFINAL IS NULL OR FDD_FPUB_CIERRE IS NOT NULL) THEN FDD_FPUB_CIERRE ELSE SYSDATE END)
          WHERE FDD_PERIODO_OP=TRUNC(FECHAOPERACION)
            AND FDD_ESTADOREPORTE='S';
    END;

    COMMIT;

 END QA_PFDDPUBLICAR;
/