create table QA_TTT2_REPORTE
(
    TT2_PERIODO_OP      DATE,
    TT2_CODE_TRAFO      VARCHAR2(20),
    TT2_CODE_IUA        VARCHAR2(20),
    TT2_GRUPOCALIDAD    NUMBER,
    TT2_IDMERCADO       NUMBER,
    TT2_CAPACIDAD_TRAFO NUMBER,
    TT2_PROPIEDAD       NUMBER,
    TT2_TSUBESTACION    NUMBER,
    TT2_LONGITUD        VARCHAR2(20),
    TT2_LATITUD         VARCHAR2(20),
    TT2_ALTITUD         NUMBER,
    TT2_ESTADO          NUMBER,
    TT2_FESTADO         DATE,
    TT2_RESMETODOLOGIA  VARCHAR2(20)
)
/


