create table QA_TTT2_CODIGO_UC
(
    TT2_UNIDAD_CONSTRUCTIVA VARCHAR2(20),
    TT2_DESCRIPCION         VARCHAR2(400),
    TT2_NIVEL_TENSION       VARCHAR2(20),
    TT2_CODIGO_UC           VARCHAR2(20),
    TT2_VALOR_UC            NUMBER
)
/


