create table QA_TTT12_REPORTE
(
    TT12_PERIODO_OP      DATE,
    TT12_ID              NUMBER,
    TT12_NOMBRE_CIRCUITO VARCHAR2(50),
    TT12_IUL_CIRCUITO    VARCHAR2(4),
    TT12_ACTIVIDAD       VARCHAR2(20),
    TT12_CODE_IUA_IUL    VARCHAR2(20),
    TT12_USRS_AFECTADOS  NUMBER,
    TT12_FINICIAL        DATE,
    TT12_FFINAL          DATE,
    TT12_DURACION        NUMBER,
    TT12_MES_EJECUCION   NUMBER
)
/


