
CREATE TABLE BRAE.QA_TFDDCARGA_SP7_TEMP(
IDE_EVENTO VARCHAR2(40)
,IDE_CIRCUITO VARCHAR2(40)
,ELEMENTO_FALLA VARCHAR2(40)
,NODO VARCHAR2(40)
,TIPO_ELEMENTO VARCHAR2(40)
,MANIOBRA_APERTURA VARCHAR2(40)
,MANIOBRA_CIERRE VARCHAR2(40)
,FECHA_DESERGINIZACION DATE
,FECHA_ENERGIZACION DATE
,TRANSFORMADOR  VARCHAR2(40)
,CLIENTES  NUMBER
,DESCRIPCION_CODIGO VARCHAR2(400)
,CODIGO NUMBER
,DURAACION DATE
,UITI NUMBER
,AREA_RESPONSABILIDAD VARCHAR2(40)
,ESTADO_EVENTO VARCHAR2(40)
,USUARIO_CREADOR VARCHAR2(40)
,USUARIO_MODIFICACION VARCHAR2(40)
,TRAFO_AFECTADOS NUMBER
);

/


