CREATE TABLE QA_TFDDCAUSAS_SP7(
	FDD_CATEGORIA				VARCHAR2(20)
,	FDD_CAUSA_SP7				NUMBER
,	FDD_NOMBRE					VARCHAR2(200)
,	FDD_DESCRIPCION				VARCHAR2(400)
,	FDD_CAUSA_CREG				NUMBER
,	FDD_DESCRIPCION_CREG		VARCHAR2(200)
);