create table QA_TFDDREPORTE_CDL
(
    FDR_CODIGOEVENTO   VARCHAR2(10),
    FDR_FINICIAL       DATE,
    FDR_FFINAL         DATE,
    FDR_CODIGOELEMENTO VARCHAR2(16),
    FDR_TIPOELEMENTO   NUMBER,
    FDR_CAUSA          VARCHAR2(16),
    FDR_CONTINUIDAD    VARCHAR2(2),
    FDR_EXCLUIDOZNI    NUMBER,
    FDR_AFECTACONGEN   NUMBER,
    FDR_USUARIOAP      NUMBER,
    FDR_TIPOCARGA      VARCHAR2(20)
)
/


