create table QA_TFDDREFERENCIA
(
    FDD_PERIODO_OP     DATE,
    FDD_CODIGOELEMENTO VARCHAR2(20),
    FDD_IUA            VARCHAR2(20),
    FDD_ALUMBRADO_CALP NUMBER,
    FDD_AUTOGENERADOR  NUMBER,
    FDD_ZONA_NO_INTER  NUMBER,
    FDD_CONSUMO        NUMBER default 0,
    FDD_CANTIDAD_USRS  NUMBER default 0
)
/


