create table QA_TFDDTRASLAPE
(
    TRA_CODIGOEVENTO_A   VARCHAR2(10),
    TRA_CODIGOELEMENTO_A VARCHAR2(16),
    TRA_FINICIAL_A       DATE,
    TRA_FFINAL_A         DATE,
    TRA_CODIGOEVENTO_B   VARCHAR2(10),
    TRA_CODIGOELEMENTO_B VARCHAR2(16),
    TRA_FINICIAL_B       DATE,
    TRA_FFINAL_B         DATE,
    TRA_CASO             VARCHAR2(5)
)
/


