create table QA_TTT11_REPORTE
(
    TT11_PERIODO_OP     DATE,
    TT11_ID             NUMBER,
    TT11_ACTIVIDAD      VARCHAR2(20),
    TT11_OBJETIVO       VARCHAR2(400),
    TT11_CODE_IUA_IUL   VARCHAR2(20),
    TT11_USRS_AFECTADOS NUMBER,
    TT11_FINICIAL       DATE,
    TT11_FFINAL         DATE,
    TT11_DURACION       NUMBER,
    TT11_MEDIO_PUB      VARCHAR2(200),
    TT11_FECHA_PUB      DATE,
    TT11_MES_PROYECCION NUMBER
)
/


