create table QA_TFDDREGISTRO_AI
(
    FDD_CODIGOEVENTO      VARCHAR2(10),
    FDD_FINICIAL          TIMESTAMP(3),
    FDD_FFINAL            TIMESTAMP(3),
    FDD_DESCRIPCION       VARCHAR2(300),
    FDD_CAUSANTE_AFECTADO VARCHAR2(16),
    FDD_CODIGOELEMENTO    VARCHAR2(16),
    FDD_TIPOELEMENTO      VARCHAR2(16),
    FDD_CAUSA             VARCHAR2(50),
    FDD_FESTIMADA         DATE,
    FDD_AFECTADOS         NUMBER,
    FDD_AFECTADOS_TOTALES NUMBER
)
/


