create table QA_TTT1_REPORTE
(
    TT1_PERIODO          DATE,
    TT1_NOMBRECIRCUITO   VARCHAR2(25),
    TT1_CODIGOCIRCUITO   VARCHAR2(10),
    TT1_VOLTAJE          NUMBER,
    TT1_GRUPOCALIDAD     NUMBER(2),
    TT1_IDMERCADO        VARCHAR2(5),
    TT1_RELE_TELECONTROL NUMBER(1),
    TT1_CANT_RELES       NUMBER(1),
    TT1_ALIMENT_RADIAL   NUMBER(1),
    TT1_NORM_ABIERTO     NUMBER(1),
    TT1_LONGITUD         NUMBER,
    TT1_LATITUD          NUMBER,
    TT1_ALTITUD          NUMBER,
    TT1_PORC_PROPIEDAD   NUMBER
)
/


