create table QA_TFDDMODIFICADOS
(
    FDD_CODIGOEVENTO   VARCHAR2(10) not null,
    FDD_FINICIAL       TIMESTAMP(3),
    FDD_FFINAL         TIMESTAMP(3),
    FDD_CODIGOELEMENTO VARCHAR2(16),
    FDD_TIPOELEMENTO   VARCHAR2(16),
    FDD_CAUSA_CREG     VARCHAR2(50),
    FDD_ORIGEN         VARCHAR2(3)
)
/


