create table QA_TFDDRESUMEN_AJ
(
    FDD_TIPOCARGA          VARCHAR2(20),
    FDD_TIPOAJUSTE         NUMBER,
    FDD_CAUSA_QOS          VARCHAR2(50),
    FDD_DESCRIPCION_QOS    VARCHAR2(400),
    FDD_EXCLUSION_QOS      VARCHAR2(20),
    FDD_CAUSA_OMS          VARCHAR2(20),
    FDD_DESCRIPCION_OMS    VARCHAR2(400),
    FDD_EXCLUSION_OMS      VARCHAR2(20),
    FDD_CANTIDAD_REGISTROS NUMBER,
    FDD_CANTIDAD_EVENTOS   NUMBER,
    FDD_PERIODO_OP         DATE
)
/


