

CREATE TABLE	QA_TTC1_DIVIPOLA (
	TC1_COD_DEPARTAMENTO	NUMBER
,	TC1_DEPARTAMENTO	VARCHAR2(200)
,	TC1_COD_MUNICIPIO	NUMBER
,	TC1_MUNICIPIO	VARCHAR2(200)
,	TC1_COD_CENTRO_POBLADO	NUMBER
,	TC1_CENTRO_POBLADO	VARCHAR2(200)
,	TC1_TIPO	VARCHAR2(20)
,	TC1_INFLUENCIA_OR	NUMBER
);


