create table QA_TCBRAEN
(
    CB_PERIODO NUMBER,
    CB_CRRJ4   NUMBER,
    CB_CRRJ3   NUMBER,
    CB_CRRJ2   NUMBER,
    CB_CRRJ1   NUMBER,
    CB_CRRJ    NUMBER,
    CB_BRAENJ4 NUMBER,
    CB_BRAENJ3 NUMBER,
    CB_BRAENJ2 NUMBER,
    CB_BRAENJ1 NUMBER,
    CB_BRAENJT NUMBER,
    CB_BRAEJ4  NUMBER,
    CB_BRAEJ3  NUMBER,
    CB_BRAEJ2  NUMBER,
    CB_BRAEJ1  NUMBER,
    CB_BRAEJT  NUMBER
)
/


