create table QA_TDIVIPOLA_DANE
(
    CODIGO_DEPARTAMENTO   NUMBER,
    NOMBRE_DEPARTAMENTO   VARCHAR2(200),
    CODIGO_MUNICIPIO      NUMBER,
    NOMBRE_MUNICIPIO      VARCHAR2(200),
    CODIGO_CENTRO_POBLADO NUMBER,
    NOMBRE_CENTRO_POBLADO VARCHAR2(200),
    TIPO                  VARCHAR2(10)
)
/


