create table QA_TTT3_REPORTE
(
    TT3_PERIODO_OP     DATE,
    TT3_IUS            VARCHAR2(4),
    TT3_CLASIFICACION  NUMBER,
    TT3_IUA            VARCHAR2(20),
    TT3_FINICIAL       DATE,
    TT3_FFINAL         DATE,
    TT3_DESCRIPCION    VARCHAR2(200),
    TT3_CODIGOPROYECTO VARCHAR2(50),
    TT3_IDMERCADO      NUMBER
)
/


