create table QA_TFDDCAUSAS
(
    FDC_CAUSA_OMS     VARCHAR2(10),
    FDC_CAUSA_015     NUMBER,
    FDC_CAUSA_SSPD    NUMBER,
    FDC_DESCRIPCION   VARCHAR2(150),
    FDC_CLASIFICACION VARCHAR2(20),
    FDC_EXCLUSION     VARCHAR2(20),
    FDC_DETALLE       VARCHAR2(150),
    FDC_DEPENDENCIA   VARCHAR2(50),
    FDC_EQUIPOTRABAJO VARCHAR2(50)
)
/


