create table QA_TCS1_TEMP
(
    CS1_PERIODO_OP DATE,
    CS1_IDMERCADO  NUMBER,
    CS1_UIXTI_M    NUMBER,
    CS1_UI_M       NUMBER,
    CS1_UT_M       NUMBER,
    CS1_SAIDI_M    NUMBER,
    CS1_SAIFI_M    NUMBER,
    CS1_SAIDI      NUMBER,
    CS1_SAIFI      NUMBER,
    CS1_SAIDI_MAT  NUMBER,
    CS1_SAIFI_MAT  NUMBER,
    CS1_MAIFI_M    NUMBER,
    CS1_MAIFI      NUMBER,
    CS1_MAIFI_MAT  NUMBER,
    CS1_CAIDI_M    NUMBER,
    CS1_CAIDI      NUMBER
)
/


