create table QA_TDATACSX
(
    FDD_CODIGOEVENTO   VARCHAR2(10) not null,
    FDD_FINICIAL       DATE,
    FDD_FFINAL         DATE,
    FDD_DURACION       NUMBER,
    FDD_DURACION_AP    NUMBER,
    FDD_CODIGOELEMENTO VARCHAR2(16),
    FDD_CONTINUIDAD    VARCHAR2(2),
    FDD_USUARIOAP      VARCHAR2(2),
    FDD_EXCLUSION      VARCHAR2(20),
    FDD_CAUSA          VARCHAR2(50),
    FDD_CAUSA_CREG     VARCHAR2(50),
    FDD_CAUSA_SSPD     NUMBER
)
/


