create table QA_TT3_SEGUIMIENTO_BACK
(
    TT3_ID_DESCONEXION         NUMBER,
    TT3_BUSCADOR               VARCHAR2(50),
    TT3_SUBESTACION            VARCHAR2(50),
    TT3_FINICIO                DATE,
    TT3_FFIN                   DATE,
    TT3_DESCRIPCION            VARCHAR2(500),
    TT3_CODIGO_PROYECTO        VARCHAR2(100),
    TT3_CODIGO_PROYECTOAJS     VARCHAR2(100),
    TT3_PERIODO                NUMBER,
    TT3_SEGUIRMES              DATE,
    TT3_CL_EJECUTADA           VARCHAR2(100),
    TT3_ACTIVIDAD              NUMBER(1),
    TT3_MEDIO_PUBLICACION      VARCHAR2(100),
    TT3_FECHA_ESTIMADA_PUBLICA DATE
)
/


