


--INSERT INTO QA_TFDDRECICLER
--SELECT *
--FROM QA_TFDDREGISTRO
--WHERE FDD_FINICIAL >='01/04/2020'
--AND FDD_FINICIAL<'01/05/2020';


UPDATE QA_TFDDREGISTRO
SET FDD_PERIODO_TC1 = 202004
WHERE FDD_FINICIAL >='01/04/2020'
AND FDD_FINICIAL<'01/05/2020';

SELECT DISTINCT FDD_PERIODO_TC1
FROM QA_TFDDREGISTRO
WHERE FDD_FINICIAL >='01/04/2020'
AND FDD_FINICIAL<'01/05/2020';

--VERFICACION DE EVENTOS EXISTENTES DEL TC1 AL REGISTRO
SELECT * FROM QA_TFDDPRELIMINAR_NR WHERE FDD_CODIGOEVENTO = (
SELECT DISTINCT FDD_CODIGOEVENTO
FROM QA_TFDDPRELIMINAR_NR
MINUS
SELECT DISTINCT FDD_CODIGOEVENTO FROM QA_TFDDREGISTRO 
WHERE FDD_CODIGOEVENTO IN (SELECT DISTINCT FDD_CODIGOEVENTO
FROM QA_TFDDPRELIMINAR_NR));


SELECT * FROM QA_TFDDREGISTRO WHERE FDD_CODIGOEVENTO ='725998';


--ACTUALIZACION DE LOS REGISTROS GENERADOS CON EL PRLIMINAR NR SEGUN TC1
SELECT* FROM QA_TFDDPRELIMINAR_NR;
SET FDD_TIPOCARGA = 'AJUSTE TC1',
    FDD_TIPOAJUSTE = '1';
    
    
UPDATE QA_TFDDREGISTRO 
SET FDD_PERIODO_OP = (CASE WHEN (FDD_FFINAL IS NULL) THEN (TRUNC(FDD_FINICIAL)) ELSE(TRUNC(FDD_FFINAL)) END)
WHERE FDD_TIPOCARGA='AJUSTE TC1'
AND FDD_FINICIAL >='01/04/2020'
AND FDD_FINICIAL<'01/05/2020';;    
    
    
SELECT * FROM QA_TFDDREGISTRO 
WHERE FDD_TIPOCARGA='AJUSTE TC1';    

--EVENTOS PARA ELIMINAR POR ACTUALIZACION DEL TC1
SELECT *  FROM QA_TFDDREGISTRO 
WHERE FDD_FINICIAL >='01/04/2020'
AND FDD_FINICIAL<'01/05/2020'
AND FDD_CODIGOELEMENTO NOT IN (SELECT DISTINCT TC1_CODCONEX FROM QA_TTC1 WHERE TC1_PERIODO=202004)
;

--CAMBIO DEL TIPO AJUSTE PARA LOS QUE SALIERON DEL TC1
UPDATE QA_TFDDREGISTRO
SET FDD_TIPOAJUSTE=3 
WHERE FDD_FINICIAL >='01/04/2020'
AND FDD_FINICIAL<'01/05/2020'
AND FDD_CODIGOELEMENTO NOT IN (SELECT DISTINCT TC1_CODCONEX FROM QA_TTC1 WHERE TC1_PERIODO=202004)
;


