--*************************************CONSTTRUCCION DE SCRIPT DE EVENTO DE ALTO IMPACTO
SELECT I.MINICIAL AS FDD_CODIGOEVENTO
      ,I.FINICIAL AS FDD_FINICIAL
      ,I.FFINAL AS FDD_FFINAL
      ,M.DESCRIPTIO AS FDD_DECRIPCION
      ,'A' AS FDD_CAUSANTE_AFECTADO
      ,I.TRAFO AS FDD_CODIGOELEMENTO
      ,'1' AS FDD_TIPOELEMENTO
      ,C.FDC_CAUSA_015 AS FDD_CAUSA
      ,SYSDATE AS FDD_CIERRE_ESTIMADO
      ,CANT_USRS AS USUARIOS_AFECTADOS
FROM OMS.INTERUPC I
LEFT OUTER JOIN OMS.MANIOBRAS M ON M.CODE=I.MINICIAL
LEFT OUTER JOIN BRAE.QA_TFDDCAUSAS C ON C.FDC_CAUSA_OMS = M.CAUSA
LEFT OUTER JOIN (
                 SELECT  TC1_CODCONEX,COUNT(TC1_CODCONEX) AS CANT_USRS
                 FROM QA_TTC1 
                 WHERE TC1_PERIODO='202207'
                 GROUP BY TC1_CODCONEX
                 ) ON TC1_CODCONEX = I.TRAFO
WHERE TRUNC(FINICIAL) = '01/08/2022'
AND M.TIPO <> 'PRUEBA' 
AND M.EJECUTADO = 1
AND I.TYPEEQUIP IN ('Transformer')
AND TC1_CODCONEX IS NOT NULL
;



SELECT * FROM  BRAE.QA_TFDDREGISTRO_AI;

CREATE TABLE BRAE.QA_TFDDREGISTRO_AI(
	FDD_CODIGOEVENTO	VARCHAR2(10)
,	FDD_FINICIAL	TIMESTAMP(3)
,	FDD_FFINAL	TIMESTAMP(3)
,	FDD_DESCRIPCION	VARCHAR2(300)
,	FDD_CAUSANTE_AFECTADO	VARCHAR2(16)
,	FDD_CODIGOELEMENTO	VARCHAR2(16)
,	FDD_TIPOELEMENTO	VARCHAR2(16)
,	FDD_CAUSA	VARCHAR2(50)
,	FDD_FESTIMADA	DATE
,	FDD_AFECTADOS	NUMBER
);



ALTER TABLE QA_TFDDREGISTRO_AI
ADD FDD_AFECTADOS_TOTALES NUMBER;




--SCRIPT GENERACION DE REPORTE DE ALTO IMPACTO
    SELECT I.MINICIAL      AS FDD_CODIGOEVENTO
          ,I.FINICIAL      AS FDD_FINICIAL
          ,I.FFINAL        AS FDD_FFINAL
          ,M.DESCRIPTIO    AS FDD_DECRIPCION --DEFINIR DE DONDE SE TOME ESTA INFORMACION 
          ,'A'             AS FDD_CAUSANTE_AFECTADO
          ,TC1_IUA         AS FDD_CODIGOELEMENTO
          ,'1'             AS FDD_TIPOELEMENTO
          ,C.FDC_CAUSA_015 AS FDD_CAUSA_CREG
          ,SYSDATE         AS FDD_FESTIMADA --RECIBIR POR INTERFACE COMO DATO DE ENTRADA
          ,CANT.AFECTADOS  AS FDD_AFECTADOS
    FROM OMS.INTERUPC I
    LEFT OUTER JOIN OMS.MANIOBRAS M ON M.CODE=I.MINICIAL
    LEFT OUTER JOIN BRAE.QA_TFDDCAUSAS C ON C.FDC_CAUSA_OMS = M.CAUSA
    LEFT OUTER JOIN (
                     SELECT  TC1_CODCONEX,TC1_IUA,COUNT(TC1_CODCONEX) AS CANT_USRS
                     FROM QA_TTC1 
                     WHERE TC1_PERIODO = MAX_PERIODO_TC1
                     AND   TC1_TIPCONEX = 'T'
                     AND   TC1_CODCONEX NOT LIKE 'ALPM%'
                     GROUP BY TC1_CODCONEX, TC1_IUA
                     ) ON TC1_CODCONEX = I.TRAFO
    LEFT OUTER JOIN (
                    SELECT I.MINICIAL      AS CODIGOEVENTO
                          ,SUM(CANT_USRS)  AS AFECTADOS
                    FROM OMS.INTERUPC I
                    LEFT OUTER JOIN OMS.MANIOBRAS M ON M.CODE=I.MINICIAL
                    LEFT OUTER JOIN (
                                     SELECT  TC1_CODCONEX,COUNT(TC1_CODCONEX) AS CANT_USRS
                                     FROM QA_TTC1 
                                     WHERE TC1_PERIODO = MAX_PERIODO_TC1
                                     AND   TC1_CODCONEX NOT LIKE 'ALPM%'
                                     AND   TC1_TIPCONEX = 'T'
                                     GROUP BY TC1_CODCONEX
                                     ) ON TC1_CODCONEX = I.TRAFO
                    WHERE TRUNC(FINICIAL) = TRUNC(TO_DATE(:FECHAOPERACION,'DD/MM/YYYY')) 
                    AND M.TIPO <> 'PRUEBA' 
                    AND M.EJECUTADO = 1
                    AND I.TYPEEQUIP IN ('Transformer')
                    AND TC1_CODCONEX IS NOT NULL
                    AND (CASE WHEN(I.FFINAL IS NOT NULL) THEN(I.FFINAL - I.FINICIAL)*24
                              WHEN(I.FFINAL IS     NULL) THEN(SYSDATE  - I.FINICIAL)*24
                         END
                        ) >= 3
                    GROUP BY I.MINICIAL    
                    ) CANT ON CANT.CODIGOEVENTO =  I.MINICIAL
    WHERE TRUNC(FINICIAL) = TRUNC(TO_DATE(:FECHAOPERACION,'DD/MM/YYYY')) --
    AND M.TIPO <> 'PRUEBA' 
    AND M.EJECUTADO = 1
    AND I.TYPEEQUIP IN ('Transformer')
    AND TC1_CODCONEX IS NOT NULL
    AND CANT.AFECTADOS >= 1000 --Usrs
    AND (CASE WHEN(I.FFINAL IS NOT NULL) THEN(I.FFINAL - I.FINICIAL)*24
              WHEN(I.FFINAL IS     NULL) THEN(SYSDATE  - I.FINICIAL)*24
         END
         )>= 3 --Hrs
;


--EVITAR CICLICIDAD DE REPORTE PARA EVENTOS ABIERTOS YA REPORTADOS.
--TOMAR MAX 4 HORAS DEL DIA ANTERIOR PARA LA VISUALIZACION DE EVENTOS OCURRIDOS EN ESE LAPSO.
--REVISAR DE QUE ORIGEN TOMAR LA DESCRIPCION DEL EVENTO.