SELECT * FROM QA_TTC1 WHERE TC1_PERIODO=202102;

SELECT * FROM QA_TFDDREPORTE;

CREATE TABLE BRAE.QA_TFDDREFERENCIA(
FDD_PERIODO_OP	DATE	,
FDD_CODIGOELEMENTO	VARCHAR2(20)	,
FDD_IUA	VARCHAR2(20)	,
FDD_TIPOCONEXION	NUMBER	,
FDD_ALUMBRADO_CALP	NUMBER	,
FDD_AUTOGENERADOR	NUMBER	,
FDD_ZONA_NO_INTER	NUMBER
);

SELECT * FROM QA_TFDDREFERENCIA;


SELECT DISTINCT TO_DATE('01/02/2021','DD/MM/YYYY') AS FDD_PERIODO_OP
      ,T1.TC1_CODCONEX AS FDD_CODIGOELEMENTO
      ,T1.TC1_IUA AS FDD_IUA
      ,(CASE WHEN(T1.TC1_TIPCONEX='T') THEN(2) ELSE(1) END) AS FDD_TIPOCONEXION
      ,(CASE WHEN(T2.TC1_CODCONEX IS NOT NULL) THEN(1) ELSE(0) END) AS FDD_ALUMBRADO_CALP
      ,0 AS FDD_AUTOGENERADOR
      ,0 AS FDD_ZONA_NO_INTER
FROM QA_TTC1 T1
LEFT OUTER JOIN (
                SELECT TC1_CODCONEX
                FROM BRAE.QA_TTC1
                WHERE TC1_PERIODO=202102
                AND TC1_TC1 LIKE 'CALP%'
                GROUP BY TC1_CODCONEX
                ) T2 ON T2.TC1_CODCONEX = T1.TC1_CODCONEX
WHERE T1.TC1_PERIODO=202102
AND T1.TC1_TIPCONEX='T';

--LLENAR TABLA QA_TFDDREFERENCIA

INSERT INTO BRAE.QA_TFDDREFERENCIA
SELECT DISTINCT TO_DATE('01/02/2021','DD/MM/YYYY') AS FDD_PERIODO_OP
      ,T1.TC1_CODCONEX AS FDD_CODIGOELEMENTO
      ,T1.TC1_IUA AS FDD_IUA
      ,(CASE WHEN(T1.TC1_TIPCONEX='T') THEN(2) ELSE(1) END) AS FDD_TIPOCONEXION
      ,(CASE WHEN(T2.TC1_CODCONEX IS NOT NULL) THEN(1) ELSE(0) END) AS FDD_ALUMBRADO_CALP
      ,0 AS FDD_AUTOGENERADOR
      ,0 AS FDD_ZONA_NO_INTER
FROM QA_TTC1 T1
LEFT OUTER JOIN (
                SELECT TC1_CODCONEX
                FROM BRAE.QA_TTC1
                WHERE TC1_PERIODO=202102
                AND TC1_TC1 LIKE 'CALP%'
                GROUP BY TC1_CODCONEX
                ) T2 ON T2.TC1_CODCONEX = T1.TC1_CODCONEX
WHERE T1.TC1_PERIODO=202102
AND T1.TC1_TIPCONEX='T';

--
SELECT * 
FROM BRAE.QA_TFDDREFERENCIA;


Select fed.code, mvl.kvnom, fed.idmercado, fed.longitud, fed.latitud, fed.z
From spard.feeders fed
left outer join (select distinct fparent,kvnom 
                 from spard.mvlinsec 
                 where fparent is not null) mvl 
on mvl.fparent=fed.code;


SELECT COUNT(DISTINCT TC1_TC1) 
FROM QA_TTC1 WHERE TC1_PERIODO=202102
;


SELECT COUNT(TC1_TC1) 
FROM QA_TTC1 
WHERE TC1_PERIODO=202102
AND TC1_CODCONEX NOT LIKE 'ALPM%'
AND TC1_TIPCONEX = 'T';



SELECT * FROM QA_TFDDREGISTRO;

SELECT DISTINCT FDR_PERIODO_OP FROM QA_TFDDREPORTE_AJ;


SELECT DISTINCT FDD_PERIODO_TC1 FROM QA_TFDDREGISTRO WHERE FDD_FINICIAL>=TO_DATE('01/04/2021','DD/MM/YYYY');



SELECT (CASE WHEN(P.FDD_TIPOCARGA='XR') THEN('XR')
             WHEN(P.FDD_TIPOCARGA='MR') THEN('MR')
             WHEN(P.FDD_TIPOCARGA='TR' AND P.FDD_TIPOAJUSTE=1) THEN('AJUSTE TC1 ADD')
             WHEN(P.FDD_TIPOCARGA='TR' AND P.FDD_TIPOAJUSTE=3) THEN('AJUSTE TC1 DEL')
        END) AS TABLA
       ,P.FDD_TIPOAJUSTE
       ,R.FDD_CAUSA_CREG AS CAUSA_QOS
       ,C2.FDC_DESCRIPCION AS FDC_DESCRIPCION_QOS
       ,C2.FDC_EXCLUSION AS FDC_EXCLUSION_QOS
       ,P.FDD_CAUSA_CREG AS CAUSA_OMS
       ,C1.FDC_DESCRIPCION AS FDC_DESCRIPCION_OMS
       ,C1.FDC_EXCLUSION AS FDC_EXCLUSION_OMS
       ,COUNT(P.FDD_CODIGOELEMENTO) AS CANTIDAD_REGISTROS
       ,COUNT(DISTINCT P.FDD_CODIGOEVENTO) AS CANTIDAD_EVENTOS
FROM QA_TFDDPRELIMINAR_AJ P
LEFT OUTER JOIN QA_TFDDREGISTRO R ON R.FDD_CODIGOEVENTO||R.FDD_CODIGOELEMENTO=P.FDD_CODIGOEVENTO||P.FDD_CODIGOELEMENTO
LEFT OUTER JOIN (SELECT DISTINCT FDC_CAUSA_015, FDC_DESCRIPCION,FDC_EXCLUSION FROM  QA_TFDDCAUSAS) C1 ON C1.FDC_CAUSA_015=P.FDD_CAUSA_CREG
LEFT OUTER JOIN (SELECT DISTINCT FDC_CAUSA_015, FDC_DESCRIPCION,FDC_EXCLUSION FROM  QA_TFDDCAUSAS) C2 ON C2.FDC_CAUSA_015=R.FDD_CAUSA_CREG
GROUP BY (CASE WHEN(P.FDD_TIPOCARGA='XR') THEN('XR')
             WHEN(P.FDD_TIPOCARGA='MR') THEN('MR')
             WHEN(P.FDD_TIPOCARGA='TR' AND P.FDD_TIPOAJUSTE=1) THEN('AJUSTE TC1 ADD')
             WHEN(P.FDD_TIPOCARGA='TR' AND P.FDD_TIPOAJUSTE=3) THEN('AJUSTE TC1 DEL')
        END),R.FDD_CAUSA_CREG,P.FDD_CAUSA_CREG,C2.FDC_DESCRIPCION,C2.FDC_EXCLUSION,C1.FDC_DESCRIPCION,C1.FDC_EXCLUSION,P.FDD_TIPOAJUSTE
ORDER BY 1;



