

-- ASIGNAR CODIGOS IUA A LOS REPORTES O AL REGISTRO DE LOS MESES FEBRERO, MARZO, ABRIL


SELECT DISTINCT FDD_PERIODO_TC1 FROM QA_TFDDREGISTRO
WHERE FDD_FINICIAL >= :PERIODO
AND   FDD_FINICIAL <  ADD_MONTHS(:PERIODO,1)
;

SELECT FDD_IUA FROM QA_TFDDREGISTRO
WHERE FDD_FINICIAL >= :PERIODO
AND   FDD_FINICIAL <  ADD_MONTHS(:PERIODO,1); --61193 REGISTROS DE FEBRERO

UPDATE QA_TFDDREGISTRO T1
SET FDD_IUA = (SELECT DISTINCT TC1_IUA
               FROM QA_TTC1
               WHERE TC1_PERIODO=TO_NUMBER(TO_CHAR(:PERIODO,'YYYYMM'))
               AND   TC1_CODCONEX = T1.FDD_CODIGOELEMENTO)
WHERE FDD_FINICIAL >= :PERIODO
AND   FDD_FINICIAL <  ADD_MONTHS(:PERIODO,1)
AND   FDD_TIPOELEMENTO='Transformer';

--FEBRERO, COMPLETAR CON TT2 DE FEBRERO
SELECT DISTINCT REG.FDD_CODIGOELEMENTO, TC1.TC1_IUA
FROM QA_TFDDREGISTRO REG
LEFT OUTER JOIN (SELECT DISTINCT TC1_CODCONEX, TC1_IUA
                 FROM QA_TTC1
                 WHERE TC1_PERIODO=202002
                 UNION
                 SELECT DISTINCT TC1_CODCONEX, TC1_IUA
                 FROM QA_TTC1
                 WHERE TC1_PERIODO=202001
                ) TC1 ON TC1.TC1_CODCONEX = REG.FDD_CODIGOELEMENTO
WHERE REG.FDD_FINICIAL >= :PERIODO
AND   REG.FDD_FINICIAL <  ADD_MONTHS(:PERIODO,1)
AND   TC1.TC1_IUA IS NULL;


--------------------------------------------------------------------------------ANALISIS
--FEBRERO, COMPLETAR CON TT2 DE FEBRERO
SELECT DISTINCT REG.FDD_CODIGOELEMENTO, TC1.TC1_IUA
FROM QA_TFDDREGISTRO REG
LEFT OUTER JOIN (SELECT DISTINCT TC1_CODCONEX, TC1_IUA
                 FROM QA_TTC1
                 WHERE TC1_PERIODO=TO_NUMBER(TO_CHAR(:PERIODO,'YYYYMM'))
                 /*UNION
                 SELECT DISTINCT TC1_CODCONEX, TC1_IUA
                 FROM QA_TTC1
                 WHERE TC1_PERIODO=TO_NUMBER(TO_CHAR(:PERIODO,'YYYY')||'0'||TO_NUMBER(TO_CHAR(:PERIODO,'MM'))-1)
                 UNION
                 SELECT DISTINCT TC1_CODCONEX, TC1_IUA
                 FROM QA_TTC1
                 WHERE TC1_PERIODO=TO_NUMBER(TO_CHAR(:PERIODO,'YYYY')||'0'||TO_NUMBER(TO_CHAR(:PERIODO,'MM'))-2)*/
                ) TC1 ON TC1.TC1_CODCONEX = REG.FDD_CODIGOELEMENTO
WHERE REG.FDD_FINICIAL >= :PERIODO
AND   REG.FDD_FINICIAL <  ADD_MONTHS(:PERIODO,1)
AND   TC1.TC1_IUA IS NULL;



SELECT DISTINCT FDD_PERIODO_TC1
FROM QA_TFDDREGISTRO
WHERE FDD_FINICIAL >= :PERIODO
AND   FDD_FINICIAL <  ADD_MONTHS(:PERIODO,1);



---DESPUES DE HABER REALIZDO EL ANALISIS PROCEDEMOS A POBLAR LOS CAMPOS FDD_IUA DE LOS MES














