--EN DESARROLLO PARA QoS

-- FORMATO TT3 TRMS CONSTRUCCION Y SEGUIMIENTO AL SUI

-------------------------------------------------------------------------------

--CONSTRUCCION DE FORMATO TT3 PARA REPORTE SUI

SELECT *
FROM BRAE.QA_TT3_RESUMEN
WHERE TT3_PERIODO=2021
;

--LLAMAR LOS ALIMENTADORES A LA TABLA RESUMEN (TT3)
SELECT  R.TT3_ID_DESCONEXION,
        R.TT3_PERIODO,
        R.TT3_BUSCADOR, 
        R.TT3_SUBESTACION,
        C.IUS,
        L.TT3_LLAVE_CIRCUITO,
        TO_CHAR(R.TT3_FINICIO,'DD-MM-YYYY HH24:MI') AS TT3_FECHA_INICIO,
        TO_CHAR(R.TT3_FFIN,'DD-MM-YYYY HH24:MI') AS TT3_FECHA_FINALIZACION,
        R.TT3_DESCRIPCION,
        R.TT3_CODIGO_PROYECTO,
        R.TT3_CODIGO_PROYECTOAJS        
FROM BRAE.QA_TT3_RESUMEN R
LEFT OUTER JOIN BRAE.QA_TT3_LLAVEBUSCAR L                                                   ---LA TABLA LLAVE_BUSCADOR SIEMPRE SERÁ NECESARIA PARA DETERMINAR LAS CONDICIONES OPERATIVAS DE CADA ID_DESCONEXION 
            ON (L.TT3_LLAVE_BUSCADOR=R.TT3_BUSCADOR 
            AND L.TT3_LLAVE_PERIODO=R.TT3_PERIODO)
LEFT OUTER JOIN (SELECT DISTINCT IUS,SUBSTR(SUBESTACION,13) AS SUBESTACION                   ---SE REQUIERE DEFINIR UNA TABLA ALIMENTADA DE LOS FORMATOS BRA1 Y BRA7 QUE CONTENGAN LAS SUBESTACIONES Y LOS CIRCUITOS Y SUS CODIGOS CREG 
                 FROM BRAE.QA_CIRCUITO_SUBESTACION) C                                        ---POSIBLEMENTE INCLUIR UN CAMPO DE PERIODO PARA DISTINGUIR EL AÑO DE REPORTE DEL TT3
            ON C.SUBESTACION=R.TT3_SUBESTACION
WHERE R.TT3_PERIODO=:TT3_PERIODO_YYYY
ORDER BY R.TT3_PERIODO,R.TT3_ID_DESCONEXION, R.TT3_FINICIO, L.TT3_LLAVE_CIRCUITO
;

--LLAMAR LOS TRAFOS A LA TABLA RESUMEN (TT3)

SELECT  R.TT3_ID_DESCONEXION,
        R.TT3_PERIODO,
        R.TT3_BUSCADOR, 
        R.TT3_SUBESTACION,
        C.IUS,
        L.TT3_LLAVE_CIRCUITO,
        T1.TT1_CODIGOCIRCUITO,
        TC.TC1_CODCONEX,
        DECODE(TC.TC1_TIPCONEX,'T',2,'P',1) AS TT3_CLASIFICACION,
        TC.TC1_IUA,
        TC.USUARIOS,
        TO_CHAR(R.TT3_FINICIO,'DD-MM-YYYY HH24:MI') AS TT3_FECHA_INICIO,
        TO_CHAR(R.TT3_FFIN,'DD-MM-YYYY HH24:MI') AS TT3_FECHA_FINALIZACION,
        R.TT3_DESCRIPCION,
        R.TT3_CODIGO_PROYECTO,
        R.TT3_CODIGO_PROYECTOAJS        
FROM BRAE.QA_TT3_RESUMEN R
LEFT OUTER JOIN BRAE.QA_TT3_LLAVEBUSCAR L                                                   ---LA TABLA LLAVE_BUSCADOR SIEMPRE SERÁ NECESARIA PARA DETERMINAR LAS CONDICIONES OPERATIVAS DE CADA ID_DESCONEXION 
            ON (L.TT3_LLAVE_BUSCADOR=R.TT3_BUSCADOR 
            AND L.TT3_LLAVE_PERIODO=R.TT3_PERIODO)
LEFT OUTER JOIN (SELECT DISTINCT LPAD(IUS,4,0) AS IUS,SUBSTR(SUBESTACION,13) AS SUBESTACION                   ---SE REQUIERE DEFINIR UNA TABLA ALIMENTADA DE LOS FORMATOS BRA1 Y BRA7 QUE CONTENGAN LAS SUBESTACIONES Y LOS CIRCUITOS Y SUS CODIGOS CREG 
                 FROM BRAE.QA_CIRCUITO_SUBESTACION) C                                        ---POSIBLEMENTE INCLUIR UN CAMPO DE PERIODO PARA DISTINGUIR EL AÑO DE REPORTE DEL TT3
            ON C.SUBESTACION=R.TT3_SUBESTACION
LEFT OUTER JOIN (SELECT TT1_PERIODO, TT1_NOMBRECIRCUITO, TT1_CODIGOCIRCUITO
                 FROM BRAE.QA_TTT1_REPORTE
                 WHERE TRUNC(TT1_PERIODO)=(SELECT MAX(TRUNC(TT1_PERIODO))
                                           FROM BRAE.QA_TTT1_REPORTE)
                ) T1 
            ON T1.TT1_NOMBRECIRCUITO=L.TT3_LLAVE_CIRCUITO
LEFT OUTER JOIN (SELECT DISTINCT TC1_CODCIRC,TC1_CODCONEX,TC1_TIPCONEX,TC1_IUA,COUNT(TC1_TC1) AS USUARIOS
                 FROM BRAE.QA_TTC1
                 WHERE TC1_PERIODO=:PERIODO_TC1_YYYYMM
                 GROUP BY TC1_CODCIRC,TC1_CODCONEX,TC1_TIPCONEX,TC1_IUA) TC
            ON TC.TC1_CODCIRC=T1.TT1_CODIGOCIRCUITO

WHERE R.TT3_PERIODO=:TT3_PERIODO_YYYY
AND TC.TC1_CODCONEX IS NOT NULL
AND TC.TC1_IUA IS NOT NULL

ORDER BY R.TT3_PERIODO,R.TT3_ID_DESCONEXION, R.TT3_FINICIO, L.TT3_LLAVE_CIRCUITO
;
            
---FORMATO TT3 ESTRUCTURA VERSION SUI (TT3)


SELECT  C.IUS AS IUS,
        DECODE(TC.TC1_TIPCONEX,'T',2,'P',1) AS "Clasificacion",
        TC.TC1_IUA AS  "Codigo Circuito o Trafo",
        TO_CHAR(R.TT3_FINICIO,'DD-MM-YYYY HH24:MI') AS "Fecha Inicio Afectacion",
        TO_CHAR(R.TT3_FFIN,'DD-MM-YYYY HH24:MI') AS "Fecha Finalizacion Afectacion",
        R.TT3_DESCRIPCION AS "Descripcion del Trabajo",
        R.TT3_CODIGO_PROYECTOAJS AS "Codigo Proyecto",
        161 AS "ID Mercado"
        
FROM BRAE.QA_TT3_RESUMEN R
LEFT OUTER JOIN BRAE.QA_TT3_LLAVEBUSCAR L                                                   ---LA TABLA LLAVE_BUSCADOR SIEMPRE SERÁ NECESARIA PARA DETERMINAR LAS CONDICIONES OPERATIVAS DE CADA ID_DESCONEXION 
            ON (L.TT3_LLAVE_BUSCADOR=R.TT3_BUSCADOR 
            AND L.TT3_LLAVE_PERIODO=R.TT3_PERIODO)
LEFT OUTER JOIN (SELECT DISTINCT LPAD(IUS,4,0) AS IUS,SUBSTR(SUBESTACION,13) AS SUBESTACION                   ---SE REQUIERE DEFINIR UNA TABLA ALIMENTADA DE LOS FORMATOS BRA1 Y BRA7 QUE CONTENGAN LAS SUBESTACIONES Y LOS CIRCUITOS Y SUS CODIGOS CREG 
                 FROM BRAE.QA_CIRCUITO_SUBESTACION) C                                        ---POSIBLEMENTE INCLUIR UN CAMPO DE PERIODO PARA DISTINGUIR EL AÑO DE REPORTE DEL TT3
            ON C.SUBESTACION=R.TT3_SUBESTACION
LEFT OUTER JOIN (SELECT TT1_PERIODO, TT1_NOMBRECIRCUITO, TT1_CODIGOCIRCUITO
                 FROM BRAE.QA_TTT1_REPORTE
                 WHERE TRUNC(TT1_PERIODO)=(SELECT MAX(TRUNC(TT1_PERIODO))
                                           FROM BRAE.QA_TTT1_REPORTE)
                ) T1 
            ON T1.TT1_NOMBRECIRCUITO=L.TT3_LLAVE_CIRCUITO
LEFT OUTER JOIN (SELECT DISTINCT TC1_CODCIRC,TC1_CODCONEX,TC1_TIPCONEX,TC1_IUA,COUNT(TC1_TC1) AS USUARIOS
                 FROM BRAE.QA_TTC1
                 WHERE TC1_PERIODO=:PERIODO_TC1_YYYYMM
                 GROUP BY TC1_CODCIRC,TC1_CODCONEX,TC1_TIPCONEX,TC1_IUA) TC
            ON TC.TC1_CODCIRC=T1.TT1_CODIGOCIRCUITO

WHERE R.TT3_PERIODO=:TT3_PERIODO_YYYY
AND TC.TC1_CODCONEX IS NOT NULL
AND TC.TC1_IUA IS NOT NULL

ORDER BY R.TT3_PERIODO,R.TT3_ID_DESCONEXION, R.TT3_FINICIO, L.TT3_LLAVE_CIRCUITO
;


----------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------
---SEGUIMIENTO TT3 CONFIRMACION 8 DIAS HABILES ANTES  TT11 ----

--VEMOS LAS TABLAS
SELECT *
FROM BRAE.QA_TT3_RESUMEN
WHERE TT3_PERIODO=2021

;
SELECT *
FROM BRAE.QA_TT3_SEGUIMIENTO
WHERE TT3_PERIODO=2021
;
--HACEMOS UNOS UPDATES SOBRE LA TABLA DE SEGUI,IENTO PARA ACTUALIZAR TIEMPOS DE CONFIRMACION SEGÚN EL NUEVO TT3
/*
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='05/02/2021 04:00:00',TT3_FFIN='05/02/2021 23:59:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=1 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=2,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='30/01/2021' WHERE TT3_ID_DESCONEXION=1 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/02/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='22/02/2021 04:00:00',TT3_FFIN='22/02/2021 23:59:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=3 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=2,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='16/02/2021' WHERE TT3_ID_DESCONEXION=3 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/02/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='26/02/2021 04:00:00',TT3_FFIN='26/02/2021 23:59:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=4 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=2,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='19/02/2021' WHERE TT3_ID_DESCONEXION=4 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/02/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='19/04/2021 04:00:00',TT3_FFIN='19/04/2021 23:59:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=5 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='13/04/2021' WHERE TT3_ID_DESCONEXION=5 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/04/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='23/04/2021 04:00:00',TT3_FFIN='23/04/2021 23:59:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=6 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='17/04/2021' WHERE TT3_ID_DESCONEXION=6 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/04/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='14/04/2021 04:00:00',TT3_FFIN='14/04/2021 23:59:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=7 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=2,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='08/04/2021' WHERE TT3_ID_DESCONEXION=7 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/04/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='15/04/2021 04:00:00',TT3_FFIN='15/04/2021 23:59:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=8 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=2,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='08/04/2021' WHERE TT3_ID_DESCONEXION=8 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/04/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='24/04/2021 04:00:00',TT3_FFIN='24/04/2021 23:59:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=9 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='17/04/2021' WHERE TT3_ID_DESCONEXION=9 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/04/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='25/04/2021 04:00:00',TT3_FFIN='25/04/2021 23:59:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=10 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='17/04/2021' WHERE TT3_ID_DESCONEXION=10 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/04/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='12/08/2021 07:00:00',TT3_FFIN='12/08/2021 09:00:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=14 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='08/08/2021' WHERE TT3_ID_DESCONEXION=14 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/08/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='13/08/2021 15:30:00',TT3_FFIN='13/08/2021 17:30:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=15 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='08/08/2021' WHERE TT3_ID_DESCONEXION=15 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/08/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='01/08/2021 15:30:00',TT3_FFIN='01/08/2021 17:30:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=27 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='28/07/2021' WHERE TT3_ID_DESCONEXION=27 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/08/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='07/08/2021 07:00:00',TT3_FFIN='07/08/2021 09:00:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=30 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='03/08/2021' WHERE TT3_ID_DESCONEXION=30 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/08/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='08/08/2021 20:00:00',TT3_FFIN='08/08/2021 22:00:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=31 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='03/08/2021' WHERE TT3_ID_DESCONEXION=31 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/08/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='23/06/2021 07:00:00',TT3_FFIN='23/06/2021 17:30:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=12 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=2,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='17/06/2021' WHERE TT3_ID_DESCONEXION=12 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/06/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='12/06/2021 04:00:00',TT3_FFIN='12/06/2021 23:59:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=17 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='06/06/2021' WHERE TT3_ID_DESCONEXION=17 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/06/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='13/06/2021 04:00:00',TT3_FFIN='13/06/2021 23:59:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=18 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='06/06/2021' WHERE TT3_ID_DESCONEXION=18 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/06/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='19/06/2021 07:00:00',TT3_FFIN='19/06/2021 17:30:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=21 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='13/06/2021' WHERE TT3_ID_DESCONEXION=21 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/06/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='20/06/2021 15:30:00',TT3_FFIN='20/06/2021 17:30:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=22 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='13/06/2021' WHERE TT3_ID_DESCONEXION=22 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/06/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='03/06/2021 04:00:00',TT3_FFIN='03/06/2021 23:59:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=23 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='28/05/2021' WHERE TT3_ID_DESCONEXION=23 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/06/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='26/06/2021 04:00:00',TT3_FFIN='26/06/2021 23:59:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=24 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='20/06/2021' WHERE TT3_ID_DESCONEXION=24 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/06/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='27/06/2021 04:00:00',TT3_FFIN='27/06/2021 23:59:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=25 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='20/06/2021' WHERE TT3_ID_DESCONEXION=25 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/06/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='23/05/2021 04:00:00',TT3_FFIN='23/05/2021 23:59:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=82 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='17/05/2021' WHERE TT3_ID_DESCONEXION=82 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/05/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='08/05/2021 04:00:00',TT3_FFIN='08/05/2021 23:59:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=9 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='01/05/2021' WHERE TT3_ID_DESCONEXION=9 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/05/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='05/03/2021 04:00:00',TT3_FFIN='05/03/2021 23:59:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=2 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=2,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='27/02/2021' WHERE TT3_ID_DESCONEXION=2 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/03/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='09/03/2021 04:00:00',TT3_FFIN='09/03/2021 23:59:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=5 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='03/03/2021' WHERE TT3_ID_DESCONEXION=5 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/03/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='12/03/2021 04:00:00',TT3_FFIN='12/03/2021 23:59:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=6 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='06/03/2021' WHERE TT3_ID_DESCONEXION=6 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/03/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='09/05/2021 04:00:00',TT3_FFIN='09/05/2021 23:59:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=10 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='03/05/2021' WHERE TT3_ID_DESCONEXION=10 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/05/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='02/05/2021 04:00:00',TT3_FFIN='03/05/2021 12:00:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=11 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=2,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='25/04/2021' WHERE TT3_ID_DESCONEXION=11 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/05/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='12/05/2021 07:00:00',TT3_FFIN='12/05/2021 17:30:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=12 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=2,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='06/05/2021' WHERE TT3_ID_DESCONEXION=12 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/05/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='25/05/2021 04:00:00',TT3_FFIN='25/05/2021 23:59:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=13 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='19/05/2021' WHERE TT3_ID_DESCONEXION=13 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/05/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='27/05/2021 07:00:00',TT3_FFIN='27/05/2021 09:00:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=14 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='21/05/2021' WHERE TT3_ID_DESCONEXION=14 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/05/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='28/05/2021 15:30:00',TT3_FFIN='28/05/2021 17:30:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=15 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='21/05/2021' WHERE TT3_ID_DESCONEXION=15 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/05/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='14/05/2021 04:00:00',TT3_FFIN='14/05/2021 23:59:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=23 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='08/05/2021' WHERE TT3_ID_DESCONEXION=23 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/05/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='01/07/2021 07:00:00',TT3_FFIN='01/07/2021 17:30:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=12 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=2,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='25/06/2021' WHERE TT3_ID_DESCONEXION=12 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/07/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='07/07/2021 07:00:00',TT3_FFIN='07/07/2021 09:00:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=19 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='01/07/2021' WHERE TT3_ID_DESCONEXION=19 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/07/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='08/07/2021 07:00:00',TT3_FFIN='08/07/2021 17:30:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=20 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='01/07/2021' WHERE TT3_ID_DESCONEXION=20 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/07/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='31/07/2021 07:00:00',TT3_FFIN='31/07/2021 17:30:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=26 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='25/07/2021' WHERE TT3_ID_DESCONEXION=26 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/07/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='26/09/2021 04:00:00',TT3_FFIN='26/09/2021 23:59:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=82 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='22/09/2021' WHERE TT3_ID_DESCONEXION=82 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/09/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='22/07/2021 07:00:00',TT3_FFIN='22/07/2021 17:30:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=28 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=2,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='16/07/2021' WHERE TT3_ID_DESCONEXION=28 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/07/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='28/07/2021 07:00:00',TT3_FFIN='28/07/2021 17:30:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=29 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='22/07/2021' WHERE TT3_ID_DESCONEXION=29 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/07/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='01/07/2021 07:00:00',TT3_FFIN='01/07/2021 17:30:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=21 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='25/06/2021' WHERE TT3_ID_DESCONEXION=21 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/07/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='02/07/2021 15:30:00',TT3_FFIN='02/07/2021 17:30:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=22 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=1,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='25/06/2021' WHERE TT3_ID_DESCONEXION=22 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/07/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='29/09/2021 04:00:00',TT3_FFIN='29/09/2021 23:59:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=33 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=2,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='25/09/2021' WHERE TT3_ID_DESCONEXION=33 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/09/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_FINICIO='01/09/2021 04:00:00',TT3_FFIN='01/09/2021 23:59:00',TT3_DESCRIPCION=(SELECT TT3_DESCRIPCION FROM BRAE.QA_TT3_RESUMEN WHERE TT3_ID_DESCONEXION=61 AND TT3_PERIODO=2021),TT3_ACTIVIDAD=2,TT3_MEDIO_PUBLICACION='REDES SOCIALES OFICIALES',TT3_FECHA_ESTIMADA_PUBLICA='28/08/2021' WHERE TT3_ID_DESCONEXION=61 AND TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/09/2021';
*/
--commit;

  



--RESTAR DE LA TABLA RESUMEN LAS CONSIGNACIONES DE LA TABLA SEGUIMIENTO QUE ESTÁN EJECUTADAS PARA VER LAS QUE FALTAN POR EJECUTAR
---SE PUEDE CONCATENAR CON EL PERIODO PARA NO CAUSAR AMBIGUEDAD O CONFUSION CON EL ID

SELECT * 
FROM BRAE.QA_TT3_RESUMEN R
WHERE TT3_ID_DESCONEXION IN (SELECT TT3_ID_DESCONEXION FROM BRAE.QA_TT3_RESUMEN WHERE TO_CHAR(TT3_FINICIO,'DD/MM/YYYY') LIKE ('%/')||:TT3_PERIODO_YYYY
                             MINUS
                             SELECT TT3_ID_DESCONEXION FROM BRAE.QA_TT3_SEGUIMIENTO WHERE TO_CHAR(TT3_FINICIO,'DD/MM/YYYY') LIKE ('%/')||:TT3_PERIODO_YYYY AND TT3_CL_EJECUTADA IS NOT NULL
                             )
AND R.TT3_PERIODO=:TT3_PERIODO_YYYY
ORDER BY R.TT3_PERIODO,R.TT3_ID_DESCONEXION,R.TT3_FINICIO
;
 
--INSERTAR EN LA TABLA SEGUIMIENTO LOS ID DE LAS CONSIGNACIONES QUE SE CONFIRMARAN PARA EL MES CORRESPONDIENTE Y POBLAR EL DATO TT3_SEGUIR_MES CON EL MES DE SEGUIMIENTO

INSERT INTO BRAE.QA_TT3_SEGUIMIENTO
SELECT  R.TT3_ID_DESCONEXION,
        R.TT3_BUSCADOR,
        R.TT3_SUBESTACION,
        R.TT3_FINICIO,
        R.TT3_FFIN,
        R.TT3_DESCRIPCION,
        R.TT3_CODIGO_PROYECTO,
        R.TT3_CODIGO_PROYECTOAJS,
        R.TT3_PERIODO,
        '01/12/2021' AS TT3_SEGUIRMES,--EDITAR AQUI EL MES DE SEGUIMIENTO
        NULL AS TT3_CL_EJECUTADA,
        R.TT3_ACTIVIDAD,
        'REDES SOCIALES OFICIALES' AS TT3_MEDIO_PUBLICACION,
        NULL AS TT3_FECHA_ESTIMADA_PUBLICA        
FROM BRAE.QA_TT3_RESUMEN R
WHERE R.TT3_ID_DESCONEXION IN ('45'	,'46'	,'58'	,'59'	,'36'	,'37'	,'44'	,'47'	,'50'	,'32'	,'62'	,'63'	,'64'	,'65'	,'66'	,'67'	,'70'	,'71'	,'73'	,'74'	,'75'	,'80'	,'78'	,'81') --ESTOS SON LOS ID QUE SE CONFIRMAN PARA NOVIEMBRE
AND R.TT3_PERIODO=:TT3_PERIODO_YYYY
;

SELECT * FROM BRAE.QA_TT3_SEGUIMIENTO
WHERE TT3_SEGUIRMES='01/12/2021';

--24 filas insertadas para DICIEMBRE 2021

--COMMIT;

--visalizamos los valores insertados en la tabla de seguimiento
SELECT *
FROM BRAE.QA_TT3_SEGUIMIENTO
WHERE TT3_PERIODO=2021
AND TT3_ID_DESCONEXION IN ('45'	,'46'	,'58'	,'59'	,'36'	,'37'	,'44'	,'47'	,'50'	,'32'	,'62'	,'63'	,'64'	,'65'	,'66'	,'67'	,'70'	,'71'	,'73'	,'74'	,'75'	,'80'	,'78'	,'81') --ESTOS SON LOS ID QUE SE CONFIRMAN PARA NOVIEMBRE
AND TT3_SEGUIRMES=:TT3_SEGUIR_MES_DD_MM_YYYY
;


--EDITAR EN CASO DE SER NECESARIO LOS VALORES DE FECHA Y HORA DE EJECUCION CONFIRMADA Y LA FECHA DE PUBLICACION PARA LOS ID SELECCIONADOS EN EL MES CORRESPONDIENTE
--PARA NOVIEMBRE SE INSERTARON LOS ID: ('61',	'38',	'39',	'40',	'41',	'42', '66')  Y SE MODIFICA LA FECHA PARA TODOS
--SE PUEDE HACER POR LA DATA EN LA APLICACION O A TRAVES DE CODIGO USANDO UPDATE


UPDATE BRAE.QA_TT3_SEGUIMIENTO 
SET TT3_FINICIO='13/12/2021 04:00:00'
   ,TT3_FFIN   ='13/12/2021 23:59:00'
   ,TT3_FECHA_ESTIMADA_PUBLICA='02/12/2021 00:00:00' 
   ,TT3_MEDIO_PUBLICACION='MENSAJE DE TEXTO Y/O CORREO ELECTRONICO Y/O COMUNICACION ESCRITA'
WHERE TT3_PERIODO=2021 
  AND TT3_SEGUIRMES='01/12/2021' 
  AND TT3_ID_DESCONEXION=32;

UPDATE BRAE.QA_TT3_SEGUIMIENTO 
SET TT3_FINICIO='02/12/2021 04:00:00'
   ,TT3_FFIN   ='02/12/2021 12:00:00'
   ,TT3_FECHA_ESTIMADA_PUBLICA='24/11/2021 00:00:00' 
   ,TT3_MEDIO_PUBLICACION='MENSAJE DE TEXTO Y/O CORREO ELECTRONICO Y/O COMUNICACION ESCRITA'
WHERE TT3_PERIODO=2021 
  AND TT3_SEGUIRMES='01/12/2021' 
  AND TT3_ID_DESCONEXION=36;
  
UPDATE BRAE.QA_TT3_SEGUIMIENTO 
SET TT3_FINICIO='02/12/2021 12:01:00'
   ,TT3_FFIN   ='02/12/2021 23:59:00'
   ,TT3_FECHA_ESTIMADA_PUBLICA='24/11/2021 00:00:00' 
   ,TT3_MEDIO_PUBLICACION='MENSAJE DE TEXTO Y/O CORREO ELECTRONICO Y/O COMUNICACION ESCRITA'
WHERE TT3_PERIODO=2021 
  AND TT3_SEGUIRMES='01/12/2021' 
  AND TT3_ID_DESCONEXION=37;
  
  
UPDATE BRAE.QA_TT3_SEGUIMIENTO 
SET TT3_FINICIO='03/12/2021 04:00:00'
   ,TT3_FFIN   ='03/12/2021 23:59:00'
   ,TT3_FECHA_ESTIMADA_PUBLICA='25/11/2021 00:00:00' 
   ,TT3_MEDIO_PUBLICACION='MENSAJE DE TEXTO Y/O CORREO ELECTRONICO Y/O COMUNICACION ESCRITA'
WHERE TT3_PERIODO=2021 
  AND TT3_SEGUIRMES='01/12/2021' 
  AND TT3_ID_DESCONEXION=44;
  
  
UPDATE BRAE.QA_TT3_SEGUIMIENTO 
SET TT3_FINICIO='29/12/2021 04:00:00'
   ,TT3_FFIN   ='29/12/2021 23:59:00'
   ,TT3_FECHA_ESTIMADA_PUBLICA='21/12/2021 00:00:00' 
   ,TT3_MEDIO_PUBLICACION='MENSAJE DE TEXTO Y/O CORREO ELECTRONICO Y/O COMUNICACION ESCRITA'
WHERE TT3_PERIODO=2021 
  AND TT3_SEGUIRMES='01/12/2021' 
  AND TT3_ID_DESCONEXION=45;
    
  
UPDATE BRAE.QA_TT3_SEGUIMIENTO 
SET TT3_FINICIO='05/12/2021 04:00:00'
   ,TT3_FFIN   ='05/12/2021 23:59:00'
   ,TT3_FECHA_ESTIMADA_PUBLICA='29/11/2021 00:00:00' 
   ,TT3_MEDIO_PUBLICACION='MENSAJE DE TEXTO Y/O CORREO ELECTRONICO Y/O COMUNICACION ESCRITA'
WHERE TT3_PERIODO=2021 
  AND TT3_SEGUIRMES='01/12/2021' 
  AND TT3_ID_DESCONEXION=46;


UPDATE BRAE.QA_TT3_SEGUIMIENTO 
SET TT3_FINICIO='13/12/2021 04:00:00'
   ,TT3_FFIN   ='13/12/2021 23:59:00'
   ,TT3_FECHA_ESTIMADA_PUBLICA='03/12/2021 00:00:00' 
   ,TT3_MEDIO_PUBLICACION='MENSAJE DE TEXTO Y/O CORREO ELECTRONICO Y/O COMUNICACION ESCRITA'
WHERE TT3_PERIODO=2021 
  AND TT3_SEGUIRMES='01/12/2021' 
  AND TT3_ID_DESCONEXION=47;
  
  
UPDATE BRAE.QA_TT3_SEGUIMIENTO 
SET TT3_FINICIO='06/12/2021 04:00:00'
   ,TT3_FFIN   ='06/12/2021 23:59:00'
   ,TT3_FECHA_ESTIMADA_PUBLICA='29/11/2021 00:00:00' 
   ,TT3_MEDIO_PUBLICACION='MENSAJE DE TEXTO Y/O CORREO ELECTRONICO Y/O COMUNICACION ESCRITA'
WHERE TT3_PERIODO=2021 
  AND TT3_SEGUIRMES='01/12/2021' 
  AND TT3_ID_DESCONEXION=50;

UPDATE BRAE.QA_TT3_SEGUIMIENTO 
SET TT3_FINICIO='02/12/2021 04:00:00'
   ,TT3_FFIN   ='02/12/2021 23:59:00'
   ,TT3_FECHA_ESTIMADA_PUBLICA='24/11/2021 00:00:00' 
   ,TT3_MEDIO_PUBLICACION='MENSAJE DE TEXTO Y/O CORREO ELECTRONICO Y/O COMUNICACION ESCRITA'
WHERE TT3_PERIODO=2021 
  AND TT3_SEGUIRMES='01/12/2021' 
  AND TT3_ID_DESCONEXION=74;

UPDATE BRAE.QA_TT3_SEGUIMIENTO 
SET TT3_FINICIO='17/12/2021 04:00:00'
   ,TT3_FFIN   ='17/12/2021 23:59:00'
   ,TT3_FECHA_ESTIMADA_PUBLICA='10/12/2021 00:00:00' 
   ,TT3_MEDIO_PUBLICACION='MENSAJE DE TEXTO Y/O CORREO ELECTRONICO Y/O COMUNICACION ESCRITA'
WHERE TT3_PERIODO=2021 
  AND TT3_SEGUIRMES='01/12/2021' 
  AND TT3_ID_DESCONEXION=75;

UPDATE BRAE.QA_TT3_SEGUIMIENTO 
SET TT3_FINICIO='27/12/2021 04:00:00'
   ,TT3_FFIN   ='27/12/2021 23:59:00'
   ,TT3_FECHA_ESTIMADA_PUBLICA='20/12/2021 00:00:00' 
   ,TT3_MEDIO_PUBLICACION='MENSAJE DE TEXTO Y/O CORREO ELECTRONICO Y/O COMUNICACION ESCRITA'
WHERE TT3_PERIODO=2021 
  AND TT3_SEGUIRMES='01/12/2021' 
  AND TT3_ID_DESCONEXION=78;

UPDATE BRAE.QA_TT3_SEGUIMIENTO 
SET TT3_FINICIO='28/12/2021 04:00:00'
   ,TT3_FFIN   ='28/12/2021 23:59:00'
   ,TT3_FECHA_ESTIMADA_PUBLICA='21/12/2021 00:00:00' 
   ,TT3_MEDIO_PUBLICACION='MENSAJE DE TEXTO Y/O CORREO ELECTRONICO Y/O COMUNICACION ESCRITA'
WHERE TT3_PERIODO=2021 
  AND TT3_SEGUIRMES='01/12/2021' 
  AND TT3_ID_DESCONEXION=80;
  
UPDATE BRAE.QA_TT3_SEGUIMIENTO 
SET TT3_FINICIO='28/12/2021 04:00:00'
   ,TT3_FFIN   ='28/12/2021 23:59:00'
   ,TT3_FECHA_ESTIMADA_PUBLICA='21/12/2021 00:00:00' 
   ,TT3_MEDIO_PUBLICACION='MENSAJE DE TEXTO Y/O CORREO ELECTRONICO Y/O COMUNICACION ESCRITA'
WHERE TT3_PERIODO=2021 
  AND TT3_SEGUIRMES='01/12/2021' 
  AND TT3_ID_DESCONEXION=81;

UPDATE BRAE.QA_TT3_SEGUIMIENTO 
SET TT3_FINICIO='04/12/2021 04:00:00'
   ,TT3_FFIN   ='04/12/2021 12:00:00'
   ,TT3_FECHA_ESTIMADA_PUBLICA='26/11/2021 00:00:00' 
   ,TT3_MEDIO_PUBLICACION='MENSAJE DE TEXTO Y/O CORREO ELECTRONICO Y/O COMUNICACION ESCRITA'
WHERE TT3_PERIODO=2021 
  AND TT3_SEGUIRMES='01/12/2021' 
  AND TT3_ID_DESCONEXION=58;


UPDATE BRAE.QA_TT3_SEGUIMIENTO 
SET TT3_FINICIO='04/12/2021 12:01:00'
   ,TT3_FFIN   ='04/12/2021 23:59:00'
   ,TT3_FECHA_ESTIMADA_PUBLICA='26/11/2021 00:00:00' 
   ,TT3_MEDIO_PUBLICACION='MENSAJE DE TEXTO Y/O CORREO ELECTRONICO Y/O COMUNICACION ESCRITA'
WHERE TT3_PERIODO=2021 
  AND TT3_SEGUIRMES='01/12/2021' 
  AND TT3_ID_DESCONEXION=59;
  

UPDATE BRAE.QA_TT3_SEGUIMIENTO 
SET TT3_FINICIO='28/12/2021 04:00:00'
   ,TT3_FFIN   ='28/12/2021 23:59:00'
   ,TT3_FECHA_ESTIMADA_PUBLICA='20/12/2021 00:00:00' 
   ,TT3_MEDIO_PUBLICACION='MENSAJE DE TEXTO Y/O CORREO ELECTRONICO Y/O COMUNICACION ESCRITA'
WHERE TT3_PERIODO=2021 
  AND TT3_SEGUIRMES='01/12/2021' 
  AND TT3_ID_DESCONEXION=62;
  
UPDATE BRAE.QA_TT3_SEGUIMIENTO 
SET TT3_FINICIO='01/12/2021 04:00:00'
   ,TT3_FFIN   ='01/12/2021 23:59:00'
   ,TT3_FECHA_ESTIMADA_PUBLICA='23/11/2021 00:00:00' 
   ,TT3_MEDIO_PUBLICACION='MENSAJE DE TEXTO Y/O CORREO ELECTRONICO Y/O COMUNICACION ESCRITA'
WHERE TT3_PERIODO=2021 
  AND TT3_SEGUIRMES='01/12/2021' 
  AND TT3_ID_DESCONEXION=63;
  
UPDATE BRAE.QA_TT3_SEGUIMIENTO 
SET TT3_FINICIO='01/12/2021 04:00:00'
   ,TT3_FFIN   ='01/12/2021 23:59:00'
   ,TT3_FECHA_ESTIMADA_PUBLICA='23/11/2021 00:00:00' 
   ,TT3_MEDIO_PUBLICACION='MENSAJE DE TEXTO Y/O CORREO ELECTRONICO Y/O COMUNICACION ESCRITA'
WHERE TT3_PERIODO=2021 
  AND TT3_SEGUIRMES='01/12/2021' 
  AND TT3_ID_DESCONEXION=64;

  
UPDATE BRAE.QA_TT3_SEGUIMIENTO 
SET TT3_FINICIO='10/12/2021 04:00:00'
   ,TT3_FFIN   ='10/12/2021 23:59:00'
   ,TT3_FECHA_ESTIMADA_PUBLICA='01/12/2021 00:00:00' 
   ,TT3_MEDIO_PUBLICACION='MENSAJE DE TEXTO Y/O CORREO ELECTRONICO Y/O COMUNICACION ESCRITA'
WHERE TT3_PERIODO=2021 
  AND TT3_SEGUIRMES='01/12/2021' 
  AND TT3_ID_DESCONEXION=65;
  

UPDATE BRAE.QA_TT3_SEGUIMIENTO 
SET TT3_FINICIO='28/12/2021 04:00:00'
   ,TT3_FFIN   ='28/12/2021 23:59:00'
   ,TT3_FECHA_ESTIMADA_PUBLICA='20/12/2021 00:00:00' 
   ,TT3_MEDIO_PUBLICACION='MENSAJE DE TEXTO Y/O CORREO ELECTRONICO Y/O COMUNICACION ESCRITA'
WHERE TT3_PERIODO=2021 
  AND TT3_SEGUIRMES='01/12/2021' 
  AND TT3_ID_DESCONEXION=66;
  

UPDATE BRAE.QA_TT3_SEGUIMIENTO 
SET TT3_FINICIO='17/12/2021 04:00:00'
   ,TT3_FFIN   ='17/12/2021 23:59:00'
   ,TT3_FECHA_ESTIMADA_PUBLICA='09/12/2021 00:00:00' 
   ,TT3_MEDIO_PUBLICACION='MENSAJE DE TEXTO Y/O CORREO ELECTRONICO Y/O COMUNICACION ESCRITA'
WHERE TT3_PERIODO=2021 
  AND TT3_SEGUIRMES='01/12/2021' 
  AND TT3_ID_DESCONEXION=67;
  

UPDATE BRAE.QA_TT3_SEGUIMIENTO 
SET TT3_FINICIO='21/12/2021 04:00:00'
   ,TT3_FFIN   ='21/12/2021 23:59:00'
   ,TT3_FECHA_ESTIMADA_PUBLICA='13/12/2021 00:00:00' 
   ,TT3_MEDIO_PUBLICACION='MENSAJE DE TEXTO Y/O CORREO ELECTRONICO Y/O COMUNICACION ESCRITA'
WHERE TT3_PERIODO=2021 
  AND TT3_SEGUIRMES='01/12/2021' 
  AND TT3_ID_DESCONEXION=70;
  
  
UPDATE BRAE.QA_TT3_SEGUIMIENTO 
SET TT3_FINICIO='01/12/2021 04:00:00'
   ,TT3_FFIN   ='01/12/2021 23:59:00'
   ,TT3_FECHA_ESTIMADA_PUBLICA='23/11/2021 00:00:00' 
   ,TT3_MEDIO_PUBLICACION='MENSAJE DE TEXTO Y/O CORREO ELECTRONICO Y/O COMUNICACION ESCRITA'
WHERE TT3_PERIODO=2021 
  AND TT3_SEGUIRMES='01/12/2021' 
  AND TT3_ID_DESCONEXION=71;
  
UPDATE BRAE.QA_TT3_SEGUIMIENTO 
SET TT3_FINICIO='04/12/2021 04:00:00'
   ,TT3_FFIN   ='04/12/2021 23:59:00'
   ,TT3_FECHA_ESTIMADA_PUBLICA='26/11/2021 00:00:00' 
   ,TT3_MEDIO_PUBLICACION='MENSAJE DE TEXTO Y/O CORREO ELECTRONICO Y/O COMUNICACION ESCRITA'
WHERE TT3_PERIODO=2021 
  AND TT3_SEGUIRMES='01/12/2021' 
  AND TT3_ID_DESCONEXION=73;
  
  
--COMMIT;


--VER COMO VA QUEDANDO LA TABLA DE SEGUIMIENTO PARA EL AÑO EVALUADO Y EL MES A CONFIRMAR

SELECT * 
FROM BRAE.QA_TT3_SEGUIMIENTO
WHERE TO_CHAR(TT3_FINICIO,'DD/MM/YYYY') LIKE ('%/')||:TT3_PERIODO_YYYY
AND TT3_SEGUIRMES=:MES_SEGU_01_MM_YYYY
ORDER BY TT3_SEGUIRMES,TT3_FINICIO,TT3_ID_DESCONEXION
;
--ESTOS SON LOS ID CONFIRMADOS PARA DICIEMBRE TT3_ID_DESCONEXION IN ('45'	,'46'	,'58'	,'59'	,'36'	,'37'	,'44'	,'47'	,'50'	,'32'	,'62'	,'63'	,'64'	,'65'	,'66'	,'67'	,'70'	,'71'	,'73'	,'74'	,'75'	,'80'	,'78'	,'81')
SELECT * 
FROM BRAE.QA_TT3_SEGUIMIENTO R
WHERE R.TT3_PERIODO=SUBSTR(:MES_SEGU_01_MM_YYYY,7)
AND R.TT3_SEGUIRMES=:MES_SEGU_01_MM_YYYY
ORDER BY TT3_SEGUIRMES,TT3_FINICIO,TT3_ID_DESCONEXION
;
--LLAMAR LOS ALIMENTADORES A LA TABLA SEGUIMIENTO (8 ANTES)
SELECT  R.TT3_ID_DESCONEXION,
        R.TT3_PERIODO,
        TO_CHAR(R.TT3_SEGUIRMES,'DD/MM/YYYY') AS TT3_SEGUIRMES,
        R.TT3_BUSCADOR, 
        R.TT3_SUBESTACION,
        C.IUS,
        L.TT3_LLAVE_CIRCUITO,
        TO_CHAR(R.TT3_FINICIO,'DD-MM-YYYY HH24:MI') AS TT3_FECHA_INICIO,
        TO_CHAR(R.TT3_FFIN,'DD-MM-YYYY HH24:MI') AS TT3_FECHA_FINALIZACION,
        R.TT3_DESCRIPCION,
        R.TT3_CODIGO_PROYECTO,
        R.TT3_CODIGO_PROYECTOAJS,        
        R.TT3_CL_EJECUTADA,
        R.TT3_ACTIVIDAD,
        R.TT3_MEDIO_PUBLICACION,
        R.TT3_FECHA_ESTIMADA_PUBLICA
FROM BRAE.QA_TT3_SEGUIMIENTO R
LEFT OUTER JOIN BRAE.QA_TT3_LLAVEBUSCAR L 
            ON (L.TT3_LLAVE_BUSCADOR=R.TT3_BUSCADOR 
            AND L.TT3_LLAVE_PERIODO=R.TT3_PERIODO)
LEFT OUTER JOIN (SELECT DISTINCT IUS,SUBSTR(SUBESTACION,13) AS SUBESTACION 
                 FROM BRAE.QA_CIRCUITO_SUBESTACION) C
            ON C.SUBESTACION=R.TT3_SUBESTACION
WHERE R.TT3_PERIODO=SUBSTR(:MES_SEGU_01_MM_YYYY,7)
AND R.TT3_SEGUIRMES=:MES_SEGU_01_MM_YYYY
ORDER BY R.TT3_PERIODO,R.TT3_FINICIO,R.TT3_ID_DESCONEXION,L.TT3_LLAVE_CIRCUITO
;


--VER EL FORMATO TC1 PARA REVISAR SU CARGA
SELECT * 
FROM BRAE.QA_TTC1
WHERE TC1_PERIODO=:PERIODO_TC1_YYYYMM
;
--LLAMAR LOS TRAFOS A LA TABLA SEGUIMIENTO (8 ANTES)
SELECT  R.TT3_ID_DESCONEXION,
        R.TT3_PERIODO,
        TO_CHAR(R.TT3_SEGUIRMES,'DD/MM/YYYY') AS TT3_SEGUIRMES,
        R.TT3_BUSCADOR, 
        R.TT3_SUBESTACION,
        C.IUS,
        L.TT3_LLAVE_CIRCUITO,                
        TC.TC1_CODCONEX,
        DECODE(TC.TC1_TIPCONEX,'T',2,'P',1) AS TT3_CLASIFICACION,
        TC.TC1_IUA,
        TC.USUARIOS,
        TO_CHAR(R.TT3_FINICIO,'DD-MM-YYYY HH24:MI') AS TT3_FECHA_INICIO,
        TO_CHAR(R.TT3_FFIN,'DD-MM-YYYY HH24:MI') AS TT3_FECHA_FINALIZACION,
        R.TT3_ACTIVIDAD,
        R.TT3_DESCRIPCION,
        R.TT3_CODIGO_PROYECTO,
        R.TT3_CODIGO_PROYECTOAJS,        
        R.TT3_MEDIO_PUBLICACION,
        TO_CHAR(R.TT3_FECHA_ESTIMADA_PUBLICA,'DD-MM-YYYY') AS TT3_FECHA_ESTIMADA_PUBLICA

FROM BRAE.QA_TT3_SEGUIMIENTO R

LEFT OUTER JOIN BRAE.QA_TT3_LLAVEBUSCAR L                  ---LA TABLA LLAVE_BUSCADOR SIEMPRE SERÁ NECESARIA PARA DETERMINAR LAS CONDICIONES OPERATIVAS DE CADA ID_DESCONEXION 
            ON (L.TT3_LLAVE_BUSCADOR=R.TT3_BUSCADOR 
            AND L.TT3_LLAVE_PERIODO=R.TT3_PERIODO)
LEFT OUTER JOIN (SELECT DISTINCT LPAD(IUS,4,0) AS IUS,SUBSTR(SUBESTACION,13) AS SUBESTACION   ---SE REQUIERE DEFINIR UNA TABLA ALIMENTADA DE LOS FORMATOS BRA1 Y BRA7 QUE CONTENGAN LAS SUBESTACIONES Y LOS CIRCUITOS Y SUS CODIGOS CREG 
                 FROM BRAE.QA_CIRCUITO_SUBESTACION) C                                          ---POSIBLEMENTE INCLUIR UN CAMPO DE PERIODO PARA DISTINGUIR EL AÑO DE REPORTE DEL TT3
            ON C.SUBESTACION=R.TT3_SUBESTACION
LEFT OUTER JOIN (SELECT TT1_PERIODO, TT1_NOMBRECIRCUITO, TT1_CODIGOCIRCUITO
                 FROM BRAE.QA_TTT1_REPORTE
                 WHERE TRUNC(TT1_PERIODO)=(SELECT MAX(TRUNC(TT1_PERIODO))
                                           FROM BRAE.QA_TTT1_REPORTE)
                ) T1 
            ON T1.TT1_NOMBRECIRCUITO=L.TT3_LLAVE_CIRCUITO
LEFT OUTER JOIN (SELECT DISTINCT TC1_CODCIRC,TC1_CODCONEX,TC1_TIPCONEX,TC1_IUA,COUNT(TC1_TC1) AS USUARIOS
                 FROM BRAE.QA_TTC1
                 WHERE TC1_PERIODO=:PERIODO_TC1_YYYYMM
                 GROUP BY TC1_CODCIRC,TC1_CODCONEX,TC1_TIPCONEX,TC1_IUA) TC
            ON TC.TC1_CODCIRC=T1.TT1_CODIGOCIRCUITO

WHERE R.TT3_PERIODO=SUBSTR(:MES_SEGU_01_MM_YYYY,7)
AND R.TT3_SEGUIRMES=:MES_SEGU_01_MM_YYYY
AND TC.TC1_CODCONEX IS NOT NULL
AND TC.TC1_IUA IS NOT NULL

ORDER BY R.TT3_PERIODO,R.TT3_SEGUIRMES,R.TT3_FINICIO,R.TT3_ID_DESCONEXION,L.TT3_LLAVE_CIRCUITO,TC.TC1_CODCONEX
;
                 
---FORMATO SEGUIMIENTO TT11 ESTRUCTURA VERSION SUI (8 ANTES)

SELECT  R.TT3_ACTIVIDAD AS "Actividad",
        R.TT3_DESCRIPCION AS "Objetivo",
        DECODE(TC.TC1_TIPCONEX,'T',2,'P',1) AS "Tipo de Conexion",
        TC.TC1_IUA AS "Codigo Circuito o Trafo",
        TC.USUARIOS AS "Numero Usuarios Afectados",
        TO_CHAR(R.TT3_FINICIO,'DD-MM-YYYY HH24:MI') AS "Fecha y Hora Inicial",
        TO_CHAR(R.TT3_FFIN,'DD-MM-YYYY HH24:MI') AS "Fecha y Hora Final",
        ROUND(((R.TT3_FFIN-R.TT3_FINICIO)*24),2) AS "Duracion",
        R.TT3_MEDIO_PUBLICACION AS "Medio de Publicacion",
        TO_CHAR(R.TT3_FECHA_ESTIMADA_PUBLICA,'DD-MM-YYYY') AS "Fecha Estimada Publicacion",
        TO_CHAR(R.TT3_FINICIO,'MM') AS "Mes Proyeccion de Ejecucion"

FROM BRAE.QA_TT3_SEGUIMIENTO R

LEFT OUTER JOIN BRAE.QA_TT3_LLAVEBUSCAR L                  ---LA TABLA LLAVE_BUSCADOR SIEMPRE SERÁ NECESARIA PARA DETERMINAR LAS CONDICIONES OPERATIVAS DE CADA ID_DESCONEXION 
            ON (L.TT3_LLAVE_BUSCADOR=R.TT3_BUSCADOR 
            AND L.TT3_LLAVE_PERIODO=R.TT3_PERIODO)
LEFT OUTER JOIN (SELECT DISTINCT LPAD(IUS,4,0) AS IUS,SUBSTR(SUBESTACION,13) AS SUBESTACION   ---SE REQUIERE DEFINIR UNA TABLA ALIMENTADA DE LOS FORMATOS BRA1 Y BRA7 QUE CONTENGAN LAS SUBESTACIONES Y LOS CIRCUITOS Y SUS CODIGOS CREG 
                 FROM BRAE.QA_CIRCUITO_SUBESTACION) C                                          ---POSIBLEMENTE INCLUIR UN CAMPO DE PERIODO PARA DISTINGUIR EL AÑO DE REPORTE DEL TT3
            ON C.SUBESTACION=R.TT3_SUBESTACION
LEFT OUTER JOIN (SELECT TT1_PERIODO, TT1_NOMBRECIRCUITO, TT1_CODIGOCIRCUITO
                 FROM BRAE.QA_TTT1_REPORTE
                 WHERE TRUNC(TT1_PERIODO)=(SELECT MAX(TRUNC(TT1_PERIODO))
                                           FROM BRAE.QA_TTT1_REPORTE)
                ) T1 
            ON T1.TT1_NOMBRECIRCUITO=L.TT3_LLAVE_CIRCUITO
LEFT OUTER JOIN (SELECT DISTINCT TC1_CODCIRC,TC1_CODCONEX,TC1_TIPCONEX,TC1_IUA,COUNT(TC1_TC1) AS USUARIOS
                 FROM BRAE.QA_TTC1
                 WHERE TC1_PERIODO=:PERIODO_TC1_YYYYMM
                 AND TC1_TIPCONEX='T'
                 GROUP BY TC1_CODCIRC,TC1_CODCONEX,TC1_TIPCONEX,TC1_IUA) TC
            ON TC.TC1_CODCIRC=T1.TT1_CODIGOCIRCUITO

WHERE R.TT3_PERIODO=SUBSTR(:MES_SEGU_01_MM_YYYY,7)
AND R.TT3_SEGUIRMES=:MES_SEGU_01_MM_YYYY
AND TC.TC1_CODCONEX IS NOT NULL
AND TC.TC1_IUA IS NOT NULL

ORDER BY R.TT3_PERIODO,R.TT3_SEGUIRMES,R.TT3_FINICIO,R.TT3_ID_DESCONEXION,L.TT3_LLAVE_CIRCUITO,TC.TC1_CODCONEX
;


--RESUMEN DEL SEGUIMIENTO CONFIRMACION PARA EL CORREO A LA SSPD Y EQUIPOS CENS  (8 ANTES)

SELECT  R.TT3_ID_DESCONEXION,
        R.TT3_PERIODO,
        TO_CHAR(R.TT3_SEGUIRMES,'DD/MM/YYYY') AS TT3_SEGUIRMES,
        R.TT3_BUSCADOR, 
        R.TT3_SUBESTACION,
        C.IUS,
        TO_CHAR(R.TT3_FINICIO,'DD-MM-YYYY HH24:MI') AS TT3_FECHA_INICIO,
        TO_CHAR(R.TT3_FFIN,'DD-MM-YYYY HH24:MI') AS TT3_FECHA_FINALIZACION,
        R.TT3_DESCRIPCION,
        --R.TT3_CODIGO_PROYECTO,
        R.TT3_CODIGO_PROYECTOAJS,
        L.TT3_LLAVE_CIRCUITO,        
        SUM(TC.USUARIOS) AS USUARIOS,
        COUNT(TC.TC1_CODCONEX) AS TRAFOS

FROM BRAE.QA_TT3_SEGUIMIENTO R

LEFT OUTER JOIN BRAE.QA_TT3_LLAVEBUSCAR L                  ---LA TABLA LLAVE_BUSCADOR SIEMPRE SERÁ NECESARIA PARA DETERMINAR LAS CONDICIONES OPERATIVAS DE CADA ID_DESCONEXION 
            ON (L.TT3_LLAVE_BUSCADOR=R.TT3_BUSCADOR 
            AND L.TT3_LLAVE_PERIODO=R.TT3_PERIODO)
LEFT OUTER JOIN (SELECT DISTINCT LPAD(IUS,4,0) AS IUS,SUBSTR(SUBESTACION,13) AS SUBESTACION   ---SE REQUIERE DEFINIR UNA TABLA ALIMENTADA DE LOS FORMATOS BRA1 Y BRA7 QUE CONTENGAN LAS SUBESTACIONES Y LOS CIRCUITOS Y SUS CODIGOS CREG 
                 FROM BRAE.QA_CIRCUITO_SUBESTACION) C                                          ---POSIBLEMENTE INCLUIR UN CAMPO DE PERIODO PARA DISTINGUIR EL AÑO DE REPORTE DEL TT3
            ON C.SUBESTACION=R.TT3_SUBESTACION
LEFT OUTER JOIN (SELECT TT1_PERIODO, TT1_NOMBRECIRCUITO, TT1_CODIGOCIRCUITO
                 FROM BRAE.QA_TTT1_REPORTE
                 WHERE TRUNC(TT1_PERIODO)=(SELECT MAX(TRUNC(TT1_PERIODO))
                                           FROM BRAE.QA_TTT1_REPORTE)
                ) T1 
            ON T1.TT1_NOMBRECIRCUITO=L.TT3_LLAVE_CIRCUITO
LEFT OUTER JOIN (SELECT DISTINCT TC1_CODCIRC,TC1_CODCONEX,TC1_TIPCONEX,TC1_IUA,COUNT(TC1_TC1) AS USUARIOS
                 FROM BRAE.QA_TTC1
                 WHERE TC1_PERIODO=:PERIODO_TC1_YYYYMM
                 GROUP BY TC1_CODCIRC,TC1_CODCONEX,TC1_TIPCONEX,TC1_IUA) TC
            ON TC.TC1_CODCIRC=T1.TT1_CODIGOCIRCUITO

WHERE R.TT3_PERIODO=SUBSTR(:MES_SEGU_01_MM_YYYY,7)
AND R.TT3_SEGUIRMES=:MES_SEGU_01_MM_YYYY
AND TC.TC1_CODCONEX IS NOT NULL
AND TC.TC1_IUA IS NOT NULL

GROUP BY R.TT3_ID_DESCONEXION, R.TT3_PERIODO, R.TT3_SEGUIRMES, R.TT3_BUSCADOR, R.TT3_SUBESTACION, 
C.IUS, TO_CHAR(R.TT3_FINICIO,'DD-MM-YYYY HH24:MI'), TO_CHAR(R.TT3_FFIN,'DD-MM-YYYY HH24:MI'), 
R.TT3_DESCRIPCION, R.TT3_CODIGO_PROYECTO, R.TT3_CODIGO_PROYECTOAJS, 
L.TT3_LLAVE_CIRCUITO, TO_CHAR(R.TT3_SEGUIRMES,'DD/MM/YYYY')
            
ORDER BY R.TT3_PERIODO,R.TT3_SEGUIRMES,TT3_FECHA_INICIO,R.TT3_ID_DESCONEXION,L.TT3_LLAVE_CIRCUITO
;


----------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------
---SEGUIMIENTO TT3 INFORME EJECUCION 3 DIAS HABILES DESPUES, (TT12)

--PRIMERO SE DEBE MODIFICAR EL CAMPO TT3_CL_EJECUTADA PARA INGRESAR EL CODIGO DE CONSIGNA
--POBLAR EL CAMPO TT3_CL_EJECUTADA EN LA TABLA BRAE.QA_TT3_SEGUIMIENTO CON LOS VALORES DE LAS CONSIGNACIONES EJECUTADAS

/*
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_190421_011677' WHERE TT3_ID_DESCONEXION=5 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/04/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_190421_011677' WHERE TT3_ID_DESCONEXION=6 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/04/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_140421_012348' WHERE TT3_ID_DESCONEXION=7 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/04/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_150421_012368' WHERE TT3_ID_DESCONEXION=8 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/04/2021';

UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_080521_012482' WHERE TT3_ID_DESCONEXION=9 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/05/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_080521_012482' WHERE TT3_ID_DESCONEXION=10 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/05/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_020521_012481' WHERE TT3_ID_DESCONEXION=11 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/05/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_250521_013076' WHERE TT3_ID_DESCONEXION=13 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/05/2021';

UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_010721_013514' WHERE TT3_ID_DESCONEXION=12 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/07/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_070721_013665' WHERE TT3_ID_DESCONEXION=19 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/07/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_070721_013665' WHERE TT3_ID_DESCONEXION=20 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/07/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_010721_013664' WHERE TT3_ID_DESCONEXION=21 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/07/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_010721_013664' WHERE TT3_ID_DESCONEXION=22 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/07/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_310721_013676' WHERE TT3_ID_DESCONEXION=26 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/07/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_220721_013674' WHERE TT3_ID_DESCONEXION=28 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/07/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_280721_013675' WHERE TT3_ID_DESCONEXION=29 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/07/2021';

UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_120821_014084' WHERE TT3_ID_DESCONEXION=14 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/08/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_120821_014084' WHERE TT3_ID_DESCONEXION=15 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/08/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_310721_013676' WHERE TT3_ID_DESCONEXION=27 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/08/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_210821_014078' WHERE TT3_ID_DESCONEXION=30 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/08/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_210821_014078' WHERE TT3_ID_DESCONEXION=31 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/08/2021';

*/
/
DECLARE
BEGIN
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_011221_016046' WHERE TT3_ID_DESCONEXION=63 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/12/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_011221_016164 ' WHERE TT3_ID_DESCONEXION=71 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/12/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_021221_016056' WHERE TT3_ID_DESCONEXION=36 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/12/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_021221_016056' WHERE TT3_ID_DESCONEXION=37 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/12/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_021221_016049' WHERE TT3_ID_DESCONEXION=74 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/12/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_101221_016229' WHERE TT3_ID_DESCONEXION=50 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/12/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_101221_016267' WHERE TT3_ID_DESCONEXION=65 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/12/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_131221_016065' WHERE TT3_ID_DESCONEXION=32 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/12/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_131221_016065' WHERE TT3_ID_DESCONEXION=47 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/12/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_141221_016066' WHERE TT3_ID_DESCONEXION=75 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/12/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_171221_016067' WHERE TT3_ID_DESCONEXION=67 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/12/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_291221_016408' WHERE TT3_ID_DESCONEXION=78 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/12/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_281221_016247' WHERE TT3_ID_DESCONEXION=62 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/12/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_281221_016247' WHERE TT3_ID_DESCONEXION=81 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/12/2021';
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_CL_EJECUTADA='CL_271221_016246' WHERE TT3_ID_DESCONEXION=45 AND TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/12/2021';
END;
/

SELECT * FROM QA_TT3_SEGUIMIENTO 
WHERE TO_CHAR(TT3_SEGUIRMES,'DD/MM/YYYY')= '01/12/2021';

COMMIT;
/*
--COMMIT;
*/
--SE DEBEN ACTUALIZAR LOS VALORES DEL CAMPO ACTIVIDAD DE LA TABLA SEGUIMIENTO YA QUE NO VIAJARON EN EL INSERT INICIAL
/*
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_ACTIVIDAD=(SELECT TT3_ACTIVIDAD FROM BRAE.QA_TT3_RESUMEN WHERE tt3_id_desconexion=12 AND tt3_periodo=2021) WHERE TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/07/2021' AND TT3_ID_DESCONEXION=12;
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_ACTIVIDAD=(SELECT TT3_ACTIVIDAD FROM BRAE.QA_TT3_RESUMEN WHERE tt3_id_desconexion=19 AND tt3_periodo=2021) WHERE TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/07/2021' AND TT3_ID_DESCONEXION=19;
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_ACTIVIDAD=(SELECT TT3_ACTIVIDAD FROM BRAE.QA_TT3_RESUMEN WHERE tt3_id_desconexion=20 AND tt3_periodo=2021) WHERE TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/07/2021' AND TT3_ID_DESCONEXION=20;
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_ACTIVIDAD=(SELECT TT3_ACTIVIDAD FROM BRAE.QA_TT3_RESUMEN WHERE tt3_id_desconexion=21 AND tt3_periodo=2021) WHERE TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/07/2021' AND TT3_ID_DESCONEXION=21;
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_ACTIVIDAD=(SELECT TT3_ACTIVIDAD FROM BRAE.QA_TT3_RESUMEN WHERE tt3_id_desconexion=22 AND tt3_periodo=2021) WHERE TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/07/2021' AND TT3_ID_DESCONEXION=22;
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_ACTIVIDAD=(SELECT TT3_ACTIVIDAD FROM BRAE.QA_TT3_RESUMEN WHERE tt3_id_desconexion=26 AND tt3_periodo=2021) WHERE TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/07/2021' AND TT3_ID_DESCONEXION=26;
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_ACTIVIDAD=(SELECT TT3_ACTIVIDAD FROM BRAE.QA_TT3_RESUMEN WHERE tt3_id_desconexion=28 AND tt3_periodo=2021) WHERE TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/07/2021' AND TT3_ID_DESCONEXION=28;
UPDATE BRAE.QA_TT3_SEGUIMIENTO SET TT3_ACTIVIDAD=(SELECT TT3_ACTIVIDAD FROM BRAE.QA_TT3_RESUMEN WHERE tt3_id_desconexion=29 AND tt3_periodo=2021) WHERE TT3_PERIODO=2021 AND TT3_SEGUIRMES='01/07/2021' AND TT3_ID_DESCONEXION=29;
*/
--COMMIT;



/*--LLAMAR LOS ALIMENTADORES A LA TABLA SEGUIMIENTO (3 DESPUES) 
SOLO VERIFICA LOS QUE SI SE EJECUTÓ CON LA INFORMACION COMO ESTABA PROGRAMADO*/
SELECT  R.TT3_ID_DESCONEXION,
        R.TT3_PERIODO,
        R.TT3_SEGUIRMES,
        R.TT3_BUSCADOR, 
        R.TT3_SUBESTACION,
        C.IUS,
        L.TT3_LLAVE_CIRCUITO,
        TO_CHAR(R.TT3_FINICIO,'DD-MM-YYYY HH24:MI') AS TT3_FECHA_INICIO,
        TO_CHAR(R.TT3_FFIN,'DD-MM-YYYY HH24:MI') AS TT3_FECHA_FINALIZACION,
        R.TT3_DESCRIPCION,
        R.TT3_ACTIVIDAD,
        R.TT3_CODIGO_PROYECTO,
        R.TT3_CODIGO_PROYECTOAJS ,
        R.TT3_CL_EJECUTADA
FROM BRAE.QA_TT3_SEGUIMIENTO R
LEFT OUTER JOIN BRAE.QA_TT3_LLAVEBUSCAR L 
            ON (L.TT3_LLAVE_BUSCADOR=R.TT3_BUSCADOR 
            AND L.TT3_LLAVE_PERIODO=R.TT3_PERIODO)
LEFT OUTER JOIN (SELECT DISTINCT IUS,SUBSTR(SUBESTACION,13) AS SUBESTACION 
                 FROM BRAE.QA_CIRCUITO_SUBESTACION) C
            ON C.SUBESTACION=R.TT3_SUBESTACION
WHERE R.TT3_PERIODO=SUBSTR(:MES_SEGU_01_MM_YYYY,7)
AND R.TT3_SEGUIRMES=:MES_SEGU_01_MM_YYYY
AND R.TT3_CL_EJECUTADA IS NOT NULL --PARA VER SOLO LAS EJECUTADAS CON CONSIGNACION
ORDER BY R.TT3_PERIODO,R.TT3_ID_DESCONEXION, R.TT3_FINICIO, L.TT3_LLAVE_CIRCUITO
;

--VERIFICAR LOS EVENTOS REGISTRADOS EN OMS Y QoS PARA VALIDAR LO EJECUTADO CAUSAS Y FECHAS

SELECT DISTINCT TO_NUMBER(RG.FDD_CODIGOEVENTO) AS FDD_CODIGOEVENTO,
I.MFINAL AS I_MFINAL,
TO_CHAR(I.FINICIAL,'DD-MM-YYYY HH24:MI') AS I_FINICIAL,   --ESTAS FECHAS TOMADAS DEL OMS_INTERUPC
TO_CHAR(I.FFINAL,'DD-MM-YYYY HH24:MI') AS I_FFINAL,       --ESTAS FECHAS TOMADAS DEL OMS_INTERUPC
TO_CHAR(RG.FDD_FINICIAL,'DD-MM-YYYY HH24:MI') AS FDD_FINICIAL,--ESTAS FECHAS TOMADAS DEL QA_TFDDREGISTRO
TO_CHAR(RG.FDD_FFINAL,'DD-MM-YYYY HH24:MI') AS FDD_FFINAL,    --ESTAS FECHAS TOMADAS DEL QA_TFDDREGISTRO
MI.BREAKER AS BREAKER_INICIAL,
DIRI.TIPO_BREAKER AS TIPO_BREAKER_I,
DIRI.DIRECCION AS DIRECCION_I,
DIRI.CIRCUITO AS CIRCUITO_I,
MI.CAUSA AS CAUSA_OMS_I,
C.FDC_DETALLE AS FDC_DETALLE_OMS_I,
RG.FDD_CAUSA AS CAUSA_QOS_I,
RG.FDD_CAUSA_CREG AS FDD_CAUSA_CREG_I,
C.FDC_DESCRIPCION AS DESCRIPCION_OMS_I,
RG.FDD_CAUSA_SSPD AS FDD_CAUSA_SSPD_I,    
MF.BREAKER AS BREAKER_FINAL,
MF.CAUSA AS CAUSA_OMS_F,
DIRF.TIPO_BREAKER AS TIPO_BREAKER_F,
DIRF.DIRECCION AS DIRECCION_F,
DIRF.CIRCUITO AS CIRCUITO_F,       
MI.OBJETIVO AS TT3_DETALLLE_TRABAJOS

FROM BRAE.QA_TFDDREGISTRO RG
LEFT OUTER JOIN OMS.INTERUPC I ON I.MINICIAL||I.TRAFO=RG.FDD_CODIGOEVENTO||RG.FDD_CODIGOELEMENTO --ESTO PARA EVITAR PRODUCTO CARTESIANO
LEFT OUTER JOIN OMS.MANIOBRAS MI ON MI.CODE=I.MINICIAL
LEFT OUTER JOIN OMS.MANIOBRAS MF ON MF.CODE=I.MFINAL
LEFT OUTER JOIN BRAE.QA_TFDDCAUSAS C ON C.FDC_CAUSA_OMS=MI.CAUSA
LEFT OUTER JOIN (SELECT CODE AS CODE, 'CABECERA_CIRCUITO' AS TIPO_BREAKER, DESCRIPTIO AS DIRECCION, CODE AS CIRCUITO FROM OMS.FEEDERS
                            UNION ALL
                            SELECT CODE, 'RECONECTADOR_RED', ADDRESS, FPARENT FROM OMS.RECLOSER
                            UNION ALL
                            SELECT CODE, DESCRIPTIO, ADDRESS, FPARENT FROM OMS.SWITCHES
                            UNION ALL
                            SELECT ELNODE, 'TRANSFORMADOR', ADDRESS, FPARENT FROM OMS.TRANSFOR
                            UNION ALL
                            SELECT INTERRUP1, 'HVTRANS_HEREDADO', NODO1||'|'||NODO2, 'CTO_P' FROM OMS.HVTRANS WHERE INTERRUP1 IS NOT NULL
                            UNION ALL
                            SELECT INTERRUP2, 'HVTRANS_HEREDADO', NODO1||'|'||NODO2, 'CTO_P' FROM OMS.HVTRANS WHERE INTERRUP2 IS NOT NULL
                            UNION ALL
                            SELECT INTERRUP1, 'HVLINSEC_HEREDADO', ELNODE1||'|'||ELNODE2, 'CTO_P' FROM OMS.HVLINSEC WHERE INTERRUP1 IS NOT NULL
                            UNION ALL
                            SELECT INTERRUP2, 'HVLINSEC_HEREDADO', ELNODE1||'|'||ELNODE2, 'CTO_P' FROM OMS.HVLINSEC WHERE INTERRUP2 IS NOT NULL) DIRI
                            ON DIRI.CODE=MI.BREAKER
LEFT OUTER JOIN (SELECT CODE AS CODE, 'CABECERA_CIRCUITO' AS TIPO_BREAKER, DESCRIPTIO AS DIRECCION, CODE AS CIRCUITO FROM OMS.FEEDERS
                            UNION ALL
                            SELECT CODE, 'RECONECTADOR_RED', ADDRESS, FPARENT FROM OMS.RECLOSER
                            UNION ALL
                            SELECT CODE, DESCRIPTIO, ADDRESS, FPARENT FROM OMS.SWITCHES
                            UNION ALL
                            SELECT ELNODE, 'TRANSFORMADOR', ADDRESS, FPARENT FROM OMS.TRANSFOR
                            UNION ALL
                            SELECT INTERRUP1, 'HVTRANS_HEREDADO', NODO1||'|'||NODO2, 'CTO_P' FROM OMS.HVTRANS WHERE INTERRUP1 IS NOT NULL
                            UNION ALL
                            SELECT INTERRUP2, 'HVTRANS_HEREDADO', NODO1||'|'||NODO2, 'CTO_P' FROM OMS.HVTRANS WHERE INTERRUP2 IS NOT NULL
                            UNION ALL
                            SELECT INTERRUP1, 'HVLINSEC_HEREDADO', ELNODE1||'|'||ELNODE2, 'CTO_P' FROM OMS.HVLINSEC WHERE INTERRUP1 IS NOT NULL
                            UNION ALL
                            SELECT INTERRUP2, 'HVLINSEC_HEREDADO', ELNODE1||'|'||ELNODE2, 'CTO_P' FROM OMS.HVLINSEC WHERE INTERRUP2 IS NOT NULL) DIRF
                            ON DIRF.CODE=MF.BREAKER

WHERE TO_CHAR(RG.FDD_FINICIAL,'MM/YYYY') = SUBSTR(:MES_SEGU_01_MM_YYYY,4)  -- FECHAS EJECUTADAS DE LAS CONSIGNACIONES
AND (RG.FDD_CAUSA_CREG = '10'   -- ESTO ES PARA CONSULTAR DE QoS
    OR C.FDC_CAUSA_015 = '10')  -- ESTO ES PARA CONSULTAR DE OMS

ORDER BY FDD_FINICIAL,FDD_FFINAL,FDD_CODIGOEVENTO
;


  
--LLAMAR LOS TRAFOS A LA TABLA SEGUIMIENTO (3 DESPUES)
SELECT  R.TT3_ID_DESCONEXION,
        R.TT3_PERIODO,
        R.TT3_SEGUIRMES,
        R.TT3_BUSCADOR, 
        R.TT3_SUBESTACION,
        C.IUS,
        DECODE(TC.TC1_TIPCONEX,'T',2,'P',1) AS TT3_CLASIFICACION,
        RG.FDD_CODIGOELEMENTO, --TC.TC1_CODCONEX,
        RG.FDD_IUA, --TC.TC1_IUA,
        TO_CHAR(RG.FDD_FINICIAL,'DD-MM-YYYY HH24:MI') AS TT3_FECHA_INICIO_REAL, --R.TT3_FINICIO
        TO_CHAR(RG.FDD_FFINAL,'DD-MM-YYYY HH24:MI') AS TT3_FECHA_FINALIZACION_REAL,  --R.TT3_FFIN
        R.TT3_ACTIVIDAD,
        R.TT3_DESCRIPCION,
        R.TT3_CODIGO_PROYECTO,
        R.TT3_CODIGO_PROYECTOAJS,
        L.TT3_LLAVE_CIRCUITO,        
        TC.USUARIOS
FROM BRAE.QA_TT3_SEGUIMIENTO R
LEFT OUTER JOIN BRAE.QA_TT3_LLAVEBUSCAR L                                                   ---LA TABLA LLAVE_BUSCADOR SIEMPRE SERÁ NECESARIA PARA DETERMINAR LAS CONDICIONES OPERATIVAS DE CADA ID_DESCONEXION 
            ON (L.TT3_LLAVE_BUSCADOR=R.TT3_BUSCADOR 
            AND L.TT3_LLAVE_PERIODO=R.TT3_PERIODO)
LEFT OUTER JOIN (SELECT DISTINCT LPAD(IUS,4,0) AS IUS,SUBSTR(SUBESTACION,13) AS SUBESTACION                   ---SE REQUIERE DEFINIR UNA TABLA ALIMENTADA DE LOS FORMATOS BRA1 Y BRA7 QUE CONTENGAN LAS SUBESTACIONES Y LOS CIRCUITOS Y SUS CODIGOS CREG 
                 FROM BRAE.QA_CIRCUITO_SUBESTACION) C                                        ---POSIBLEMENTE INCLUIR UN CAMPO DE PERIODO PARA DISTINGUIR EL AÑO DE REPORTE DEL TT3
            ON C.SUBESTACION=R.TT3_SUBESTACION
LEFT OUTER JOIN (SELECT TT1_PERIODO, TT1_NOMBRECIRCUITO, TT1_CODIGOCIRCUITO
                 FROM BRAE.QA_TTT1_REPORTE
                 WHERE TRUNC(TT1_PERIODO)=(SELECT MAX(TRUNC(TT1_PERIODO))
                                           FROM BRAE.QA_TTT1_REPORTE)
                ) T1 
            ON T1.TT1_NOMBRECIRCUITO=L.TT3_LLAVE_CIRCUITO
LEFT OUTER JOIN (SELECT DISTINCT TC1_CODCIRC,TC1_CODCONEX,TC1_TIPCONEX,TC1_IUA,COUNT(TC1_TC1) AS USUARIOS
                 FROM BRAE.QA_TTC1
                 WHERE TC1_PERIODO=:PERIODO_TC1_YYYYMM
                 GROUP BY TC1_CODCIRC,TC1_CODCONEX,TC1_TIPCONEX,TC1_IUA) TC
            ON TC.TC1_CODCIRC=T1.TT1_CODIGOCIRCUITO
LEFT OUTER JOIN BRAE.QA_TFDDREGISTRO RG 
          ON (RG.FDD_CODIGOELEMENTO=TC.TC1_CODCONEX
          AND TO_CHAR(RG.FDD_FINICIAL,'MM/YYYY')= TO_CHAR(R.TT3_FINICIO,'MM/YYYY')      -----REVISAR COMO PODRIA CAUSAR UN PRODUCTO CARTESIANO Y DUPLICAR TRANSFORMADORES EN UN MISMO EVENTO
          /*AND TO_CHAR(RG.FDD_FFINAL,'DD/MM/YYYY')= TO_CHAR(R.TT3_FFIN,'DD/MM/YYYY')*/           -----ESTO OBLIGA A QUE LA FECHA DE EJECUCION Y LA CONFIRMADA EN EL TT11 SEAN IGUALES AL INICIO Y AL FINAL
          )
WHERE TC.TC1_CODCONEX IS NOT NULL
AND TC.TC1_IUA IS NOT NULL
AND R.TT3_PERIODO=SUBSTR(:MES_SEGU_01_MM_YYYY,7)
AND R.TT3_SEGUIRMES=:MES_SEGU_01_MM_YYYY
AND RG.FDD_CAUSA_CREG=10  --DEPENDE DE QUE EN QOS ESTEN CORRECTAMENTE LAS CLASIFICACIONES DE EVENTOS Y AJUSTES TERMINADOS
AND R.TT3_CL_EJECUTADA IS NOT NULL --PARA VER SOLO LAS EJECUTADAS CON CONSIGNACION
ORDER BY R.TT3_PERIODO,R.TT3_FINICIO,R.TT3_ID_DESCONEXION,L.TT3_LLAVE_CIRCUITO,TC.TC1_CODCONEX
;


---FROMATO SEGUIMIENTO TT3 ESTRUCTURA VERSION SUI (3 DESPUES)

SELECT  R.TT3_ACTIVIDAD AS "Actividad",
        DECODE(TC.TC1_TIPCONEX,'T',2,'P',1) AS "Tipo de Conexion",
        RG.FDD_IUA AS "Codigo Circuito o Trafo",
        TC.USUARIOS AS "Numero Usuarios Afectados",
        TO_CHAR(RG.FDD_FINICIAL,'DD-MM-YYYY HH24:MI') AS "Fecha y Hora Inicial", --R.TT3_FINICIO
        TO_CHAR(RG.FDD_FFINAL,'DD-MM-YYYY HH24:MI') AS "Fecha y Hora Final",  --R.TT3_FFIN        
        ROUND(((NVL(TO_DATE(TO_CHAR(RG.FDD_FFINAL,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'),(ADD_MONTHS (:MES_SEGU_01_MM_YYYY,1)))-TO_DATE(TO_CHAR(RG.FDD_FINICIAL,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'))*24),2) AS "Duracion",
        TO_CHAR(RG.FDD_FINICIAL,'MM') AS "Mes Realizacion de Ejecucion"
        
FROM BRAE.QA_TT3_SEGUIMIENTO R
LEFT OUTER JOIN BRAE.QA_TT3_LLAVEBUSCAR L                                                   ---LA TABLA LLAVE_BUSCADOR SIEMPRE SERÁ NECESARIA PARA DETERMINAR LAS CONDICIONES OPERATIVAS DE CADA ID_DESCONEXION 
            ON (L.TT3_LLAVE_BUSCADOR=R.TT3_BUSCADOR 
            AND L.TT3_LLAVE_PERIODO=R.TT3_PERIODO)
LEFT OUTER JOIN (SELECT DISTINCT LPAD(IUS,4,0) AS IUS,SUBSTR(SUBESTACION,13) AS SUBESTACION                   ---SE REQUIERE DEFINIR UNA TABLA ALIMENTADA DE LOS FORMATOS BRA1 Y BRA7 QUE CONTENGAN LAS SUBESTACIONES Y LOS CIRCUITOS Y SUS CODIGOS CREG 
                 FROM BRAE.QA_CIRCUITO_SUBESTACION) C                                        ---POSIBLEMENTE INCLUIR UN CAMPO DE PERIODO PARA DISTINGUIR EL AÑO DE REPORTE DEL TT3
            ON C.SUBESTACION=R.TT3_SUBESTACION
LEFT OUTER JOIN (SELECT TT1_PERIODO, TT1_NOMBRECIRCUITO, TT1_CODIGOCIRCUITO
                 FROM BRAE.QA_TTT1_REPORTE
                 WHERE TRUNC(TT1_PERIODO)=(SELECT MAX(TRUNC(TT1_PERIODO))
                                           FROM BRAE.QA_TTT1_REPORTE)
                ) T1 
            ON T1.TT1_NOMBRECIRCUITO=L.TT3_LLAVE_CIRCUITO
LEFT OUTER JOIN (SELECT DISTINCT TC1_CODCIRC,TC1_CODCONEX,TC1_TIPCONEX,TC1_IUA,COUNT(TC1_TC1) AS USUARIOS
                 FROM BRAE.QA_TTC1
                 WHERE TC1_PERIODO=:PERIODO_TC1_YYYYMM
                 GROUP BY TC1_CODCIRC,TC1_CODCONEX,TC1_TIPCONEX,TC1_IUA) TC
            ON TC.TC1_CODCIRC=T1.TT1_CODIGOCIRCUITO
LEFT OUTER JOIN BRAE.QA_TFDDREGISTRO RG 
          ON (RG.FDD_CODIGOELEMENTO=TC.TC1_CODCONEX
          AND TO_CHAR(RG.FDD_FINICIAL,'MM/YYYY')= TO_CHAR(R.TT3_FINICIO,'MM/YYYY')      -----REVISAR COMO PODRIA CAUSAR UN PRODUCTO CARTESIANO Y DUPLICAR TRANSFORMADORES EN UN MISMO EVENTO
          /*AND TO_CHAR(RG.FDD_FFINAL,'DD/MM/YYYY')= TO_CHAR(R.TT3_FFIN,'DD/MM/YYYY')*/           -----ESTO OBLIGA A QUE LA FECHA DE EJECUCION Y LA CONFIRMADA EN EL TT11 SEAN IGUALES AL INICIO Y AL FINAL
          )
WHERE TC.TC1_CODCONEX IS NOT NULL
AND TC.TC1_IUA IS NOT NULL
AND R.TT3_PERIODO=SUBSTR(:MES_SEGU_01_MM_YYYY,7)
AND R.TT3_SEGUIRMES=:MES_SEGU_01_MM_YYYY
AND RG.FDD_CAUSA_CREG=10  --DEPENDE DE QUE EN QOS ESTEN CORRECTAMENTE LAS CLASIFICACIONES DE EVENTOS Y AJUSTES TERMINADOS
AND R.TT3_CL_EJECUTADA IS NOT NULL --PARA VER SOLO LAS EJECUTADAS CON CONSIGNACION
ORDER BY R.TT3_PERIODO,R.TT3_FINICIO,R.TT3_ID_DESCONEXION,L.TT3_LLAVE_CIRCUITO,TC.TC1_CODCONEX
;



----SIN REVISAR CONSIGNSA NO EJECUTADAS EN EL MES
---EXPORTE DE LA TABLA DE REGISTRO PARA COMPLETAR LOS TRAFOS QUE FALTARON
-----------------------------------------------------------------------------------------------------------
SELECT TO_NUMBER(RG.FDD_CODIGOEVENTO) AS FDD_CODIGOEVENTO,
I.MFINAL AS I_MFINAL,
TO_CHAR(RG.FDD_FINICIAL,'DD-MM-YYYY HH24:MI') AS FDD_FINICIAL,--ESTAS FECHAS TOMADAS DEL QA_TFDDREGISTRO
TO_CHAR(RG.FDD_FFINAL,'DD-MM-YYYY HH24:MI') AS FDD_FFINAL,    --ESTAS FECHAS TOMADAS DEL QA_TFDDREGISTRO
RG.FDD_CODIGOELEMENTO,
RG.FDD_IUA,
T.FPARENT,
MI.BREAKER AS BREAKER_INICIAL,
DIRI.TIPO_BREAKER AS TIPO_BREAKER_I,
DIRI.DIRECCION AS DIRECCION_I,
DIRI.CIRCUITO AS CIRCUITO_I,
RG.FDD_CAUSA AS CAUSA_QOS_I,
RG.FDD_CAUSA_CREG AS FDD_CAUSA_CREG_I,
RG.FDD_CAUSA_SSPD AS FDD_CAUSA_SSPD_I,    
MF.BREAKER AS BREAKER_FINAL,
DIRF.TIPO_BREAKER AS TIPO_BREAKER_F,
DIRF.DIRECCION AS DIRECCION_F,
DIRF.CIRCUITO AS CIRCUITO_F,       
MI.OBJETIVO AS TT3_DETALLLE_TRABAJOS,
TC.USUARIOS

FROM BRAE.QA_TFDDREGISTRO RG
LEFT OUTER JOIN OMS.INTERUPC I ON I.MINICIAL||I.TRAFO=RG.FDD_CODIGOEVENTO||RG.FDD_CODIGOELEMENTO --ESTO PARA EVITAR PRODUCTO CARTESIANO
LEFT OUTER JOIN OMS.MANIOBRAS MI ON MI.CODE=I.MINICIAL
LEFT OUTER JOIN OMS.MANIOBRAS MF ON MF.CODE=I.MFINAL
LEFT OUTER JOIN BRAE.QA_TFDDCAUSAS C ON C.FDC_CAUSA_OMS=MI.CAUSA
LEFT OUTER JOIN SPARD.TRANSFOR T
            ON T.CODE=RG.FDD_CODIGOELEMENTO
LEFT OUTER JOIN (SELECT DISTINCT TC1_CODCONEX,TC1_TIPCONEX,TC1_IUA,COUNT(TC1_TC1) AS USUARIOS
                 FROM BRAE.QA_TTC1
                 WHERE TC1_PERIODO=:PERIODO_TC1_YYYYMM
                 GROUP BY TC1_CODCONEX,TC1_TIPCONEX,TC1_IUA) TC
            ON TC.TC1_CODCONEX=RG.FDD_CODIGOELEMENTO
LEFT OUTER JOIN (SELECT CODE AS CODE, 'CABECERA_CIRCUITO' AS TIPO_BREAKER, DESCRIPTIO AS DIRECCION, CODE AS CIRCUITO FROM OMS.FEEDERS
                            UNION ALL
                            SELECT CODE, 'RECONECTADOR_RED', ADDRESS, FPARENT FROM OMS.RECLOSER
                            UNION ALL
                            SELECT CODE, DESCRIPTIO, ADDRESS, FPARENT FROM OMS.SWITCHES
                            UNION ALL
                            SELECT ELNODE, 'TRANSFORMADOR', ADDRESS, FPARENT FROM OMS.TRANSFOR
                            UNION ALL
                            SELECT INTERRUP1, 'HVTRANS_HEREDADO', NODO1||'|'||NODO2, 'CTO_P' FROM OMS.HVTRANS WHERE INTERRUP1 IS NOT NULL
                            UNION ALL
                            SELECT INTERRUP2, 'HVTRANS_HEREDADO', NODO1||'|'||NODO2, 'CTO_P' FROM OMS.HVTRANS WHERE INTERRUP2 IS NOT NULL
                            UNION ALL
                            SELECT INTERRUP1, 'HVLINSEC_HEREDADO', ELNODE1||'|'||ELNODE2, 'CTO_P' FROM OMS.HVLINSEC WHERE INTERRUP1 IS NOT NULL
                            UNION ALL
                            SELECT INTERRUP2, 'HVLINSEC_HEREDADO', ELNODE1||'|'||ELNODE2, 'CTO_P' FROM OMS.HVLINSEC WHERE INTERRUP2 IS NOT NULL) DIRI
                            ON DIRI.CODE=MI.BREAKER
LEFT OUTER JOIN (SELECT CODE AS CODE, 'CABECERA_CIRCUITO' AS TIPO_BREAKER, DESCRIPTIO AS DIRECCION, CODE AS CIRCUITO FROM OMS.FEEDERS
                            UNION ALL
                            SELECT CODE, 'RECONECTADOR_RED', ADDRESS, FPARENT FROM OMS.RECLOSER
                            UNION ALL
                            SELECT CODE, DESCRIPTIO, ADDRESS, FPARENT FROM OMS.SWITCHES
                            UNION ALL
                            SELECT ELNODE, 'TRANSFORMADOR', ADDRESS, FPARENT FROM OMS.TRANSFOR
                            UNION ALL
                            SELECT INTERRUP1, 'HVTRANS_HEREDADO', NODO1||'|'||NODO2, 'CTO_P' FROM OMS.HVTRANS WHERE INTERRUP1 IS NOT NULL
                            UNION ALL
                            SELECT INTERRUP2, 'HVTRANS_HEREDADO', NODO1||'|'||NODO2, 'CTO_P' FROM OMS.HVTRANS WHERE INTERRUP2 IS NOT NULL
                            UNION ALL
                            SELECT INTERRUP1, 'HVLINSEC_HEREDADO', ELNODE1||'|'||ELNODE2, 'CTO_P' FROM OMS.HVLINSEC WHERE INTERRUP1 IS NOT NULL
                            UNION ALL
                            SELECT INTERRUP2, 'HVLINSEC_HEREDADO', ELNODE1||'|'||ELNODE2, 'CTO_P' FROM OMS.HVLINSEC WHERE INTERRUP2 IS NOT NULL) DIRF
                            ON DIRF.CODE=MF.BREAKER

WHERE TO_CHAR(RG.FDD_FINICIAL,'YYYYMM') = :PERIODO_YYYYMM  -- FECHAS EJECUTADAS DE LAS CONSIGNACIONES
AND (RG.FDD_CAUSA_CREG = '10'   -- ESTO ES PARA CONSULTAR DE QoS
    OR C.FDC_CAUSA_015 = '10')  -- ESTO ES PARA CONSULTAR DE OMS

ORDER BY FDD_FINICIAL,FDD_FFINAL,FDD_CODIGOEVENTO
;

SELECT count(*) FROM QA_TFDDREGISTRO
WHERE TO_CHAR(FDD_FINICIAL,'DD/MM/YYYY')='01/12/2021'
AND FDD_CAUSA_CREG IN ('10');-- CON CAUSA CREG
--AND FDD_CODIGOELEMENTO='2T02446';
--AND FDD_CAUSA_SSPD IN ('14');--CAUSA SSPD - SIN RECIERRE


