SELECT TPARENT, SUM(KW) AS KW, T.MUNICIPIO,M.DESCRIPCION
--SELECT COUNT(*)
FROM SPARD.STREETLG
LEFT OUTER JOIN TRANSFOR T ON T.CODE=TPARENT
LEFT OUTER JOIN MUN_DANE M ON M.MUN_ID=T.MUNICIPIO
WHERE TPARENT IS NOT NULL
GROUP BY TPARENT,T.MUNICIPIO,M.DESCRIPCION
ORDER BY TPARENT;
