---USUARIOS CON DIU O FIU MAYOR A 360
SELECT  TO_CHAR(CSU_PERIODO_OP,'DD/MM/YYYY') AS PERIODO_OP,
        CSU_NIU,
        TC.TC1_CODCONEX,
        TR.PROPIEDAD,
        TRF.KVA,
        TRF.PHASES,        
        TR.FPARENT,
        TO_NUMBER(TR.GRUPO015) AS GRUPO015,
        TR.POBLACION,
        TR.MUNDANE,
        M.MUND_DESCRIPCION,
        M.MUND_REGIONAL,        
        TR.LATITUD,
        TR.LONGITUD,
        ROUND(CSU_DIUM,2) AS CSU_DIUM,
        ROUND(CSU_DIU,2) AS CSU_DIU,
        CSU_FIUM,
        CSU_FIU       
FROM  QA_TCSU TU
LEFT OUTER JOIN (SELECT TO_DATE(('01'||'/'||SUBSTR(TC1_PERIODO,5,6)||'/'||SUBSTR(TC1_PERIODO,1,4)),'DD/MM/YYYY') AS PERIODO_OP, TC1_TC1, TC1_CODCONEX --,TC1_GC
                 FROM (SELECT * FROM QA_TTC1 UNION ALL SELECT * FROM QA_TTC1_TEMP)) TC ON (TU.CSU_PERIODO_OP = TC.PERIODO_OP AND TU.CSU_NIU = TC.TC1_TC1) -- SOLO CUANDO HAY DATOS TEMPORALES CARGADOS EN LA TABLA TC1_TEMP ALTERNA
LEFT OUTER JOIN (SELECT CODE,FPARENT,OWNER AS PROPIEDAD,TRFTYPE,(DEP_ID*1000+MUNICIPIO) AS MUNDANE,POBLACION,GRUPO015,LATITUD,LONGITUD FROM OMS.TRANSFOR@OMSPROD) TR ON TR.CODE=TC.TC1_CODCONEX
LEFT OUTER JOIN GE_TMUNDANE M ON M.MUND_MUNDANE=TR.MUNDANE
LEFT OUTER JOIN OMS.TRFTYPES@OMSPROD TRF ON TRF.CODE=TR.TRFTYPE
WHERE   (TU.CSU_DIU>=360 OR TU.CSU_FIU>=360)
ORDER BY CSU_PERIODO_OP, CSU_NIU;