--ACTUALIZACION PARA TC1 AJUSTES

DELETE FROM QA_TTC1_TEMP;
COMMIT;

SELECT MAX(TC1_PERIODO) FROM QA_TTC1;--202203

INSERT   INTO QA_TTC1
SELECT * FROM QA_TTC1_TEMP;

COMMIT;


--APROBACION DE AUMENTO POR ENCIMA DE 1000 USUARIOS
SELECT ((SELECT COUNT(TC1_TC1) FROM QA_TTC1_TEMP      WHERE TC1_PERIODO=202205)
       -(SELECT COUNT(TC1_TC1) FROM QA_TTC1           WHERE TC1_PERIODO=202204)) AS CANTIDAD_DE_AUMENTO
FROM DUAL;--1701

--VALIDAR QUE NO EXISTA UN TRANSFORMADOR CON DIFERENTES IUA
SELECT T.X, COUNT(T.X) AS CANTIDAD
FROM(SELECT DISTINCT TC1_CODCONEX AS X,TC1_IUA FROM QA_TTC1_TEMP /*WHERE TC1_PERIODO=202204*/) T
WHERE T.X <> '2T01495'
HAVING COUNT(T.X) > 1 
GROUP BY T.X; --NO DEBE ARROJAR NINGUN RESULTADO


--VALIDAR QUE NO EXISTA UN TRANSFORMDAOR CON DIFERENTE IUL

SELECT T.X, COUNT(T.X) AS CANTIDAD
FROM(
    SELECT DISTINCT TC1_CODCONEX AS X,TC1_CODCIRC
    FROM QA_TTC1
    WHERE TC1_TIPCONEX='T'
    AND   TC1_PERIODO = 202204
    AND TC1_CODCONEX NOT LIKE 'ALPM%') T
HAVING COUNT(T.X) > 1
GROUP BY T.X
;-- NO DEBE ARROJAR NINGUN RESULTADO

--VALIDAR QUE NO EXISTA UN USUARIO DUPLICADO CON DIFERENTE TRANSFORMADOR

--VALIDAR QUE NO EXISTA UN USUARIO CON DIFERENTES IUA
SELECT T.X, COUNT(T.X) AS CANTIDAD
FROM(SELECT DISTINCT TC1_TC1 AS X,TC1_IUA FROM QA_TTC1_TEMP /*WHERE TC1_PERIODO=202204*/) T
HAVING COUNT(T.X) > 1 
GROUP BY T.X; --NO DEBE ARROJAR NINGUN RESULTADO



--1046636

SELECT * FROM QA_TTC1 WHERE TC1_PERIODO=202204 AND TC1_TC1='1046636';

DELETE FROM QA_TTC1 WHERE TC1_PERIODO=202204 AND TC1_TC1='1046636' AND TC1_TIPCONEX='T';
COMMIT;

--VERIFICAR QUE EL TIPO DE CONEXION
SELECT *
FROM QA_TTC1
WHERE TC1_TIPCONEX IN ('1','2')
AND TC1_PERIODO=202204;-- NO DEBE ARROJAR NINGUN RESULTADO



--VALIDAR QUE LOS CODIGOS SEAN LOS PERTENECIENTES A LOS NUEVOS DE REPOSICION
SELECT DISTINCT TC1_CODCONEX,TC1_IUA 
FROM QA_TTC1_TEMP /*WHERE TC1_PERIODO=202204*/
WHERE TC1_TIPCONEX='T'
MINUS
SELECT DISTINCT TT2_CODIGOELEMENTO,TT2_CODE_IUA FROM QA_TTT2_REGISTRO
WHERE TT2_ESTADO IN ('OPERACION','CONSTRUCCION')
;


SELECT * FROM QA_TTC1_TEMP  
WHERE TC1_CODCONEX IN (SELECT DISTINCT TT2_CODIGOELEMENTO
                        FROM(
                            SELECT DISTINCT TT2_CODIGOELEMENTO,TT2_CODE_IUA FROM QA_TTT2_REGISTRO
                            WHERE TT2_ESTADO IN ('OPERACION','CONSTRUCCION')
                            MINUS
                            SELECT DISTINCT TC1_CODCONEX,TC1_IUA 
                            FROM QA_TTC1_TEMP WHERE TC1_TIPCONEX='T'
                        ));


SELECT DISTINCT TT2_CODIGOELEMENTO
FROM(
    SELECT DISTINCT TT2_CODIGOELEMENTO,TT2_CODE_IUA FROM QA_TTT2_REGISTRO
    WHERE TT2_ESTADO IN ('OPERACION','CONSTRUCCION')
    MINUS
    SELECT DISTINCT TC1_CODCONEX,TC1_IUA 
    FROM QA_TTC1 WHERE TC1_PERIODO=202204
    AND TC1_TIPCONEX='T'
   );

--
SELECT MAX(TC1_PERIODO)
FROM QA_TTC1;


--INSERTAR LA INFORMACION EN LA TABLA QA_TTC1
INSERT INTO QA_TTC1
SELECT * FROM QA_TTC1_TEMP; --584.599 filas insertadas.
COMMIT;

SELECT * FROM QA_TTC1
WHERE TC1_PERIODO=202205;

--INFORMAR Y DAR LUZ VERDE PARA LA REALIZACION DEL AJUSTE Y EL PRIMER REPORTE DEL PERIODO (m)

-----------------------------------------------------------COMPARTIR FORMATO TC1 COMERCIALIZADORA MAS TARDAR DIA 7 DE CADA MES-----------------------------------------


--EXTRACCION DEL ARCHIVO PARA COMENTARIOS COMERCIALIZADORAS
SELECT TC1_TC1 AS "NIU"
,TC1_IUA AS "Codigo de Conexión"
,TC1_TIPCONEX AS "Tipo de Conexión"
,TC1_NT AS "Nivel de Tensión del usuario"
,TC1_NTP AS "Nivel de Tensión"
,(TC1_PROPACTIV) AS "% propiedad del Activo"
,(TC1_CONEXRED) AS "Conexión Red"
,(TC1_IDCOMER) AS "ID Comercializador"
,(TC1_IDMERC) AS "ID Mercado"
,(TC1_GC) AS "GRUPO CALIDAD"
,TC1_CODFRONCOM AS "Código Frontera Comercial"
,(TC1_CODCIRC) AS "Código Circuito o Línea"
,TC1_CODTRANSF AS "CODIGO TRANFORMADOR TT2"
,(TC1_CODDANE) AS "Código DANE NIU"
,(TC1_UBIC) AS "Ubicación"
,TC1_DIREC AS "Direccion"
,(TC1_CONESP) AS "Condiciones Especiales"
,(TC1_CODARESP) AS "TIPO DE AREA ESPECIAL"
,(TC1_TIPARESP) AS "CODIGO DE AREA ESPECIAL"
,(TC1_ESTSECT) AS "Estrato - Sector"
,TC1_ALTITUD AS "Altitud"
,TC1_LONGITUD AS "LONGITUD"
,TC1_LATITUD AS "LATITUD"
,(TC1_AUTOGEN) AS "Autogenerador"
,TC1_EXPENER AS "Exporta Energía"
,TC1_CAPAUTOGENR AS "Capacidad Autogenerador kw"
,TC1_TIPGENR AS "Tipo de Generación"
,TC1_CODFRONEXP AS "Codigo frontera Autogenarador"
,TC1_FENTGEN AS "Fecha Entrada en Operación"
,TC1_CONTRESP AS "Contrato de Respaldo"
,TC1_CAPCONTRESP AS "Capacidad Contrato de Respaldo"
FROM  QA_TTC1_TEMP 
WHERE   TC1_IDCOMER <> '604';


-----------------------------------------------------------ACTUALIZACION PARA TC1 Y EL CALCULO DE INDICADORES-------------------------------------------------------------------------


SELECT * FROM QA_TTC1_TEMP;

DELETE FROM QA_TTC1_TEMP;
COMMIT;

--TRANSFORMADORES QUE FUERON ELIMINADOS DEL TC1 DESDE EL SEGUNDO DIA HABIL DEL MES
SELECT DISTINCT TC1_CODCONEX FROM BRAE.QA_TTC1 WHERE TC1_PERIODO=202303
MINUS
SELECT DISTINCT TC1_CODCONEX FROM QA_TTC1_TEMP;

--TRAFOS PARA AGREGAR AL TC1 EN CASO DE QUE HAYAN INGRESADO NUEVOS
SELECT DISTINCT TC1_CODCONEX FROM BRAE.QA_TTC1_TEMP
MINUS
SELECT DISTINCT TC1_CODCONEX FROM QA_TTC1 WHERE TC1_PERIODO=202303;

--TRAFOS AFECTADOS EN EL MES DEL PERIODO DEL TC1
SELECT DISTINCT I.TRAFO FROM OMS.INTERUPC I
LEFT OUTER JOIN OMS.MANIOBRAS M
ON M.CODE = I.MINICIAL
WHERE  M.CAUSA <> 'PRUEBA'
AND I.TYPEEQUIP = 'Transformer'
AND I.FINICIAL >= TO_DATE('01/12/2021','DD/MM/YYYY')
AND I.FINICIAL  <  TO_DATE('01/01/2022','DD/MM/YYYY')
AND I.TRAFO='4T00361';

--VALIDADION QUE LOS QUE SE DESEAN AGREGAR NO TIENEN AFECTACIONES EN EL PERIODO
SELECT DISTINCT I.TRAFO
FROM OMS.INTERUPC I
LEFT OUTER JOIN OMS.MANIOBRAS M
ON M.CODE = I.MINICIAL
WHERE  M.CAUSA <> 'PRUEBA'
AND I.TYPEEQUIP = 'Transformer'
AND I.FINICIAL >= TO_DATE('01/12/2021','DD/MM/YYYY')
AND I.FINICIAL  <  TO_DATE('01/01/2022','DD/MM/YYYY')
AND I.TRAFO IN (SELECT DISTINCT TC1_CODCONEX FROM QA_TTC1_TEMP
              MINUS
               SELECT DISTINCT TC1_CODCONEX FROM QA_TTC1 WHERE TC1_PERIODO=202112
               ); --VACIA

--VALIDAR QUE LOS CAMPOS IUA DE LA NEUVA ACTUALIZACION SEAN LOS MISMOS QUE AL ACTAULIZACION ANTERIOR
SELECT TC1_CODCONEX
FROM (
        SELECT DISTINCT TC1_CODCONEX,TC1_IUA FROM QA_TTC1_TEMP
        MINUS
        SELECT DISTINCT TC1_CODCONEX,TC1_IUA FROM QA_TTC1 WHERE TC1_PERIODO=202303
     )
MINUS
(SELECT DISTINCT TC1_CODCONEX FROM QA_TTC1_TEMP
MINUS
SELECT DISTINCT TC1_CODCONEX FROM QA_TTC1 WHERE TC1_PERIODO=202303)
;--VACIA



SELECT * FROM QA_TTC1_TEMP WHERE TC1_TIPCONEX='P'; 

--VALIDAR QUE NO EXISTA UN TRANSFORMADOR CON DIFERENTES IUA
SELECT T.X, COUNT(T.X)
FROM(
SELECT DISTINCT TC1_CODCONEX AS X,TC1_IUA
FROM QA_TTC1_TEMP) T
HAVING COUNT(T.X) > 1 
GROUP BY T.X
; --SE PRESENTA UNICAMENTE EL CASO ESPECIAL DE LOS USAURIOS STN

--VERIFICACION EN CASO DE QUE EXISTAN TRANSFORMADORES CON DIFERENTES IUA
SELECT * FROM QA_TTC1_TEMP
WHERE TC1_CODCONEX IN (
                        SELECT T.X
                        FROM(
                        SELECT DISTINCT TC1_CODCONEX AS X,TC1_IUA
                        FROM QA_TTC1 WHERE TC1_PERIODO=202301) T
                        HAVING COUNT(T.X) > 1 
                        GROUP BY T.X
                      );

--VALIDAR QUE NO EXISTA UN TRANSFORMDAOR CON DIFERENTE IUL
SELECT T.X, COUNT(T.X)
FROM(
SELECT DISTINCT TC1_CODCONEX AS X,TC1_CODCIRC
FROM QA_TTC1_TEMP
WHERE TC1_TIPCONEX='T'
--AND TC1_PERIODO=202207
AND TC1_CODCONEX NOT LIKE 'ALPM%') T
HAVING COUNT(T.X) > 1
GROUP BY T.X
;



--DESPUES DE HABER VALIDADO LAS DOS TABLAS QA_TTC1 CON QA_TTC1_TEMP
--BORRAR QA_TTC1 SOLO EL PERIODO
--INSERTAR QA_TTC1_TEMP EN QA_TTC1

SELECT * FROM QA_TTC1_TEMP;

--CAMBIAR LOS VALORES DE TC1_TIPCONEX
UPDATE QA_TTC1_TEMP
SET TC1_TIPCONEX='P'
WHERE TC1_TIPCONEX='1';--7 filas actualizadas.
--COMMIT;
UPDATE QA_TTC1_TEMP
SET TC1_TIPCONEX='T'
WHERE TC1_TIPCONEX='2';-- 584.684 filas actualizadas
--COMMIT;

SELECT count(*) FROM QA_TTC1
WHERE TC1_PERIODO=202303; --601.108  Filas

DELETE FROM QA_TTC1
WHERE TC1_PERIODO=202303; -- 601,108 rows affected in 1 m 12 s 220 ms
COMMIT;

--INSERTAR QA_TTC1_TEMP A QA_TTC1
INSERT INTO QA_TTC1
SELECT * FROM QA_TTC1_TEMP; --598.469 filas insertadas.

COMMIT;

--Verificacion de la cantidad insertada
SELECT COUNT(*) FROM QA_TTC1 WHERE TC1_PERIODO=202303; --601.127 filas insertadas
--OK
--END; PROCEDA AL CALCULO DE INDICADORES
