CREATE OR REPLACE PROCEDURE BRAE.QA_PTC2_REGISTRO(FECHAOPERACION DATE)
AS

  TYPE T_QA_TTC2_REGISTRO IS TABLE OF QA_TTC2_REGISTRO%ROWTYPE;
  V_QA_TTC2_REGISTRO T_QA_TTC2_REGISTRO;

BEGIN 
	--BORRAR TABLA DE OBSERVACIONES 
	DELETE FROM QA_TTC2_OBS
	WHERE ROWNUM >= 0;
	COMMIT;

	--VALIDACION DEL EXISTENCIA DE USUARIOS DEL TC2 EN TC1
    SELECT 	TC2_NIU
		,	TC2_INFO_PREDIAL
		,	TC2_CEDULA_CATASTRAL
		,	TC2_TIPO_FACTURA
		,	TC2_ID_FACTURA
		,	TC2_TIPO_TARIFA
		,	TC2_TIPO_LECTURA
		,	TC2_CONSUMO_USR
		,	TC2_CONSUMO_SUBS
		,	TC2_VALOR_SUBS_USR
		,	TC2_VALOR_REFACT_SUBS_USR
		,	TC2_VALOR_FOES_APLI_CONS
		,	TC2_VALOR_REFACT_FOES_APLI
		,	TC2_VALOR_CONTRIBUCION
		,	TC2_VALOR_REFACT_CONT
		,	TC2_TVC
		,	TC2_VC
		,	TC2_VCD
		,	TC2_VCF
		,	TC2_CEC_KWH
		,	TC2_CONPU
		,	TC2_THC
		,	TC2_HC
		,	TC2_REFACT_COMPENSACION
		,	TC2_TIPO_MEDIDOR
		,	TC2_TARIFA_APLICADA
		,	TC2_FECHA_PUB_TARIFA_APLI
		,	TC2_VALOR_SUBSIDIO_REC
		,	TC2_ID_MERCADO
		,	TC2_AGNIO_REPORTE
		,	TC2_MES_REPORTE
		,   'Usuario no existe en TC1' AS TC2_OBS
    BULK COLLECT INTO V_QA_TTC2_REGISTRO
    FROM QA_TTC2_REGISTRO
    WHERE TC2_NIU IN (
						SELECT DISTINCT TO_CHAR(TC2_NIU) FROM QA_TTC2_REGISTRO
						WHERE TC2_MES_REPORTE = TO_NUMBER(TO_CHAR(FECHAOPERACION,'MM'))
						AND TC2_AGNIO_REPORTE = TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))
					MINUS
						SELECT DISTINCT TC1_TC1 FROM QA_TTC1
						WHERE TC1_PERIODO = TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYYMM'))
     				 )
    AND TC2_MES_REPORTE = TO_NUMBER(TO_CHAR(FECHAOPERACION,'MM'))
	AND TC2_AGNIO_REPORTE = TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))
	;

    IF V_QA_TTC2_REGISTRO IS NOT EMPTY THEN
         FOR i IN V_QA_TTC2_REGISTRO.FIRST..V_QA_TTC2_REGISTRO.LAST LOOP
               INSERT INTO BRAE.QA_TTC2_OBS
               VALUES V_QA_TTC2_REGISTRO(i);
         END LOOP;
         COMMIT;
    END IF;
   
   --VALIDACION INFO PREDIAL VS CEDULA CATASTRAL
   	   V_QA_TTC2_REGISTRO.DELETE;
       SELECT 	TC2_NIU
		,	TC2_INFO_PREDIAL
		,	TC2_CEDULA_CATASTRAL
		,	TC2_TIPO_FACTURA
		,	TC2_ID_FACTURA
		,	TC2_TIPO_TARIFA
		,	TC2_TIPO_LECTURA
		,	TC2_CONSUMO_USR
		,	TC2_CONSUMO_SUBS
		,	TC2_VALOR_SUBS_USR
		,	TC2_VALOR_REFACT_SUBS_USR
		,	TC2_VALOR_FOES_APLI_CONS
		,	TC2_VALOR_REFACT_FOES_APLI
		,	TC2_VALOR_CONTRIBUCION
		,	TC2_VALOR_REFACT_CONT
		,	TC2_TVC
		,	TC2_VC
		,	TC2_VCD
		,	TC2_VCF
		,	TC2_CEC_KWH
		,	TC2_CONPU
		,	TC2_THC
		,	TC2_HC
		,	TC2_REFACT_COMPENSACION
		,	TC2_TIPO_MEDIDOR
		,	TC2_TARIFA_APLICADA
		,	TC2_FECHA_PUB_TARIFA_APLI
		,	TC2_VALOR_SUBSIDIO_REC
		,	TC2_ID_MERCADO
		,	TC2_AGNIO_REPORTE
		,	TC2_MES_REPORTE
		,   'Error de inconsistencia entre INFO PREDIAL y CEDULA CATASTRAL' AS TC2_OBS
    BULK COLLECT INTO V_QA_TTC2_REGISTRO
	FROM QA_TTC2_REGISTRO
	WHERE TC2_MES_REPORTE = TO_NUMBER(TO_CHAR(FECHAOPERACION,'MM'))
	AND TC2_AGNIO_REPORTE = TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))
	AND TC2_NIU||TC2_ID_FACTURA  NOT IN (
										SELECT TC2_NIU||TC2_ID_FACTURA  
										FROM QA_TTC2_REGISTRO
										WHERE TC2_MES_REPORTE = TO_NUMBER(TO_CHAR(FECHAOPERACION,'MM'))
										AND TC2_AGNIO_REPORTE = TO_NUMBER(TO_CHAR(FECHAOPERACION,'YYYY'))
										AND (  TC2_INFO_PREDIAL = 1 AND LENGTH(TC2_CEDULA_CATASTRAL) BETWEEN 21 AND 56
											OR TC2_INFO_PREDIAL = 2 AND LENGTH(TC2_CEDULA_CATASTRAL) <= 30
											OR TC2_INFO_PREDIAL = 3 AND TC2_CEDULA_CATASTRAL = '0'
											OR TC2_INFO_PREDIAL = 4 AND TC2_CEDULA_CATASTRAL = '1'
										    OR TC2_INFO_PREDIAL = 5 AND LENGTH(TC2_CEDULA_CATASTRAL) <= 11
										    )
										)
	
	;

    IF V_QA_TTC2_REGISTRO IS NOT EMPTY THEN
         FOR i IN V_QA_TTC2_REGISTRO.FIRST..V_QA_TTC2_REGISTRO.LAST LOOP
               INSERT INTO BRAE.QA_TTC2_OBS
               VALUES V_QA_TTC2_REGISTRO(i);
         END LOOP;
         COMMIT;
    END IF;
 	
END QA_PTC2_REGISTRO;