ï»¿--ACTUALIZACION DE LA TABLA REGISTRO PARA EL CAMPO TC1 -by Edwin Silva Salas
UPDATE QA_TFDDREGISTRO
SET FDD_PERIODO_TC1=202005
WHERE FDD_FINICIAL >= TO_DATE('01/05/2020','DD/MM/YYYY')
;

SELECT DISTINCT FDD_PERIODO_TC1 FROM QA_TFDDREGISTRO
WHERE FDD_FINICIAL >= TO_DATE('01/05/2020','DD/MM/YYYY');



-- VERIFICA DIFERENCIA DE LAS CAUSAS Y FECHAS DE EVENTOS ENTRE QA_TFDDREGISTRO VS AGREGADOS POR TC1
SELECT FDD_CODIGOEVENTO,FDD_CAUSA, FDD_CAUSA_CREG,FDD_CAUSA_SSPD,FDD_FINICIAL,COUNT(FDD_CODIGOEVENTO) AS CANTIDAD
    FROM QA_TFDDREGISTRO WHERE FDD_CODIGOEVENTO IN (
                                          SELECT FDD_CODIGOEVENTO FROM (
                                                                        SELECT X.FDD_CODIGOEVENTO,COUNT(X.FDD_CODIGOEVENTO) AS CANTIDAD
                                                                        FROM (SELECT  DISTINCT(FDD_CODIGOEVENTO),FDD_CAUSA||FDD_CAUSA_CREG AS X
                                                                              FROM QA_TFDDREGISTRO) X
                                                                        HAVING COUNT(X.FDD_CODIGOEVENTO)>1
                                                                        GROUP BY X.FDD_CODIGOEVENTO
                                                                        ORDER BY 1))
GROUP BY FDD_CODIGOEVENTO,FDD_CAUSA,FDD_CAUSA_CREG,FDD_CAUSA_SSPD,FDD_FINICIAL
ORDER BY 1;

--COMPROBACION DE NR NO AJUSTADOS
SELECT FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO
FROM QA_TFDDMODIFICADOS
WHERE FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO  IN (SELECT FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO FROM QA_TFDDREGISTRO WHERE FDD_TIPOCARGA='NR' AND FDD_AJUSTADO='N');

--COMPROBACION DE TC1 NO AJUSTADOS
SELECT FDD_CODIGOEVENTO,FDD_CODIGOELEMENTO,FDD_CAUSA_CREG, FDD_ORIGEN
FROM QA_TFDDMODIFICADOS
WHERE FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO  IN (SELECT FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO FROM QA_TFDDREGISTRO WHERE FDD_TIPOCARGA='AJUSTE TC1' AND FDD_AJUSTADO='N');

--COMPROBACION DE REGISTROS ELIMINADOS POR TC1-- NO AJUSTADOS
SELECT FDD_CODIGOEVENTO,FDD_CODIGOELEMENTO,FDD_CAUSA_CREG, FDD_ORIGEN
FROM QA_TFDDMODIFICADOS
WHERE FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO  IN (SELECT FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO FROM QA_TFDDREGISTRO WHERE FDD_TIPOAJUSTE=3 AND FDD_AJUSTADO='N')
ORDER BY FDD_CODIGOEVENTO

;
-- COMPRBAR QUE TODOS EVENTOS YA ESTAN EN LA TABLA REGISTRO, PORQUE SON AJUSTES TC1
SELECT DISTINCT FDD_CODIGOEVENTO
FROM QA_TFDDREGISTRO
WHERE FDD_CODIGOEVENTO IN (SELECT DISTINCT FDD_CODIGOEVENTO
                           FROM QA_TFDDPRELIMINAR_NR)
MINUS
SELECT DISTINCT FDD_CODIGOEVENTO
FROM QA_TFDDPRELIMINAR_NR;

-- SE ACTUALIZA LA TABLA PRELIMINAR_NR PARA MARCAR LOS TC1 <AGREGAR>
UPDATE QA_TFDDPRELIMINAR_NR
SET FDD_TIPOCARGA='AJUSTE TC1',
    FDD_TIPOAJUSTE=1;

-- ACTULIZACION DE LOS ELEMENTOS ELIMINADOS POR AJSUTE TC1
UPDATE QA_TFDDREGISTRO
SET FDD_TIPOAJUSTE=3
WHERE FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO IN (
SELECT FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO FROM QA_TFDDREGISTRO
WHERE FDD_CODIGOELEMENTO NOT IN (SELECT DISTINCT(TC1_CODCONEX) FROM QA_TTC1 WHERE TC1_PERIODO=202005)
AND FDD_FINICIAL >=TO_DATE('01/05/2020','DD/MM/YYYY'));


-- GENENAR TT9
-- MODIFICADOS
SELECT 161 AS COD_MERCADO
      ,TO_NUMBER(M.FDD_CODIGOEVENTO) AS CODIGO_EVENTO
      ,TO_CHAR(M.FDD_FINICIAL,'DD-MM-YYYY HH24:MI:SS') AS FECHA_INICIAL_HORA
      ,T.FDD_IUA AS CODIGO_ELEMENTO
      ,1 AS TIPO_ELEMENTO
      ,(CASE WHEN ((SELECT DISTINCT (E.FDD_CODIGOEVENTO) FROM QA_TFDDMODIFICADOS@BRAEPROD E WHERE E.FDD_CAUSA_CREG=0 AND E.FDD_ORIGEN='OMS')=M.FDD_CODIGOEVENTO) THEN (3) ELSE (2) END) AS AJUSTE
      ,'MODIFICADOS' AS FUENTE_AJUSTE
FROM QA_TFDDMODIFICADOS@BRAEPROD M
LEFT OUTER JOIN (SELECT FDD_CODIGOEVENTO,FDD_CODIGOELEMENTO,FDD_IUA FROM QA_TFDDREGISTRO@BRAEPROD ) T ON T.FDD_CODIGOEVENTO||T.FDD_CODIGOELEMENTO=M.FDD_CODIGOEVENTO||M.FDD_CODIGOELEMENTO
WHERE FDD_ORIGEN='QOS'
AND M.FDD_CODIGOEVENTO||M.FDD_CODIGOELEMENTO NOT IN (SELECT FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO FROM QA_TFDDREGISTRO@BRAEPROD WHERE FDD_TIPOCARGA='AJUSTE TC1' AND FDD_AJUSTADO='N')--PARA NO TRAER EN ESTA CARGA LOS AGREAGADOS POR TC1
AND M.FDD_CODIGOEVENTO||M.FDD_CODIGOELEMENTO NOT IN (SELECT FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO FROM QA_TFDDREGISTRO@BRAEPROD WHERE FDD_TIPOAJUSTE=3 AND FDD_AJUSTADO='N')--PARA NO TRAER EN ESTA CARGA LOS ELIMINADOS POR TC1
UNION ALL
-- AGREAGADOS NR
SELECT 161 AS COD_MERCADO
      ,TO_NUMBER(FDD_CODIGOEVENTO) AS CODIGO_EVENTO
      ,NULL AS FECHA_INICIAL_HORA
      ,FDD_IUA AS CODIGO_ELEMENTO
      ,1 AS TIPO_ELEMENTO
      ,2 AS FDD_TIPOAJUSTE
      ,'NR' AS FUENTE_AJUSTE
FROM QA_TFDDREGISTRO@BRAEPROD
WHERE FDD_TIPOCARGA='NR'
AND FDD_AJUSTADO='N'
UNION ALL
--AGREGADOS POR TC1
SELECT 161 AS COD_MERCADO
      ,TO_NUMBER(FDD_CODIGOEVENTO) AS CODIGO_EVENTO
      ,TO_CHAR(FDD_FINICIAL,'DD-MM-YYYY HH24:MI:SS') AS FECHA_INICIAL_HORA
      ,FDD_IUA AS CODIGO_ELEMENTO
      ,1 AS TIPO_ELEMENTO
      ,FDD_TIPOAJUSTE AS AJUSTE
      ,'AJUSTE TC1 ADD' AS FUENTE_AJUSTE
FROM QA_TFDDREGISTRO@BRAEPROD
WHERE FDD_TIPOCARGA='AJUSTE TC1'
AND FDD_AJUSTADO='N'
UNION ALL
-- ELIMINADOS POR TC1
SELECT 161 AS COD_MERCADO
      ,TO_NUMBER(FDD_CODIGOEVENTO) AS CODIGO_EVENTO
      ,TO_CHAR(FDD_FINICIAL,'DD-MM-YYYY HH24:MI:SS') AS FECHA_INICIAL_HORA
      ,FDD_IUA AS CODIGO_ELEMENTO
      ,1 AS TIPO_ELEMENTO
      ,FDD_TIPOAJUSTE AS AJUSTE
      ,'AJUSTE TC1 DEL' AS FUENTE_AJUSTE
FROM QA_TFDDREGISTRO@BRAEPROD
WHERE FDD_TIPOAJUSTE=3
AND FDD_AJUSTADO='N';



--  Reporte_Ajustes_Abril_2020
--ADICIONA MODIFICADOS
SELECT TO_NUMBER(M.FDD_CODIGOEVENTO) AS FDD_CODIGOEVENTO,
       TO_CHAR(M.FDD_FINICIAL,'DD/MM/YYYY HH24:MI:SS') AS FDD_FINCIAL,
        TO_CHAR((CASE WHEN(T.FDD_CONTINUIDAD='S') THEN(NULL) ELSE(M.FDD_FFINAL) END),'DD/MM/YYYY HH24:MI:SS') AS FDD_FFINAL,
       T.FDD_IUA,
       1 AS FDD_TIPOELEMENTO,
       (CASE WHEN TO_NUMBER(M.FDD_CAUSA_CREG)=0
             THEN TO_NUMBER((SELECT DISTINCT (E.FDD_CAUSA_CREG) FROM QA_TFDDMODIFICADOS@BRAEPROD E WHERE E.FDD_CODIGOEVENTO=M.FDD_CODIGOEVENTO AND E.FDD_ORIGEN='QOS'))
             ELSE TO_NUMBER(M.FDD_CAUSA_CREG)
        END) AS FDD_CAUSA,
       T.FDD_CONTINUIDAD,
       0 FDD_EXCLUIDOZNI,
       0 FDD_AFECTACONGEN,
      (CASE WHEN T.FDD_USUARIOAP='N' THEN 0 ELSE 1 END) AS FDD_USUARIOAP,
      (CASE WHEN TO_NUMBER(M.FDD_CAUSA_CREG)=0 THEN 3 ELSE 2 END) AS FDR_TIPOAJUSTE,
      TO_CHAR(:RADICADO_SSPD) AS FDR_RADICADO
      FROM QA_TFDDMODIFICADOS@BRAEPROD M
      LEFT OUTER JOIN QA_TFDDREGISTRO@BRAEPROD T ON T.FDD_CODIGOEVENTO||T.FDD_CODIGOELEMENTO=M.FDD_CODIGOEVENTO||M.FDD_CODIGOELEMENTO
WHERE FDD_ORIGEN='OMS'
AND M.FDD_CODIGOEVENTO||M.FDD_CODIGOELEMENTO NOT IN (SELECT FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO FROM QA_TFDDREGISTRO@BRAEPROD WHERE FDD_TIPOCARGA='AJUSTE TC1' AND FDD_AJUSTADO='N')--PARA NO TRAER EN ESTA CARGA LOS AGREAGADOS POR TC1
AND M.FDD_CODIGOEVENTO||M.FDD_CODIGOELEMENTO NOT IN (SELECT FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO FROM QA_TFDDREGISTRO@BRAEPROD WHERE FDD_TIPOAJUSTE=3 AND FDD_AJUSTADO='N')--PARA NO TRAER EN ESTA CARGA LOS ELIMINADOS POR TC1
UNION ALL
--ADICIONA NR'S
SELECT TO_NUMBER(FDD_CODIGOEVENTO) AS FDD_CODIGOEVENTO,
       TO_CHAR(FDD_FINICIAL,'DD/MM/YYYY HH24:MI:SS') AS FFINICIAL,
       TO_CHAR(FDD_FFINAL,'DD/MM/YYYY HH24:MI:SS') AS FDD_FFINAL,
       FDD_IUA,
       1 AS FDD_TIPOELEMENTO,
       TO_NUMBER(FDD_CAUSA_CREG),
       FDD_CONTINUIDAD,
       0 FDD_EXCLUIDOZNI,
       0 FDD_AFECTACONGEN,
       (CASE WHEN FDD_USUARIOAP='N' THEN 0 ELSE 1 END) AS FDD_USUARIOAP,
       2 AS FDD_TIPOAJUSTE,
       TO_CHAR(:RADICADO_SSPD) AS FDD_RADICADO
FROM QA_TFDDREGISTRO@BRAEPROD
WHERE FDD_TIPOCARGA='NR' AND FDD_AJUSTADO='N'
UNION ALL
--AGREGADOS POR TC1
SELECT TO_NUMBER(FDD_CODIGOEVENTO) AS FDD_CODIGOEVENTO,
       TO_CHAR(FDD_FINICIAL,'DD/MM/YYYY HH24:MI:SS') AS FFINICIAL,
       TO_CHAR(FDD_FFINAL,'DD/MM/YYYY HH24:MI:SS') AS FDD_FFINAL,
       FDD_IUA,
       1 AS FDD_TIPOELEMENTO,
       TO_NUMBER(CASE WHEN(FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO=M.LLAVE) THEN(M.CAUSA_CREG) ELSE(FDD_CAUSA_CREG) END) AS FDD_CUASA_CREG,--LLAMAR LA CAUSA DEL OMS-MODIFICADOS
       FDD_CONTINUIDAD,
       0 FDD_EXCLUIDOZNI,
       0 FDD_AFECTACONGEN,
       (CASE WHEN FDD_USUARIOAP='N' THEN 0 ELSE 1 END) AS FDD_USUARIOAP,
       FDD_TIPOAJUSTE,
       TO_CHAR(:RADICADO_SSPD) AS FDD_RADICADO
FROM QA_TFDDREGISTRO@BRAEPROD
LEFT OUTER JOIN (SELECT FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO AS LLAVE, FDD_CAUSA_CREG AS CAUSA_CREG FROM  QA_TFDDMODIFICADOS@BRAEPROD WHERE FDD_ORIGEN='OMS') M ON M.LLAVE = FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO
WHERE FDD_TIPOCARGA='AJUSTE TC1'
AND FDD_AJUSTADO='N'
UNION ALL
--ELIMINADOS POR TC1
SELECT TO_NUMBER(FDD_CODIGOEVENTO) AS FDD_CODIGOEVENTO,
       TO_CHAR(FDD_FINICIAL,'DD/MM/YYYY HH24:MI:SS') AS FFINICIAL,
       TO_CHAR(FDD_FFINAL,'DD/MM/YYYY HH24:MI:SS') AS FDD_FFINAL,
       FDD_IUA,
       1 AS FDD_TIPOELEMENTO,
       TO_NUMBER(FDD_CAUSA_CREG),--- CUANDO SE VA A ELIMINAR SE DEJA CON LA CAUSA ANTERIOR
       FDD_CONTINUIDAD,
       0 FDD_EXCLUIDOZNI,
       0 FDD_AFECTACONGEN,
       (CASE WHEN FDD_USUARIOAP='N' THEN 0 ELSE 1 END) AS FDD_USUARIOAP,
       FDD_TIPOAJUSTE,
       TO_CHAR(:RADICADO_SSPD) AS FDD_RADICADO
FROM QA_TFDDREGISTRO@BRAEPROD
WHERE FDD_TIPOAJUSTE=3
AND FDD_AJUSTADO='N'

--COMPROBACION DE DIFERENCIAS DE LOS CAMPOS FINICIAL, FFINAL DE LOS EVENTOS MODIFICADOS EXEPTO LOS NR
SELECT TO_NUMBER(M.FDD_CODIGOEVENTO) AS FDD_CODIGOEVENTO
       ,TO_DATE(TO_CHAR(M.FDD_FINICIAL,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') AS FDD_FINCIAL
       ,TO_DATE(TO_CHAR(M.FDD_FFINAL,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') AS FDD_FFINAL
       --,TO_NUMBER(M.FDD_CAUSA_CREG) AS FDD_CAUSA
      FROM QA_TFDDMODIFICADOS M
      LEFT OUTER JOIN QA_TFDDREGISTRO T ON T.FDD_CODIGOEVENTO||T.FDD_CODIGOELEMENTO=M.FDD_CODIGOEVENTO||M.FDD_CODIGOELEMENTO
WHERE FDD_ORIGEN='OMS'
MINUS
SELECT TO_NUMBER(M.FDD_CODIGOEVENTO) AS FDD_CODIGOEVENTO
       ,TO_DATE(TO_CHAR(M.FDD_FINICIAL,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') AS FDD_FINCIAL
       ,TO_DATE(TO_CHAR(M.FDD_FFINAL,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS') AS FDD_FFINAL
       --,TO_NUMBER(M.FDD_CAUSA_CREG) AS FDD_CAUSA
      FROM QA_TFDDMODIFICADOS M
      LEFT OUTER JOIN QA_TFDDREGISTRO T ON T.FDD_CODIGOEVENTO||T.FDD_CODIGOELEMENTO=M.FDD_CODIGOEVENTO||M.FDD_CODIGOELEMENTO
WHERE FDD_ORIGEN='QOS';

---- CANTIDAD DE EVENTOS MODIFICADOS
SELECT COUNT(DISTINCT M.FDD_CODIGOEVENTO)
      FROM QA_TFDDMODIFICADOS M
      LEFT OUTER JOIN QA_TFDDREGISTRO T ON T.FDD_CODIGOEVENTO||T.FDD_CODIGOELEMENTO=M.FDD_CODIGOEVENTO||M.FDD_CODIGOELEMENTO
WHERE FDD_ORIGEN='OMS'; --- RESULTADOS 13 registros.

---- CANTIDAD DE REGISTROS MODIFICADOS
SELECT COUNT(M.FDD_CODIGOEVENTO)
      FROM QA_TFDDMODIFICADOS M
      LEFT OUTER JOIN QA_TFDDREGISTRO T ON T.FDD_CODIGOEVENTO||T.FDD_CODIGOELEMENTO=M.FDD_CODIGOEVENTO||M.FDD_CODIGOELEMENTO
WHERE FDD_ORIGEN='OMS'; ---

--CANTIDAD DE EVENTOS NR
SELECT COUNT(DISTINCT FDD_CODIGOEVENTO)
FROM QA_TFDDREGISTRO
WHERE FDD_TIPOCARGA='NR' AND FDD_AJUSTADO='N';

--CANTIDAD DE REGISTROS NR
SELECT COUNT(FDD_CODIGOEVENTO)
FROM QA_TFDDREGISTRO
WHERE FDD_TIPOCARGA='NR' AND FDD_AJUSTADO='N';

----TABLA DINAMICA CAUSAS MODIFICADAS
SELECT TO_CHAR('MODIFICADOS') AS TABLA
      ,TO_NUMBER(T.FDD_CAUSA_CREG) AS CAUSA_QOS
      ,TO_NUMBER(M.FDD_CAUSA_CREG) AS CAUSA_OMS
      ,COUNT (M.FDD_CODIGOEVENTO) AS CANTIDAD_REGISTROS
      ,COUNT(DISTINCT M.FDD_CODIGOEVENTO) AS CANTIDAD_EVENTOS
      FROM QA_TFDDMODIFICADOS M
      LEFT OUTER JOIN QA_TFDDREGISTRO T ON T.FDD_CODIGOEVENTO||T.FDD_CODIGOELEMENTO=M.FDD_CODIGOEVENTO||M.FDD_CODIGOELEMENTO
      WHERE FDD_ORIGEN='OMS'
      AND M.FDD_CODIGOEVENTO||M.FDD_CODIGOELEMENTO NOT IN (SELECT FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO FROM QA_TFDDREGISTRO WHERE FDD_TIPOCARGA='AJUSTE TC1' AND FDD_AJUSTADO='N')--PARA NO TRAER EN ESTA CARGA LOS AGREAGADOS POR TC1
      AND M.FDD_CODIGOEVENTO||M.FDD_CODIGOELEMENTO NOT IN (SELECT FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO FROM QA_TFDDREGISTRO WHERE FDD_TIPOAJUSTE=3 AND FDD_AJUSTADO='N')--PARA NO TRAER EN ESTA CARGA LOS ELIMINADOS POR TC1
      GROUP BY 'MODIFICADOS',T.FDD_CAUSA_CREG,M.FDD_CAUSA_CREG
UNION ALL
SELECT TO_CHAR('REGISTRO_NR') AS TABLA
      ,TO_NUMBER(R.FDD_CAUSA_CREG) AS CAUSA_QOS
      ,TO_NUMBER(C.CAUSA015) AS CAUSA_OMS
      ,COUNT(R.FDD_CODIGOEVENTO) AS CANTIDAD_REGISTROS
      ,COUNT(DISTINCT R.FDD_CODIGOEVENTO) AS CANTIDAD_EVENTOS
          FROM QA_TFDDREGISTRO R
      LEFT OUTER JOIN OMS.MANIOBRAS M ON M.CODE=R.FDD_CODIGOEVENTO
      LEFT OUTER JOIN OMS.CAUSAS C ON C.CODE=M.CAUSA
      WHERE R.FDD_TIPOCARGA='NR' AND R.FDD_AJUSTADO='N'
      GROUP BY 'REGISTRO_NR',R.FDD_CAUSA_CREG,C.CAUSA015
UNION ALL
SELECT TO_CHAR('AJUSTE TC1 ADD') AS TABLA
      ,TO_NUMBER(R.FDD_CAUSA_CREG) AS CAUSA_QOS
      ,TO_NUMBER(C.CAUSA015) AS CAUSA_OMS
      ,COUNT(R.FDD_CODIGOEVENTO) AS CANTIDAD_REGISTROS
      ,COUNT(DISTINCT R.FDD_CODIGOEVENTO) AS CANTIDAD_EVENTOS
          FROM QA_TFDDREGISTRO R
      LEFT OUTER JOIN OMS.MANIOBRAS M ON M.CODE=R.FDD_CODIGOEVENTO
      LEFT OUTER JOIN OMS.CAUSAS C ON C.CODE=M.CAUSA
      WHERE R.FDD_TIPOCARGA='AJUSTE TC1' AND R.FDD_AJUSTADO='N'
      GROUP BY 'AJUSTE TC1 ADD',R.FDD_CAUSA_CREG,C.CAUSA015
UNION ALL
SELECT TO_CHAR('AJUSTE TC1 DEL') AS TABLA
      ,TO_NUMBER(R.FDD_CAUSA_CREG) AS CAUSA_QOS
      ,TO_NUMBER(C.CAUSA015) AS CAUSA_OMS
      ,COUNT(R.FDD_CODIGOEVENTO) AS CANTIDAD_REGISTROS
      ,COUNT(DISTINCT R.FDD_CODIGOEVENTO) AS CANTIDAD_EVENTOS
          FROM QA_TFDDREGISTRO R
      LEFT OUTER JOIN OMS.MANIOBRAS M ON M.CODE=R.FDD_CODIGOEVENTO
      LEFT OUTER JOIN OMS.CAUSAS C ON C.CODE=M.CAUSA
      WHERE R.FDD_TIPOAJUSTE=3 AND R.FDD_AJUSTADO='N'
      GROUP BY 'AJUSTE TC1 DEL',R.FDD_CAUSA_CREG,C.CAUSA015
;

--AJUSTES A BASE DE DATOS QOS PARA EL MES DE ABRIL 2020
-----------------------------------------------------------

---AJUSTES DE 22 REGISTROS NR
    UPDATE BRAE.QA_TFDDREGISTRO
    SET FDD_AJUSTADO='S',
        FDD_TIPOAJUSTE='2',
        FDD_RADICADO='2020042810395117',
        FDD_APROBADO='N'
    WHERE FDD_TIPOCARGA = 'NR' AND FDD_AJUSTADO = 'N';
--COMMIT;
SELECT * FROM QA_TFDDREGISTRO
WHERE FDD_TIPOCARGA = 'NR' AND FDD_AJUSTADO = 'S' AND FDD_RADICADO='2020042810395117';



-- AJUSTE DE 3524 REGISTROS MODIFICADOS
UPDATE QA_TFDDREGISTRO R
SET  --R.FDD_FINICIAL = (SELECT FDD_FINICIAL FROM QA_TFDDMODIFICADOS WHERE FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO=R.FDD_CODIGOEVENTO||R.FDD_CODIGOELEMENTO AND FDD_ORIGEN='OMS'),
     --R.FDD_FFINAL = (SELECT FDD_FFINAL FROM QA_TFDDMODIFICADOS WHERE FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO=R.FDD_CODIGOEVENTO||R.FDD_CODIGOELEMENTO AND FDD_ORIGEN='OMS'),
     R.FDD_CAUSA = (SELECT DISTINCT(M.CAUSA)
                    FROM OMS.INTERUPC I
                    LEFT OUTER JOIN OMS.MANIOBRAS M ON M.CODE=I.MINICIAL
                    WHERE I.MINICIAL=R.FDD_CODIGOEVENTO),
     R.FDD_AJUSTADO='S',
     R.FDD_TIPOAJUSTE=(CASE WHEN ((SELECT DISTINCT(TO_NUMBER(FDD_CAUSA_CREG))
                                   FROM QA_TFDDMODIFICADOS
                                   WHERE FDD_CODIGOEVENTO=R.FDD_CODIGOEVENTO
                                   AND FDD_ORIGEN='OMS')=0)
                            THEN 3
                            ELSE 2
                      END),
     R.FDD_RADICADO='2020042810395117',
     R.FDD_APROBADO='N',
     R.FDD_CAUSA_CREG=(SELECT  DISTINCT(FDD_CAUSA_CREG)
                       FROM QA_TFDDMODIFICADOS
                       WHERE FDD_CODIGOEVENTO=R.FDD_CODIGOEVENTO
                       AND FDD_ORIGEN='OMS'),
     R.FDD_EXCLUSION=(SELECT DISTINCT(C.FDC_EXCLUSION)
                     FROM OMS.INTERUPC I
                     LEFT OUTER JOIN OMS.MANIOBRAS M ON M.CODE=I.MINICIAL
                     LEFT OUTER JOIN QA_TFDDCAUSAS C ON C.FDC_CAUSA_OMS=M.CAUSA
                     WHERE I.MINICIAL=R.FDD_CODIGOEVENTO)
  WHERE R.FDD_CODIGOEVENTO||R.FDD_CODIGOELEMENTO IN (SELECT DISTINCT FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO FROM QA_TFDDMODIFICADOS);
;
--COMMIT;
SELECT * FROM QA_TFDDREGISTRO R
WHERE R.FDD_CODIGOEVENTO||R.FDD_CODIGOELEMENTO IN (SELECT DISTINCT FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO FROM QA_TFDDMODIFICADOS);




 --COMPLETAR EL CAMPO FDD_CAUSA_SSPD PARA TODOS LOS REGISTROS AFECTADOS SEGUN LA CONDICION WHERE

  UPDATE BRAE.QA_TFDDREGISTRO T
   SET T.FDD_CAUSA_SSPD =
          (CASE
              WHEN (  (  TO_DATE (
                            TO_CHAR (T.FDD_FFINAL, 'DD/MM/YYYY hh24:mi:ss'),
                            'DD/MM/YYYY hh24:mi:ss')
                       - TO_DATE (
                            TO_CHAR (T.FDD_FINICIAL, 'DD/MM/YYYY hh24:mi:ss'),
                            'DD/MM/YYYY hh24:mi:ss'))
                    * 24) <= 0.05
              THEN
                 1
              ELSE
                 NVL ((SELECT FDC_CAUSA_SSPD  FROM QA_TFDDCAUSAS WHERE FDC_CAUSA_OMS=T.FDD_CAUSA), 0)
           END)
  WHERE T.FDD_CODIGOEVENTO||T.FDD_CODIGOELEMENTO IN (SELECT DISTINCT FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO FROM QA_TFDDMODIFICADOS);

--COMMIT;

--COMPROBACION DE QUE NO EXISTEN EVENTOS MODIFICADOS ABIERTOS POR LO QUE NO SE HACE NECESARIO CORRER SCRIPT PARA
--JUSTIFICACION DE CAUAS_SSPD=1, Y PARA LOS NR'S NO SE EJECUTA POR LO QUE YA VIENEN CON ESA INSTANCIA DESDE SU CREACION

SELECT DISTINCT FDD_CODIGOEVENTO,
       TO_CHAR(FDD_FINICIAL,'DD/MM/YYYY HH24:MI:SS') AS FDD_FINICIAL,
       TO_CHAR(FDD_FFINAL,'DD/MM/YYYY HH24:MI:SS') AS FDD_FFINAL
FROM QA_TFDDREGISTRO
WHERE FDD_CODIGOEVENTO IN (SELECT DISTINCT FDD_CODIGOEVENTO FROM QA_TFDDMODIFICADOS)
AND FDD_CONTINUIDAD='S';


-- PASAR LOS ELIMINADOS A QA_TFDDELIMINADOS

INSERT INTO QA_TFDDELIMINADOS
SELECT * FROM QA_TFDDREGISTRO
WHERE FDD_CAUSA_CREG=0
AND FDD_RADICADO='2020042810395117';
--COMMIT;

--ELIMINACION DE LOS EVENTOS CON TIPO DE AJUSTE = 3 (MODIFICADOS POR AJUSTE 3-CAUSA 0)

DELETE FROM QA_TFDDREGISTRO
WHERE FDD_CAUSA_CREG=0
AND FDD_RADICADO='2020042810395117';
--COMMIT;

--AJUSTE PARA LOS ADD TC1
    UPDATE BRAE.QA_TFDDREGISTRO
    SET FDD_AJUSTADO='S',
        FDD_RADICADO='2020042810395117',
        FDD_APROBADO='N'
    WHERE FDD_TIPOCARGA = 'AJUSTE TC1' AND FDD_AJUSTADO = 'N';
--COMMIT;

--AJUSTE PARA LOS DEL TC1
    UPDATE BRAE.QA_TFDDREGISTRO
    SET FDD_AJUSTADO='S',
        FDD_RADICADO='2020042810395117',
        FDD_APROBADO='N'
    WHERE FDD_TIPOCARGA = 'CARGA DIARIA' AND FDD_AJUSTADO = 'N' AND FDD_TIPOAJUSTE=3;
--COMMIT;

SELECT * FROM QA_TFDDREGISTRO
WHERE FDD_TIPOCARGA = 'NR' AND FDD_AJUSTADO = 'S' AND FDD_RADICADO='2020042810395117';
--COMMIT;

SELECT * FROM QA_TFDDREGISTRO
WHERE FDD_TIPOCARGA='AJUSTE TC1'
AND FDD_AJUSTADO='S';


-- ELIMINACION DE LOS REGISTRO ACUTALIZADOS POR EL AJUSTE TC1

INSERT INTO QA_TFDDELIMINADOS
SELECT * FROM QA_TFDDREGISTRO
WHERE FDD_TIPOAJUSTE=3
AND FDD_TIPOCARGA='CARGA DIARIA'
AND FDD_RADICADO='2020042810395117';
--COMMIT;

--ELIMINACION DE LOS EVENTOS CON TIPO DE AJUSTE = 3 (MODIFICADOS POR AJUSTE 3-CAUSA 0)

DELETE FROM QA_TFDDREGISTRO
WHERE FDD_TIPOAJUSTE=3
AND FDD_TIPOCARGA='CARGA DIARIA'
AND FDD_RADICADO='2020042810395117';
--COMMIT;

SELECT * FROM QA_TFDDREGISTRO
 WHERE FDD_TIPOCARGA = 'CARGA DIARIA' AND FDD_AJUSTADO = 'S' AND FDD_TIPOAJUSTE=3;


---GENERAR TT9 Con el PL PRELIMINAR_NR version II
--MODIFICADOS
SELECT 161 AS COD_MERCADO
      ,TO_NUMBER(T1.FDD_CODIGOEVENTO) AS FDD_CODIGOEVENTO
      ,TO_CHAR(T2.FDD_FINICIAL,'DD-MM-YYYY HH24:MI:SS') AS FECHA_INICIAL_HORA
      ,T1.FDD_IUA AS CODIGO_ELEMENTO
      ,1 AS FDD_TIPOELEMENTO
      ,T1.FDD_TIPOAJUSTE
      ,(CASE WHEN(T1.FDD_TIPOCARGA='MR') THEN('MR') END) AS FUENTE_AJUSTE
FROM QA_TFDDPRELIMINAR_AJ T1
LEFT OUTER JOIN QA_TFDDREGISTRO T2 ON T2.FDD_CODIGOEVENTO||T2.FDD_CODIGOELEMENTO=T1.FDD_CODIGOEVENTO||T1.FDD_CODIGOELEMENTO
WHERE T1.FDD_TIPOCARGA='MR'
UNION ALL
--XR
SELECT 161 AS COD_MERCADO
      ,TO_NUMBER(T1.FDD_CODIGOEVENTO) AS FDD_CODIGOEVENTO
      ,TO_CHAR(T2.FDD_FINICIAL,'DD-MM-YYYY HH24:MI:SS') AS FECHA_INICIAL_HORA
      ,T1.FDD_IUA AS CODIGO_ELEMENTO---AQUI SE DEBE UTILIZAR LA INFORMACION DE LA TABLA T1 DESPUES DE ACTUALIZAR TC1
      ,1 AS FDD_TIPOELEMENTO
      ,T1.FDD_TIPOAJUSTE
      ,(CASE WHEN(T1.FDD_TIPOCARGA='XR') THEN('XR') END) AS FUENTE_AJUSTE
FROM QA_TFDDPRELIMINAR_AJ T1
LEFT OUTER JOIN QA_TFDDREGISTRO T2 ON T2.FDD_CODIGOEVENTO||T2.FDD_CODIGOELEMENTO=T1.FDD_CODIGOEVENTO||T1.FDD_CODIGOELEMENTO--PARA ESTA VEZ SOLAMENTE, ELIMINAR ESTA LINEA
WHERE T1.FDD_TIPOCARGA='XR'
UNION ALL
--AJUSTE TC1 ADD
 SELECT 161 AS COD_MERCADO
      ,TO_NUMBER(T1.FDD_CODIGOEVENTO) AS FDD_CODIGOEVENTO
      ,TO_CHAR(T1.FDD_FINICIAL,'DD-MM-YYYY HH24:MI:SS') AS FECHA_INICIAL_HORA
      ,T1.FDD_IUA AS CODIGO_ELEMENTO
      ,1 AS FDD_TIPOELEMENTO
      ,T1.FDD_TIPOAJUSTE
      ,(CASE WHEN(T1.FDD_TIPOCARGA='TR') THEN('TR') END) AS FUENTE_AJUSTE
FROM QA_TFDDPRELIMINAR_AJ T1
WHERE T1.FDD_TIPOCARGA='TR'
AND FDD_TIPOAJUSTE=1
UNION ALL
--AJUSTE TC1 DEL
SELECT 161 AS COD_MERCADO
      ,TO_NUMBER(T1.FDD_CODIGOEVENTO) AS FDD_CODIGOEVENTO
      ,TO_CHAR(T1.FDD_FINICIAL,'DD-MM-YYYY HH24:MI:SS') AS FECHA_INICIAL_HORA
      ,T1.FDD_IUA AS CODIGO_ELEMENTO
      ,1 AS FDD_TIPOELEMENTO
      ,T1.FDD_TIPOAJUSTE
      ,(CASE WHEN(T1.FDD_TIPOCARGA='TR') THEN('TR') END) AS FUENTE_AJUSTE
FROM QA_TFDDPRELIMINAR_AJ T1
WHERE T1.FDD_TIPOCARGA='TR'
AND FDD_TIPOAJUSTE=3;

--TABLA DINAMICA VERSION QA_TFDDPRELIMINAR_AJ
SELECT (CASE WHEN(P.FDD_TIPOCARGA='XR') THEN('XR')
             WHEN(P.FDD_TIPOCARGA='MR') THEN('MR')
             WHEN(P.FDD_TIPOCARGA='TR' AND P.FDD_TIPOAJUSTE=1) THEN('AJUSTE TC1 ADD')
             WHEN(P.FDD_TIPOCARGA='TR' AND P.FDD_TIPOAJUSTE=3) THEN('AJUSTE TC1 DEL')
        END) AS TABLA
       ,P.FDD_TIPOAJUSTE
       ,R.FDD_CAUSA_CREG AS CAUSA_QOS
       ,C2.FDC_DESCRIPCION AS FDC_DESCRIPCION_QOS
       ,C2.FDC_EXCLUSION AS FDC_EXCLUSION_QOS
       ,P.FDD_CAUSA_CREG AS CAUSA_OMS
       ,C1.FDC_DESCRIPCION AS FDC_DESCRIPCION_OMS
       ,C1.FDC_EXCLUSION AS FDC_EXCLUSION_OMS
       ,COUNT(P.FDD_CODIGOELEMENTO) AS CANTIDAD_REGISTROS
       ,COUNT(DISTINCT P.FDD_CODIGOEVENTO) AS CANTIDAD_EVENTOS
FROM QA_TFDDPRELIMINAR_AJ P
LEFT OUTER JOIN QA_TFDDREGISTRO R ON R.FDD_CODIGOEVENTO||R.FDD_CODIGOELEMENTO=P.FDD_CODIGOEVENTO||P.FDD_CODIGOELEMENTO
LEFT OUTER JOIN (SELECT DISTINCT FDC_CAUSA_015, FDC_DESCRIPCION,FDC_EXCLUSION FROM  QA_TFDDCAUSAS) C1 ON C1.FDC_CAUSA_015=P.FDD_CAUSA_CREG
LEFT OUTER JOIN (SELECT DISTINCT FDC_CAUSA_015, FDC_DESCRIPCION,FDC_EXCLUSION FROM  QA_TFDDCAUSAS) C2 ON C2.FDC_CAUSA_015=R.FDD_CAUSA_CREG
GROUP BY (CASE WHEN(P.FDD_TIPOCARGA='XR') THEN('XR')
             WHEN(P.FDD_TIPOCARGA='MR') THEN('MR')
             WHEN(P.FDD_TIPOCARGA='TR' AND P.FDD_TIPOAJUSTE=1) THEN('AJUSTE TC1 ADD')
             WHEN(P.FDD_TIPOCARGA='TR' AND P.FDD_TIPOAJUSTE=3) THEN('AJUSTE TC1 DEL')
        END),R.FDD_CAUSA_CREG,P.FDD_CAUSA_CREG,C2.FDC_DESCRIPCION,C2.FDC_EXCLUSION,C1.FDC_DESCRIPCION,C1.FDC_EXCLUSION,P.FDD_TIPOAJUSTE
ORDER BY 1;

---GENERAR FORMATO MENSUAL DE AJUSTES LAC VERSION II
SELECT TO_NUMBER(FDD_CODIGOEVENTO) AS FDD_CODIGOEVENTO
      ,TO_CHAR(FDD_FINICIAL,'DD/MM/YYYY HH24:MI:SS') AS FDD_FINICIAL
      ,TO_CHAR(FDD_FFINAL,'DD/MM/YYYY HH24:MI:SS') AS FDD_FFINAL
      ,FDD_IUA
      ,(CASE WHEN(FDD_TIPOELEMENTO='Transformer') THEN(1) ELSE (2) END ) AS FDD_TIPOELEMENTO
      ,TO_NUMBER(FDD_CAUSA_CREG) AS FDD_CAUSA
      ,FDD_CONTINUIDAD
      ,0 AS FDD_EXCLUIDOZNI
      ,(CASE WHEN FDD_CODIGOGENERADOR IS NULL THEN 0 ELSE 1 END) AS FDD_AFECTACONGEN
      ,(CASE WHEN FDD_USUARIOAP='S' THEN 1 ELSE 0 END) AS FDD_USUARIOAP
      ,FDD_TIPOAJUSTE
      ,TO_CHAR(:RADICADO_SSPD)
FROM QA_TFDDPRELIMINAR_NR;


--GENERAR TT9 VERSION III

---GENERAR TT9 Con el PL PRELIMINAR_NR version II
--MODIFIDIED AND XR
SELECT 161 AS COD_MERCADO
      ,TO_NUMBER(T1.FDD_CODIGOEVENTO) AS FDD_CODIGOEVENTO
      ,TO_CHAR(T2.FDD_FINICIAL,'DD-MM-YYYY HH24:MI:SS') AS FECHA_INICIAL_HORA
      ,T1.FDD_IUA AS CODIGO_ELEMENTO
      ,1 AS FDD_TIPOELEMENTO
      ,T1.FDD_TIPOAJUSTE
FROM QA_TFDDPRELIMINAR_AJ T1
LEFT OUTER JOIN QA_TFDDREGISTRO T2 ON T2.FDD_CODIGOEVENTO||T2.FDD_CODIGOELEMENTO=T1.FDD_CODIGOEVENTO||T1.FDD_CODIGOELEMENTO
WHERE (T1.FDD_TIPOCARGA='MR' OR T1.FDD_TIPOCARGA='XR')
UNION ALL
--AJUSTE TC1 ADD Y DEL
 SELECT 161 AS COD_MERCADO
      ,TO_NUMBER(T1.FDD_CODIGOEVENTO) AS FDD_CODIGOEVENTO
      ,TO_CHAR(T1.FDD_FINICIAL,'DD-MM-YYYY HH24:MI:SS') AS FECHA_INICIAL_HORA
      ,T1.FDD_IUA AS CODIGO_ELEMENTO
      ,1 AS FDD_TIPOELEMENTO
      ,T1.FDD_TIPOAJUSTE
FROM QA_TFDDPRELIMINAR_AJ T1
WHERE T1.FDD_TIPOCARGA='TR'
AND (FDD_TIPOAJUSTE = 1 OR FDD_TIPOAJUSTE = 3)
;

--TT9 VERSION IV
--CREATE VIEW QA_VTT9 AS
SELECT 161 AS COD_MERCADO
      ,TO_NUMBER(AJS.FDD_CODIGOEVENTO) AS FDD_CODIGOEVENTO
      ,(
       CASE WHEN(   AJS.FDD_TIPOCARGA='MR'
                 OR AJS.FDD_TIPOCARGA='XR') THEN(TO_CHAR(REG.FDD_FINICIAL,'DD-MM-YYYY HH24:MI:SS'))
             WHEN(  AJS.FDD_TIPOCARGA='TR') THEN(TO_CHAR(AJS.FDD_FINICIAL,'DD-MM-YYYY HH24:MI:SS'))
       END
       ) AS FECHA_INICIAL_HORA
      ,AJS.FDD_IUA AS CODIGO_ELEMENTO
      ,1 AS FDD_TIPOELEMENTO
      ,AJS.FDD_TIPOAJUSTE
      ,(
       161||','||
       TO_NUMBER(AJS.FDD_CODIGOEVENTO)||','||
       (
        CASE WHEN(   AJS.FDD_TIPOCARGA='MR'
                  OR AJS.FDD_TIPOCARGA='XR') THEN(TO_CHAR(REG.FDD_FINICIAL,'DD-MM-YYYY HH24:MI:SS'))
              WHEN(  AJS.FDD_TIPOCARGA='TR') THEN(TO_CHAR(AJS.FDD_FINICIAL,'DD-MM-YYYY HH24:MI:SS'))
        END
        )||','||
       AJS.FDD_IUA||','||
       1||','||
       AJS.FDD_TIPOAJUSTE
       ) AS CONCAT
FROM QA_TFDDPRELIMINAR_AJ AJS
LEFT OUTER JOIN QA_TFDDREGISTRO REG ON (REG.FDD_CODIGOEVENTO||REG.FDD_CODIGOELEMENTO
                                      = AJS.FDD_CODIGOEVENTO||AJS.FDD_CODIGOELEMENTO);
DESC QA_TCS1;



select DISTINCT R.FDD_CODIGOEVENTO
              , R.FDD_FINICIAL
              , R.FDD_FFINAL
              , R. FDD_CAUSA_CREG
              , R.FDD_CODIGOELEMENTO
              ,TO_CHAR (T.TC1_PERIODO)
              ,TO_CHAR(R.FDD_PERIODO_OP,'YYYYMM')
from BRAE.QA_TFDDREGISTRO R
LEFT JOIN (BRAE.QA_TTC1) T ON T.TC1_CODCONEX = R.FDD_CODIGOELEMENTO AND TO_CHAR (T.TC1_PERIODO)= TO_CHAR(R.FDD_PERIODO_OP,'YYYYMM')
WHERE FDD_CAUSA_CREG ='14';

SELECT COUNT(DISTINCT R.FDD_CODIGOEVENTO) AS CANTIDAD_EVEN
      ,COUNT(R.FDD_CODIGOELEMENTO) AS CANT_ELEMEN
      ,ROUND(SUM(T.CANT_USRS*(TO_DATE(TO_CHAR(R.FDD_FFINAL  ,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')-
                        TO_DATE(TO_CHAR(R.FDD_FINICIAL,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'))*24),3) AS UIxTI
FROM BRAE.QA_TFDDREGISTRO R
LEFT JOIN (SELECT TC1_CODCONEX, COUNT(TC1_TC1) AS CANT_USRS
           FROM BRAE.QA_TTC1
           WHERE TC1_PERIODO = TO_CHAR(TO_DATE(:PERIODO,'DD/MM/YYYY'),'YYYY')||'12'
           GROUP BY TC1_CODCONEX) T
           ON T.TC1_CODCONEX = R.FDD_CODIGOELEMENTO  
WHERE TO_CHAR(R.FDD_FINICIAL,'YYYY') = TO_CHAR(TO_DATE(:PERIODO,'DD/MM/YYYY'),'YYYY')
AND R.FDD_CAUSA_CREG = '14';

SELECT ESTADO,COUNT(ESTADO) 
FROM SPARD.TRANSFOR
GROUP BY ESTADO ;
--WHERE CODE IN ('6T00002');

SELECT * FROM SPARD.TRANSFOR 
WHERE CODE IN ('6T00002');

SELECT * FROM QA_TTC1 WHERE TC1_CODFRONCOM IN ('Frt35204');

SELECT TC1_TC1, TC1_CODFRONCOM,TC1_PERIODO FROM QA_TTC1
WHERE TC1_CODFRONCOM IN ('Frt20707',
'Frt31058',
'Frt38164',
'Frt35204')
ORDER BY 2,3;


DESC QA_TTC1;



SELECT * FROM QA_TCSU WHERE CSU_PERIODO_OP='01/09/2021';

SELECT CODE, MUNICIPIO FROM SPARD.TRANSFOR;

SELECT * FROM QA_TTC1 WHERE TC1_CODCONEX='4T00741'
AND TC1_PERIODO=202109;





SELECT T1.CSU_PERIODO_OP AS PERIODO
      ,T1.CSU_NIU AS CODIGO_UNICO_USUARIO
      ,T2.TC1_NT AS NIVEL_TENSION
      ,T2.TC1_GC AS GRUPO_CALIDAD
      ,ROUND(T1.CSU_DIU,2) AS DIU_HRS
      ,ROUND(T1.CSU_DIUM,2) AS DIUM_HRS
      ,T1.CSU_FIU AS FIU
      ,T1.CSU_FIUM AS FIUM
      ,ROUND(T3.DIUGJ,2) AS META_POR_DURACION_HRS
      ,T3.FIUGJ AS META_POR_FRECUENCIA
FROM QA_TCSU T1
LEFT OUTER JOIN (SELECT DISTINCT TC1_TC1, TC1_GC, TC1_NT FROM QA_TTC1 WHERE TC1_PERIODO='202012')  T2 ON T2.TC1_TC1 = T1.CSU_NIU
LEFT OUTER JOIN (SELECT NT,GRUPO015,DIUGJ,FIUGJ FROM QA_TMETAS_CALINDIVIDUAL WHERE PERIODO='2020') T3 ON (T3.NT=T2.TC1_NT AND T3.GRUPO015=T2.TC1_GC)
WHERE T1.CSU_NIU IN ('606661')
AND TO_CHAR(T1.CSU_PERIODO_OP,'yyyy')='2021'
ORDER BY T1.CSU_PERIODO_OP,T1.CSU_NIU
;

SELECT * FROM QA_TTC1 
WHERE TC1_TC1 = '606661' 
AND SUBSTR(TC1_PERIODO,1,4)='2021';

SELECT '606661' AS COD_USUARIO
      ,FDD_CODIGOEVENTO AS COD_EVENTO
      ,FDD_FINICIAL AS FECHA_INICIAL
      ,FDD_FFINAL AS FECHA_FINAL
      ,ROUND((TO_DATE(TO_CHAR(FDD_FFINAL  ,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')-
       TO_DATE(TO_CHAR(FDD_FINICIAL,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'))*24,3) AS DURACIÓN_HRS
      ,FDD_CODIGOELEMENTO AS TRANSFORMADOR
      ,FDD_CAUSA_CREG AS CAUSA_CREG
      ,FDD_CAUSA_SSPD AS CAUSA_SSPD
      ,FDD_EXCLUSION AS EXCLUSION
      ,FDC_DESCRIPCION AS DESCRIPCION
      ,FDC_DETALLE AS DETALLE
FROM QA_TFDDREGISTRO
LEFT OUTER JOIN QA_TFDDCAUSAS ON FDC_CAUSA_OMS=FDD_CAUSA
WHERE FDD_CODIGOELEMENTO='1T11333'
AND TO_CHAR(FDD_FINICIAL,'YYYY')='2021'
--AND FDD_CAUSA_SSPD <> '1'
ORDER BY FDD_FINICIAL;


SELECT * FROM QA_TFDDCAUSAS;





SELECT * FROM ALL_TABLES
WHERE OWNER  = 'OMS'
AND TABLE_NAME LIKE '%CUAD%';

SELECT * FROM OMS.LOGMAN
--WHERE TO_CHAR(FECHA,'MMYYYY')='122020'
WHERE CODE = '924498';

SELECT * FROM OMS.INTERUPC
WHERE MINICIAL = '780670';

SELECT * FROM OMS.MANIOBRAS
WHERE CODE  = '780670';


SELECT * FROM QA_TFDDREPORTE_AJ
WHERE FDR_PERIODO_OP=DATE'2020-12-01';


SELECT * FROM QA_TFDDREGISTRO
WHERE FDD_PERIODO_OP=DATE'2020-12-01'
AND FDD_AJUSTADO='S';

SELECT * FROM QA_TTT9
WHERE TT9_PERIODO_OP=DATE'2020-12-01';






SELECT * FROM QA_TFDDREGISTRO
WHERE T;

SELECT * FROM OMS.MANIOBRAS
WHERE EVENTO='1630358';

SELECT * FROM OMS.GEV_CUA_CUADRILLA;

SELECT * FROM OMS.INTERUPC
WHERE MINICIAL='438404';


SELECT * FROM QA_TFDDREGISTRO
WHERE FDD_CODIGOEVENTO='438404';







