SELECT * 
FROM QA_TFDDREGISTRO
WHERE FDD_TIPOCARGA='NR';

SELECT DISTINCT FDD_CODIGOEVENTO,FDD_TIPOCARGA, FDD_FINICIAL, FDD_FFINAL 
FROM QA_TFDDREGISTRO
WHERE FDD_TIPOCARGA IN ('DR','XR')
AND FDD_PERIODO_OP= TO_DATE('29/07/2021','DD/MM/YYYY')
AND FDD_CODIGOELEMENTO IN (
                           SELECT FDD_CODIGOELEMENTO
                           FROM QA_TFDDREGISTRO
                           WHERE FDD_CODIGOEVENTO='838122'
                           )
UNION ALL                        
SELECT DISTINCT FDD_CODIGOEVENTO,FDD_TIPOCARGA, FDD_FINICIAL, FDD_FFINAL 
FROM QA_TFDDREGISTRO
WHERE FDD_CODIGOEVENTO='838122';


SELECT FDD_CODIGOEVENTO,FDD_TIPOCARGA,FDD_CODIGOELEMENTO 
FROM QA_TFDDREGISTRO
WHERE FDD_TIPOCARGA IN ('DR','XR')
AND FDD_PERIODO_OP= TO_DATE('29/07/2021','DD/MM/YYYY')
AND FDD_CODIGOELEMENTO IN (
                           SELECT FDD_CODIGOELEMENTO
                           FROM QA_TFDDREGISTRO
                           WHERE FDD_CODIGOEVENTO='837869'
                           );
                           
                           
  ------------------------------------------------------                         
                           
				SELECT FDD_CODIGOEVENTO
				     , MIN_IZQ - ROWNUM/86400
				     , MAX_DER + ROWNUM/86400
				      ,(
				        CASE WHEN((MIN_IZQ - ROWNUM/86400) >= TRUNC(TO_DATE('29/07/2021','DD/MM/YYYY'))+(2/86400))
				             THEN(1)
				             ELSE(0)
				        END
				        ) AS VAL_IZQ
				      ,(
				        CASE WHEN((MAX_DER + ROWNUM/86400) <= TRUNC(TO_DATE('29/07/2021','DD/MM/YYYY'))+1-(2/86400))
				             THEN(1)
				             ELSE(0)
				        END
				        ) AS VAL_DER
				--BULK COLLECT INTO VAR_L
				FROM(
				SELECT T1.FDD_CODIGOEVENTO
				      ,(
				        CASE WHEN(TO_DATE(TO_CHAR(MIN(T2.FDD_FINICIAL),'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')>=TRUNC(TO_DATE('29/07/2021','DD/MM/YYYY'))+(2/86400))
				             THEN(TO_DATE(TO_CHAR(MIN(T2.FDD_FINICIAL),'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'))
				             ELSE(NULL)
				        END
				        ) AS MIN_IZQ
				      ,(
				        CASE WHEN(TO_DATE(TO_CHAR(MAX(T2.FDD_FFINAL)  ,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS')<=TRUNC(TO_DATE('29/07/2021','DD/MM/YYYY'))+1-(2/86400))
				             THEN(TO_DATE(TO_CHAR(MAX(T2.FDD_FFINAL)  ,'DD/MM/YYYY HH24:MI:SS'),'DD/MM/YYYY HH24:MI:SS'))
				             ELSE(NULL)
				        END
				        ) AS MAX_DER
				FROM QA_TFDDREGISTRO T1
				LEFT OUTER JOIN ( SELECT FDD_CODIGOEVENTO,FDD_CODIGOELEMENTO
				                        ,FDD_FINICIAL    ,(CASE WHEN(FDD_FFINAL IS NULL) THEN(TO_DATE('29/07/2021','DD/MM/YYYY') + 1-(1/86400)) ELSE(FDD_FFINAL) END)AS FDD_FFINAL
													FROM QA_TFDDREGISTRO
													WHERE FDD_PERIODO_OP = TO_DATE('29/07/2021','DD/MM/YYYY')
													AND   FDD_TIPOCARGA <> 'NR'
				                ) T2 ON T2.FDD_CODIGOELEMENTO = T1.FDD_CODIGOELEMENTO
				WHERE T1.FDD_PERIODO_OP = TO_DATE('29/07/2021','DD/MM/YYYY')
				AND   T1.FDD_TIPOCARGA = 'NR'
				AND   T2.FDD_CODIGOELEMENTO IS NOT NULL-- PARA NO TRAER LOS ELEMENTOS QUE NO TRASLAPARON PERO SI DEL EVENTO TRASLAPADO
				GROUP BY T1.FDD_CODIGOEVENTO
				ORDER BY MAX_DER ASC);                           

--DELETE FROM QA_TFDDREGISTRO WHERE FDD_CODIGOEVENTO ='838742';
--COMMIT;
UPDATE QA_TFDDREGISTRO
SET FDD_TIPOCARGA='XR',
    FDD_FINICIAL = TO_TIMESTAMP('29/07/2021 23:59:57.000','DD/MM/YYYY hh24:mi:ss.FF3'),
    FDD_FFINAL   = TO_TIMESTAMP('29/07/2021 23:59:58.000','DD/MM/YYYY hh24:mi:ss.FF3')
WHERE FDD_CODIGOEVENTO ='838122';

UPDATE QA_TFDDREGISTRO
SET FDD_TIPOCARGA='XR',
    FDD_FINICIAL = TO_TIMESTAMP('29/07/2021 23:59:57.000','DD/MM/YYYY hh24:mi:ss.FF3'),
    FDD_FFINAL   = TO_TIMESTAMP('29/07/2021 23:59:58.000','DD/MM/YYYY hh24:mi:ss.FF3')
WHERE FDD_CODIGOEVENTO ='837869';
--------------------------------
UPDATE QA_TFDDREGISTRO
SET FDD_TIPOCARGA='NR',
    FDD_FINICIAL = NULL,
    FDD_FFINAL   = NULL
WHERE FDD_CODIGOEVENTO ='838122';

UPDATE QA_TFDDREGISTRO
SET FDD_TIPOCARGA='NR',
    FDD_FINICIAL = NULL,
    FDD_FFINAL   = NULL
WHERE FDD_CODIGOEVENTO ='837869';

