--- TABLA COMPUESTA QA_TFDDREGISTRO Y QA_TFDDPRELIMINAR_NR PARA CALCULAR INDICADOR SAIDI & SAIFI (SQL CON CURSOR)

----- QA_TFDDREGISTRO EVENTOS DEL MES
        SELECT TO_NUMBER(FDD_CODIGOEVENTO) AS FDD_CODIGOEVENTO, 
               TO_CHAR(FDD_FINICIAL,'DD/MM/YYYY HH24:MI:SS')AS FDD_FINICIAL,
               TO_CHAR(FDD_FFINAL,'DD/MM/YYYY HH24:MI:SS')AS FDD_FFINAL,
               ( CASE WHEN (TO_DATE(TO_CHAR(FDD_FFINAL,'DD/MM/YYYY hh24:mi:ss'),'DD/MM/YYYY hh24:mi:ss') >= TO_DATE(:FECHA_FIN_DD_MM_YYYY,'DD/MM/YYYY hh24:mi:ss') OR FDD_FFINAL IS NULL )
                     THEN
                      (TO_DATE(:FECHA_FIN_DD_MM_YYYY,'DD/MM/YYYY hh24:mi:ss') -TO_DATE(TO_CHAR(FDD_FINICIAL,'DD/MM/YYYY hh24:mi:ss'),'DD/MM/YYYY hh24:mi:ss'))*24
                     ELSE
                        CASE WHEN (TO_DATE(TO_CHAR(FDD_FINICIAL,'DD/MM/YYYY hh24:mi:ss'),'DD/MM/YYYY hh24:mi:ss') < TO_DATE(:FECHA_INICIO_DD_MM_YYYY,'DD/MM/YYYY hh24:mi:ss'))
                        THEN
                           (TO_DATE(TO_CHAR(FDD_FFINAL,'DD/MM/YYYY hh24:mi:ss'),'DD/MM/YYYY hh24:mi:ss')-TO_DATE(:FECHA_INICIO_DD_MM_YYYY,'DD/MM/YYYY hh24:mi:ss'))*24
                        ELSE
                         (TO_DATE(TO_CHAR(FDD_FFINAL,'DD/MM/YYYY hh24:mi:ss'),'DD/MM/YYYY hh24:mi:ss')-TO_DATE(TO_CHAR(FDD_FINICIAL,'DD/MM/YYYY hh24:mi:ss'),'DD/MM/YYYY hh24:mi:ss'))*24
                         END
                END) AS FDD_DURACION,
               FDD_CODIGOELEMENTO,
               T.LONGITUD,
              T.LATITUD,
               M.BREAKER,
               NVL(TC1.USUARIOS,0) AS USUARIOS_UI,
               NVL((( CASE WHEN (TO_DATE(TO_CHAR(FDD_FFINAL,'DD/MM/YYYY hh24:mi:ss'),'DD/MM/YYYY hh24:mi:ss') >= TO_DATE(:FECHA_FIN_DD_MM_YYYY,'DD/MM/YYYY hh24:mi:ss') OR FDD_FFINAL IS NULL )
                     THEN
                      (TO_DATE(:FECHA_FIN_DD_MM_YYYY,'DD/MM/YYYY hh24:mi:ss') -TO_DATE(TO_CHAR(FDD_FINICIAL,'DD/MM/YYYY hh24:mi:ss'),'DD/MM/YYYY hh24:mi:ss'))*24
                     ELSE
                        CASE WHEN (TO_DATE(TO_CHAR(FDD_FINICIAL,'DD/MM/YYYY hh24:mi:ss'),'DD/MM/YYYY hh24:mi:ss') < TO_DATE(:FECHA_INICIO_DD_MM_YYYY,'DD/MM/YYYY hh24:mi:ss'))
                        THEN
                           (TO_DATE(TO_CHAR(FDD_FFINAL,'DD/MM/YYYY hh24:mi:ss'),'DD/MM/YYYY hh24:mi:ss')-TO_DATE(:FECHA_INICIO_DD_MM_YYYY,'DD/MM/YYYY hh24:mi:ss'))*24
                        ELSE
                         (TO_DATE(TO_CHAR(FDD_FFINAL,'DD/MM/YYYY hh24:mi:ss'),'DD/MM/YYYY hh24:mi:ss')-TO_DATE(TO_CHAR(FDD_FINICIAL,'DD/MM/YYYY hh24:mi:ss'),'DD/MM/YYYY hh24:mi:ss'))*24
                         END
                END)*TC1.USUARIOS),0) AS FDD_UIXTI,
               T.FPARENT,
               MUN.MUND_DESCRIPCION,
               MUN.MUND_REGIONAL,
               FDD_CAUSA,
               SUBSTR (C.FDC_DETALLE,8) AS DETALLE_CAUSA,
               TO_NUMBER(FDD_CAUSA_CREG) AS FDD_CAUSA_CREG,
               FDD_CAUSA_SSPD,
               FDD_EXCLUSION,
               FDD_TIPOCARGA,
               FDD_CONTINUIDAD, 
               FDD_USUARIOAP, 
               FDD_AJUSTADO, 
               FDD_TIPOAJUSTE,
               FDD_RADICADO, 
               FDD_APROBADO,
               --C.FDC_EXCLUSION AS EXCLUSION_CORREGIDA, --ESTE CAMPO ES PARA CORREGIR EL UPDATE DEL CAMPO DESDE LA TABLA QA_TFDDCAUSAS
               M.OBJETIVO AS OBJETIVO_INI
         FROM QA_TFDDREGISTRO
         LEFT OUTER JOIN (SELECT TC1_CODCONEX, COUNT(TC1_TC1) AS USUARIOS FROM QA_TTC1 WHERE TC1_PERIODO=:PERIODO_TC1_YYYYMM GROUP BY TC1_CODCONEX) TC1 ON TC1.TC1_CODCONEX=FDD_CODIGOELEMENTO --'201905'
         LEFT OUTER JOIN OMS.TRANSFOR@OMSPROD T ON T.CODE=FDD_CODIGOELEMENTO
         LEFT OUTER JOIN OMS.MANIOBRAS@OMSPROD M ON M.CODE=FDD_CODIGOEVENTO
         LEFT OUTER JOIN GE_TMUNDANE MUN ON MUN.MUND_MUNDANE = (T.DEP_ID*1000+T.MUNICIPIO)
         LEFT OUTER JOIN QA_TFDDCAUSAS C ON C.FDC_CAUSA_OMS=FDD_CAUSA
                     
         WHERE (TO_CHAR(FDD_FINICIAL, 'MM/YYYY')  = SUBSTR(:FECHA_INICIO_DD_MM_YYYY,4)--'07/2019' 
                OR TO_CHAR(FDD_FFINAL, 'MM/YYYY') = SUBSTR(:FECHA_INICIO_DD_MM_YYYY,4))--'07/2019')
                
UNION ALL
----- QA_TFDDREGISTRO EVENTOS QUE VIENEN ABIERTOS DE ANTES Y PASAN DERECHO
        SELECT TO_NUMBER(FDD_CODIGOEVENTO) AS FDD_CODIGOEVENTO, 
               TO_CHAR(FDD_FINICIAL,'DD/MM/YYYY HH24:MI:SS')AS FDD_FINICIAL,
               TO_CHAR(FDD_FFINAL,'DD/MM/YYYY HH24:MI:SS')AS FDD_FFINAL,
               --(TO_DATE(:FECHA_FIN_DD_MM_YYYY,'DD/MM/YYYY hh24:mi:ss')-TO_DATE(:FECHA_INICIO_DD_MM_YYYY,'DD/MM/YYYY hh24:mi:ss'))*24 AS FDD_DURACION,
               672 AS DURACION,
               FDD_CODIGOELEMENTO,
               T.LONGITUD,
               T.LATITUD,
               M.BREAKER,
               NVL(TC1.USUARIOS,0) AS USUARIOS_UI,
               --NVL(((TO_DATE(:FECHA_FIN_DD_MM_YYYY,'DD/MM/YYYY hh24:mi:ss')-TO_DATE(:FECHA_INICIO_DD_MM_YYYY,'DD/MM/YYYY hh24:mi:ss'))*24*TC1.USUARIOS),0) AS FDD_UIXTI,
               NVL(672*TC1.USUARIOS,0) AS FDD_UIXTI,
                T.FPARENT,
                MUN.MUND_DESCRIPCION,
                MUN.MUND_REGIONAL,
               FDD_CAUSA,
               SUBSTR (C.FDC_DETALLE,8) AS DETALLE_CAUSA,
               TO_NUMBER(FDD_CAUSA_CREG) AS FDD_CAUSA_CREG,
               FDD_CAUSA_SSPD,
               FDD_EXCLUSION,
               FDD_TIPOCARGA,
               FDD_CONTINUIDAD, 
               FDD_USUARIOAP, 
               FDD_AJUSTADO, 
               FDD_TIPOAJUSTE,
               FDD_RADICADO, 
               FDD_APROBADO,
               --C.FDC_EXCLUSION AS EXCLUSION_CORREGIDA, --ESTE CAMPO ES PARA CORREGIR EL UPDATE DEL CAMPO DESDE LA TABLA QA_TFDDCAUSAS
               M.OBJETIVO AS OBJETIVO_INI
         FROM QA_TFDDREGISTRO
         LEFT OUTER JOIN (SELECT TC1_CODCONEX, COUNT(TC1_TC1) AS USUARIOS FROM QA_TTC1 WHERE TC1_PERIODO=:PERIODO_TC1_YYYYMM GROUP BY TC1_CODCONEX) TC1 ON TC1.TC1_CODCONEX=FDD_CODIGOELEMENTO --201905
         LEFT OUTER JOIN OMS.TRANSFOR@OMSPROD T ON T.CODE=FDD_CODIGOELEMENTO
        LEFT OUTER JOIN OMS.MANIOBRAS@OMSPROD M ON M.CODE=FDD_CODIGOEVENTO
         LEFT OUTER JOIN GE_TMUNDANE MUN ON MUN.MUND_MUNDANE = (T.DEP_ID*1000+T.MUNICIPIO)
         LEFT OUTER JOIN QA_TFDDCAUSAS C ON C.FDC_CAUSA_OMS=FDD_CAUSA
         
         WHERE TO_CHAR(FDD_FINICIAL, 'MM/YYYY') < SUBSTR(:FECHA_INICIO_DD_MM_YYYY,4)--'07/2019'
         AND (TO_CHAR(FDD_FFINAL, 'MM/YYYY') >= SUBSTR(:FECHA_FIN_DD_MM_YYYY,4) OR FDD_FFINAL IS NULL) --'08/2019'
   
UNION ALL       
----- QA_TFDDPRELIMINAR_NR EVENTOS DEL MES
         SELECT TO_NUMBER(FDD_CODIGOEVENTO) AS FDD_CODIGOEVENTO, 
               TO_CHAR(FDD_FINICIAL,'DD/MM/YYYY HH24:MI:SS')AS FDD_FINICIAL,
               TO_CHAR(FDD_FFINAL,'DD/MM/YYYY HH24:MI:SS')AS FDD_FFINAL,
               ( CASE WHEN (TO_DATE(TO_CHAR(FDD_FFINAL,'DD/MM/YYYY hh24:mi:ss'),'DD/MM/YYYY hh24:mi:ss') >= TO_DATE(:FECHA_FIN_DD_MM_YYYY,'DD/MM/YYYY hh24:mi:ss') OR FDD_FFINAL IS NULL )
                     THEN
                      (TO_DATE(:FECHA_FIN_DD_MM_YYYY,'DD/MM/YYYY hh24:mi:ss') -TO_DATE(TO_CHAR(FDD_FINICIAL,'DD/MM/YYYY hh24:mi:ss'),'DD/MM/YYYY hh24:mi:ss'))*24
                     ELSE
                        CASE WHEN (TO_DATE(TO_CHAR(FDD_FINICIAL,'DD/MM/YYYY hh24:mi:ss'),'DD/MM/YYYY hh24:mi:ss') < TO_DATE(:FECHA_INICIO_DD_MM_YYYY,'DD/MM/YYYY hh24:mi:ss'))
                        THEN
                           (TO_DATE(TO_CHAR(FDD_FFINAL,'DD/MM/YYYY hh24:mi:ss'),'DD/MM/YYYY hh24:mi:ss')-TO_DATE(:FECHA_INICIO_DD_MM_YYYY,'DD/MM/YYYY hh24:mi:ss'))*24
                        ELSE
                         (TO_DATE(TO_CHAR(FDD_FFINAL,'DD/MM/YYYY hh24:mi:ss'),'DD/MM/YYYY hh24:mi:ss')-TO_DATE(TO_CHAR(FDD_FINICIAL,'DD/MM/YYYY hh24:mi:ss'),'DD/MM/YYYY hh24:mi:ss'))*24
                         END
                END) AS FDD_DURACION,
               FDD_CODIGOELEMENTO,
               T.LONGITUD,
               T.LATITUD,
               M.BREAKER,
               NVL(TC1.USUARIOS,0) AS USUARIOS_UI,
               NVL((( CASE WHEN (TO_DATE(TO_CHAR(FDD_FFINAL,'DD/MM/YYYY hh24:mi:ss'),'DD/MM/YYYY hh24:mi:ss') >= TO_DATE(:FECHA_FIN_DD_MM_YYYY,'DD/MM/YYYY hh24:mi:ss') OR FDD_FFINAL IS NULL )
                     THEN
                      (TO_DATE(:FECHA_FIN_DD_MM_YYYY,'DD/MM/YYYY hh24:mi:ss') -TO_DATE(TO_CHAR(FDD_FINICIAL,'DD/MM/YYYY hh24:mi:ss'),'DD/MM/YYYY hh24:mi:ss'))*24
                     ELSE
                        CASE WHEN (TO_DATE(TO_CHAR(FDD_FINICIAL,'DD/MM/YYYY hh24:mi:ss'),'DD/MM/YYYY hh24:mi:ss') < TO_DATE(:FECHA_INICIO_DD_MM_YYYY,'DD/MM/YYYY hh24:mi:ss'))
                        THEN
                           (TO_DATE(TO_CHAR(FDD_FFINAL,'DD/MM/YYYY hh24:mi:ss'),'DD/MM/YYYY hh24:mi:ss')-TO_DATE(:FECHA_INICIO_DD_MM_YYYY,'DD/MM/YYYY hh24:mi:ss'))*24
                        ELSE
                         (TO_DATE(TO_CHAR(FDD_FFINAL,'DD/MM/YYYY hh24:mi:ss'),'DD/MM/YYYY hh24:mi:ss')-TO_DATE(TO_CHAR(FDD_FINICIAL,'DD/MM/YYYY hh24:mi:ss'),'DD/MM/YYYY hh24:mi:ss'))*24
                         END
                END)*TC1.USUARIOS),0) AS FDD_UIXTI,
               T.FPARENT,
               MUN.MUND_DESCRIPCION,
               MUN.MUND_REGIONAL,
               FDD_CAUSA,
               SUBSTR (C.FDC_DETALLE,8) AS DETALLE_CAUSA,
               TO_NUMBER(FDD_CAUSA_CREG) AS FDD_CAUSA_CREG,
               FDD_CAUSA_SSPD,
               FDD_EXCLUSION,
               FDD_TIPOCARGA,
               FDD_CONTINUIDAD, 
               FDD_USUARIOAP, 
               FDD_AJUSTADO, 
               FDD_TIPOAJUSTE,
               FDD_RADICADO, 
               FDD_APROBADO,
               --C.FDC_EXCLUSION AS EXCLUSION_CORREGIDA, --ESTE CAMPO ES PARA CORREGIR EL UPDATE DEL CAMPO DESDE LA TABLA QA_TFDDCAUSAS
               M.OBJETIVO AS OBJETIVO_INI
         FROM QA_TFDDPRELIMINAR_NR
         LEFT OUTER JOIN (SELECT TC1_CODCONEX, COUNT(TC1_TC1) AS USUARIOS FROM QA_TTC1 WHERE TC1_PERIODO=:PERIODO_TC1_YYYYMM GROUP BY TC1_CODCONEX) TC1 ON TC1.TC1_CODCONEX=FDD_CODIGOELEMENTO  --'201905'
         LEFT OUTER JOIN OMS.TRANSFOR@OMSPROD T ON T.CODE=FDD_CODIGOELEMENTO
         LEFT OUTER JOIN OMS.MANIOBRAS@OMSPROD M ON M.CODE=FDD_CODIGOEVENTO
         LEFT OUTER JOIN GE_TMUNDANE MUN ON MUN.MUND_MUNDANE = (T.DEP_ID*1000+T.MUNICIPIO)
         LEFT OUTER JOIN QA_TFDDCAUSAS C ON C.FDC_CAUSA_OMS=FDD_CAUSA
         
         WHERE (TO_CHAR(FDD_FINICIAL, 'MM/YYYY')  = SUBSTR(:FECHA_INICIO_DD_MM_YYYY,4)--'07/2019' 
                OR TO_CHAR(FDD_FFINAL, 'MM/YYYY') = SUBSTR(:FECHA_INICIO_DD_MM_YYYY,4))--'07/2019')

ORDER BY FDD_FINICIAL,FDD_CODIGOEVENTO,FDD_CODIGOELEMENTO
;
