---DATA DE APORTES SAIDI & SAIFI (SQL CON CURSOR)
SELECT TO_NUMBER(FDD_CODIGOEVENTO) AS FDD_CODIGOEVENTO,
TO_CHAR(FDD_FINICIAL,'DD/MM/YYYY HH24:MI:SS')AS FDD_FINICIAL,
TO_CHAR(FDD_FFINAL,'DD/MM/YYYY HH24:MI:SS')AS FDD_FFINAL,
FDD_DURACION,
FDD_CODIGOELEMENTO, 
T.LONGITUD,
T.LATITUD,
TC1.USUARIOS AS FDD_UI,
(FDD_DURACION*TC1.USUARIOS) AS FDD_UIXTI,
(FDD_DURACION*TC1.USUARIOS)/UIXTI_TOTAL.DURACION_TOTAL AS PORCENT_SAIDI,
TC1.USUARIOS/UI_TOTAL.FRECUENCIA_TOTAL AS PORCENT_SAIFI,
T.FPARENT,
MUN.MUND_DESCRIPCION,
FDD_CAUSA,
C.FDC_DETALLE AS DETALLE_CAUSA,
TO_NUMBER(FDD_CAUSA_CREG) AS FDD_CAUSA_CREG,
FDD_CAUSA_SSPD,
FDD_EXCLUSION,
REG.FDD_TIPOCARGA
FROM QA_TDATACSX 
LEFT OUTER JOIN OMS.TRANSFOR@OMSPROD T ON T.CODE=FDD_CODIGOELEMENTO
LEFT OUTER JOIN QA_TFDDCAUSAS C ON C.FDC_CAUSA_OMS=FDD_CAUSA
LEFT OUTER JOIN (SELECT FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO AS LLAVE_EVEELE, FDD_TIPOCARGA FROM QA_TFDDREGISTRO) REG ON REG.LLAVE_EVEELE=FDD_CODIGOEVENTO||FDD_CODIGOELEMENTO
LEFT OUTER JOIN GE_TMUNDANE MUN ON MUN.MUND_MUNDANE = (T.DEP_ID*1000+T.MUNICIPIO)
LEFT OUTER JOIN (SELECT TC1_CODCONEX, COUNT(TC1_TC1) AS USUARIOS FROM QA_TTC1 WHERE TC1_PERIODO='201904' GROUP BY TC1_CODCONEX) TC1 ON TC1.TC1_CODCONEX=FDD_CODIGOELEMENTO
LEFT OUTER JOIN
            (SELECT TO_CHAR(FDD_FINICIAL,'MM/YYYY') AS PERIODO, SUM(FDD_DURACION*TC1.USUARIOS) AS DURACION_TOTAL
            FROM QA_TDATACSX 
                LEFT OUTER JOIN (SELECT TC1_CODCONEX, COUNT(TC1_TC1) AS USUARIOS 
                                FROM QA_TTC1 
                                WHERE TC1_PERIODO='201904' GROUP BY TC1_CODCONEX) TC1 
                ON TC1.TC1_CODCONEX=FDD_CODIGOELEMENTO
                GROUP BY TO_CHAR(FDD_FINICIAL,'MM/YYYY')) UIXTI_TOTAL 
ON UIXTI_TOTAL.PERIODO = TO_CHAR(FDD_FINICIAL,'MM/YYYY')
LEFT OUTER JOIN 
            (SELECT TO_CHAR(FDD_FINICIAL,'MM/YYYY') AS PERIODO, SUM(TC1.USUARIOS) AS FRECUENCIA_TOTAL
            FROM QA_TDATACSX 
                LEFT OUTER JOIN (SELECT TC1_CODCONEX, COUNT(TC1_TC1) AS USUARIOS 
                                FROM QA_TTC1 
                                WHERE TC1_PERIODO='201904' GROUP BY TC1_CODCONEX) TC1 
                ON TC1.TC1_CODCONEX=FDD_CODIGOELEMENTO
                GROUP BY TO_CHAR(FDD_FINICIAL,'MM/YYYY')) UI_TOTAL 
ON UI_TOTAL.PERIODO=TO_CHAR(FDD_FINICIAL,'MM/YYYY')
;
