--PRESIONAR F5
SET HEADING OFF
SET FEEDBACK OFF
SPOOL C:\Users\esilvas\Desktop\REGISTRO.TXT
SELECT *    
FROM QA_TFDDREGISTRO WHERE FDD_PERIODO_OP='15/06/2019';
SPOOL OFF;
SET FEEDBACK ON
SET HEADING ON




