CREATE OR REPLACE PROCEDURE BRAE.QA_PFDDREPORTE_AI(FECHAOPERACION IN DATE)
AS
BEGIN
	
	INSERT INTO QA_TFDDREPORTE_AI
	SELECT FDD_CODIGOEVENTO
		,FDD_FINICIAL
		,FDD_FFINAL
		,FDD_DESCRIPCION
		,FDD_CAUSANTE_AFECTADO
		,FDD_CODIGOELEMENTO
		,FDD_TIPOELEMENTO
		,FDD_CAUSA
		,FDD_FESTIMADA
		,FDD_AFECTADOS_TOTALES 
		,FECHAOPERACION AS FDD_PERIODO_OP
	FROM QA_TFDDREGISTRO_AI;
	COMMIT;

	INSERT INTO QA_TLOG_EJECUCION
    SELECT SYSDATE,'QA_PFDDREPORTE_AI','PROCEDIMIENTO',UPPER(sys_context('USERENV','OS_USER')),'EXITOSO','Se ha configurado un EVENTO DE ALTO IMPACTO' FROM DUAL;
   	COMMIT;

END QA_PFDDREPORTE_AI;