CREATE OR REPLACE PROCEDURE BRAE.QA_PFDDREGISTRO_AI(FECHAOPERACION DATE)
AS

MAX_PERIODO_TC1 NUMBER;

BEGIN

-- MAX PERIODO TC1
    SELECT MAX(TC1_PERIODO)
    INTO MAX_PERIODO_TC1
    FROM BRAE.QA_TTC1;

    --AGREGA INFORMACION A LA TABLA DE REGISTRO PARA SU POSTERIOR ANALISIS
    --INSERT INTO QA_TFDDREGISTRO_AI 
    SELECT I.MINICIAL      AS FDD_CODIGOEVENTO
          ,I.FINICIAL      AS FDD_FINICIAL
          ,I.FFINAL        AS FDD_FFINAL
          ,M.DESCRIPTIO    AS FDD_DECRIPCION
          ,'A'             AS FDD_CAUSANTE_AFECTADO
          ,I.TRAFO         AS FDD_CODIGOELEMENTO
          ,'1'             AS FDD_TIPOELEMENTO
          ,C.FDC_CAUSA_015 AS FDD_CAUSA_CREG
          ,SYSDATE         AS FDD_FESTIMADA --RECIBIR POR INTERFACE COMO DATO DE ENTRADA
          ,CANT_USRS       AS FDD_AFECTADOS
          ,NULL            AS FDD_AFECTADOS_TOTALES --REALIZADA POR PROCEDIMIENTO
    FROM OMS.INTERUPC I
    LEFT OUTER JOIN OMS.MANIOBRAS M ON M.CODE=I.MINICIAL
    LEFT OUTER JOIN BRAE.QA_TFDDCAUSAS C ON C.FDC_CAUSA_OMS = M.CAUSA
    LEFT OUTER JOIN (
                     SELECT  TC1_CODCONEX,COUNT(TC1_CODCONEX) AS CANT_USRS
                     FROM QA_TTC1 
                     WHERE TC1_PERIODO =202207 --MAX_PERIODO_TC1
                     GROUP BY TC1_CODCONEX
                     ) ON TC1_CODCONEX = I.TRAFO
    WHERE TRUNC(FINICIAL) = TRUNC(TO_DATE(:FECHAOPERACION,'DD/MM/YYYY')) 
    --WHERE TRUNC(FINICIAL) = TRUNC(FECHAOPERACION)-- +4 HORAS DEL DIA ANTERIOR
    AND M.TIPO <> 'PRUEBA' 
    AND M.EJECUTADO = 1
    AND I.TYPEEQUIP IN ('Transformer')
    AND TC1_CODCONEX IS NOT NULL
    ;


END QA_PFDDREGISTRO_AI;
/

--TRAER CODIGO IUA PARA EL REPORTE

