CREATE OR REPLACE PROCEDURE QA_PFDDRESUMEN_AJ(FECHAOPERACION DATE)
AS
AJUSTADO NUMBER;
BEGIN
        --REPROCESO        
        SELECT COUNT(DISTINCT FDD_AJUSTADO) AS AJUSTADO
        INTO AJUSTADO
        FROM QA_TFDDREGISTRO
        WHERE TRUNC(FDD_FINICIAL,'MM') = TRUNC(FECHAOPERACION)
        AND   FDD_AJUSTADO = 'S'
        ;
        
        IF AJUSTADO = 0 THEN

            DELETE FROM BRAE.QA_TFDDRESUMEN_AJ
            WHERE FDD_PERIODO_OP = TRUNC(FECHAOPERACION);
            COMMIT;
            
            --INSERCION DE REGISTROS
            INSERT INTO BRAE.QA_TFDDRESUMEN_AJ 
            SELECT  P.FDD_TIPOCARGA                    AS FDD_TIPOCARGA
                   ,P.FDD_TIPOAJUSTE                   AS FDD_TIPOAJUSTE
                   ,R.FDD_CAUSA_CREG                   AS FDD_CAUSA_QOS
                   ,C2.FDC_DESCRIPCION                 AS FDD_DESCRIPCION_QOS
                   ,C2.FDC_EXCLUSION                   AS FDD_EXCLUSION_QOS
                   ,P.FDD_CAUSA_CREG                   AS FDD_CAUSA_OMS
                   ,C1.FDC_DESCRIPCION                 AS FDD_DESCRIPCION_OMS
                   ,C1.FDC_EXCLUSION                   AS FDD_EXCLUSION_OMS
                   ,COUNT(P.FDD_CODIGOELEMENTO)        AS FDD_CANTIDAD_REGISTROS
                   ,COUNT(DISTINCT P.FDD_CODIGOEVENTO) AS FDD_CANTIDAD_EVENTOS
                   ,TRUNC(FECHAOPERACION)         AS FDD_PERIODO_OP
            FROM BRAE.QA_TFDDPRELIMINAR_AJ P
            LEFT OUTER JOIN BRAE.QA_TFDDREGISTRO R ON R.FDD_CODIGOEVENTO||R.FDD_CODIGOELEMENTO = P.FDD_CODIGOEVENTO||P.FDD_CODIGOELEMENTO
            LEFT OUTER JOIN (SELECT DISTINCT FDC_CAUSA_015, FDC_DESCRIPCION,FDC_EXCLUSION FROM  BRAE.QA_TFDDCAUSAS) C1 ON C1.FDC_CAUSA_015 = P.FDD_CAUSA_CREG
            LEFT OUTER JOIN (SELECT DISTINCT FDC_CAUSA_015, FDC_DESCRIPCION,FDC_EXCLUSION FROM  BRAE.QA_TFDDCAUSAS) C2 ON C2.FDC_CAUSA_015 = R.FDD_CAUSA_CREG
            GROUP BY P.FDD_TIPOCARGA
                    ,R.FDD_CAUSA_CREG
                    ,P.FDD_CAUSA_CREG
                    ,C2.FDC_DESCRIPCION
                    ,C2.FDC_EXCLUSION
                    ,C1.FDC_DESCRIPCION
                    ,C1.FDC_EXCLUSION
                    ,P.FDD_TIPOAJUSTE
                    ,TRUNC(FECHAOPERACION)
            ORDER BY 1;
            COMMIT;
        ELSE
            DBMS_OUTPUT.PUT_LINE('No es posible generar un nuevo registro de informacion para este periodo.');
        END IF;

END QA_PFDDRESUMEN_AJ;


