create table QA_TBRA11_REPORTE
(
    BRA11_PERIODO_OP             DATE,
    BRA11_CODIGOELEMENTO         VARCHAR2(20),
    BRA11_CODIGOPROYECTO         VARCHAR2(20),
    BRA11_IUL                    VARCHAR2(5),
    BRA11_CODE_IUA               VARCHAR2(20),
    BRA11_CODE_IUA_PRO           VARCHAR2(20),
    BRA11_UNIDAD_CONSTRUCTIVA    VARCHAR2(20),
    BRA11_RPP                    NUMBER,
    BRA11_SALINIDAD              VARCHAR2(2),
    BRA11_TIPOINVERSION          VARCHAR2(5),
    BRA11_OBSERVACIONES          VARCHAR2(400),
    BRA11_FESTADO                NUMBER,
    BRA11_REMUNERACION_PENDIENTE NUMBER,
    BRA11_ESTADO                 VARCHAR2(20),
    BRA11_RESMETODOLOGIA         VARCHAR2(20),
    BRA11_ALTERNATIVA_VALORACION VARCHAR2(20),
    BRA11_ID_PLAN                NUMBER,
    BRA11_CANTIDAD_REPOSICIONES  NUMBER,
    BRA11_IDMERCADO              NUMBER
)
/


