CREATE OR REPLACE PROCEDURE QA_PBRA11_REGISTRO(FECHAOPERACION DATE) AS

    TYPE VAR_TABLE IS TABLE OF QA_TBRA11_REGISTRO%ROWTYPE;
    QA_VBRA11_REGISTRO VAR_TABLE;
    
    CANT     NUMBER;
    AJUSTADO NUMBER;
  
BEGIN
    --VALIDACIONES
    SELECT COUNT(*)
    INTO  CANT
    FROM  BRAE.QA_TBRA11_REGISTRO
    WHERE BRA11_PERIODO_OP =  TRUNC(FECHAOPERACION);

    --VERIFICACION DE ACCION DE AJUSTES REALIZADOS EN LA BASE DE DATOS PARA EL PERIODO 
    SELECT COUNT(DISTINCT FDD_AJUSTADO) AS AJUSTADO
    INTO AJUSTADO
    FROM QA_TFDDREGISTRO
    WHERE TRUNC(FDD_FINICIAL,'MM') = TRUNC(FECHAOPERACION)
    AND   FDD_AJUSTADO = 'S'
    ;

    IF AJUSTADO = 1 AND CANT = 0 THEN
        --ELIMINAR LOS ACTIVOS EN ESTADO 3 DEL MES ANTERIOR
        DELETE FROM QA_TBRA11_REGISTRO
            WHERE BRA11_ESTADO = 3;
        COMMIT;

        --INSERCION DE REGISTROS 
        INSERT INTO BRAE.QA_TBRA11_REGISTRO
        SELECT   FECHAOPERACION AS BRA11_PERIODO_OP
                ,TT2_CODIGOELEMENTO AS BRA11_CODIGOELEMENTO
                ,TT2_CODIGOPROYECTO AS BRA11_CODIGOPROYECTO
                ,TT2_IUL AS BRA11_IUL
                ,(CASE WHEN(TT2_ESTADO_BRA11<>'PLANEACION') THEN(TT2_CODE_IUA) ELSE(NULL)  END) AS BRA11_CODE_IUA
                ,(CASE WHEN(TT2_ESTADO_BRA11 ='PLANEACION') THEN(TT2_CODE_IUA) ELSE(NULL)  END) AS BRA11_CODE_IUA_PRO
                ,TT2_UNIDAD_CONSTRUCTIVA AS BRA11_UNIDAD_CONSTRUCTIVA
                ,TT2_RPP AS BRA11_RPP
                ,TT2_SALINIDAD AS BRA11_SALINIDAD
                ,TT2_TIPOINVERSION AS BRA11_TIPOINVERSION
                ,'NA' AS BRA11_OBSERVACIONES
                ,TRUNC(TT2_PERIODO_OP,'YYYY') AS BRA11_FESTADO
                ,TT2_REMUNERACION_PENDIENTE AS BRA11_REMUNERACION_PENDIENTE
                ,(CASE WHEN(TT2_ESTADO_BRA11 = 'OPERACION'   ) THEN(2)
                       WHEN(TT2_ESTADO_BRA11 = 'RETIRADO'    ) THEN(3)
                       WHEN(TT2_ESTADO_BRA11 = 'PLANEACION'  ) THEN(1)
                  END)   AS BRA11_ESTADO
                ,TT2_RESMETODOLOGIA AS BRA11_RESMETODOLOGIA
                ,(CASE WHEN(TT2_ALTERNATIVA_VALORACION = 'BRAEN') THEN(6) 
                       WHEN(TT2_ALTERNATIVA_VALORACION = 'BRAFO') THEN(3)
                       WHEN(TT2_ALTERNATIVA_VALORACION = 'INVA' ) THEN(5) 
                  END) AS BRA11_ALTERNATIVA_VALORACION 
                ,TT2_ID_PLAN AS BRA11_ID_PLAN
                ,(CASE WHEN(TT2_TIPOINVERSION IN (1,3)) THEN(1) ELSE(0) END) AS BRA11_CANTIDAD_REPOSICIONES
                ,TT2_IDMERCADO AS BRA11_IDMERCADO
        FROM QA_TTT2_REGISTRO
        WHERE TT2_PERIODO_OP = TRUNC(FECHAOPERACION);
        COMMIT;
        
        --ELIMINACION DE REGISTROS OBJETOS DE MODIFICACION EN EL PERIODO ACTUAL (ACUTALIZACION REGISTRO) ELIMINACION DE LOS ACTIVOS ESTADO=3

        DELETE FROM BRAE.QA_TBRA11_REGISTRO
        WHERE BRA11_CODIGOELEMENTO IN (
                                       SELECT DISTINCT BRA11_CODIGOELEMENTO
                                       FROM BRAE.QA_TBRA11_REGISTRO
                                       WHERE BRA11_PERIODO_OP = DATE'2022-12-01'-- TRUNC(FECHAOPERACION)
                                       )
        AND   BRA11_PERIODO_OP <> TRUNC(FECHAOPERACION)
        AND   BRA11_ESTADO = '2';
        COMMIT;


    END IF;
    
END QA_PBRA11_REGISTRO;

